// Toko Live v26: use remembered decisions as material for disagreement and challenge.
const norm=s=>String(s||'').toLowerCase().replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim();
const words=s=>norm(s).split(' ').filter(w=>w.length>3&&!/^(this|that|with|from|have|what|when|then|about|should|would|could|there|their|project)$/.test(w));
function project(q=''){return window.TokoResponseEngine?.detectProject?.(q)||String(window.TokoLiveContext?.snapshot?.().project||'').toUpperCase()||null}
function memories(p){const all=window.TokoDecisionMemory?.read?.()||[];return all.filter(x=>!p||String(x.project||'').toUpperCase()===p).slice(-30)}
function relevance(q,m){const a=new Set(words(q)),b=words([m.text,m.note,m.value,m.decision].filter(Boolean).join(' '));let n=0;for(const w of b)if(a.has(w))n++;return n}
function bestMemory(q,p){const ms=memories(p);return ms.map(m=>({m,s:relevance(q,m)})).sort((a,b)=>b.s-a.s)[0]?.m||ms[ms.length-1]||null}
function textOf(m){return String(m?.text||m?.decision||m?.note||m?.value||'').trim()}
function intent(q){const s=norm(q);if(/what did we decide|decision|remember|previous|before|history/.test(s))return'history';if(/disagree|challenge|push back|wrong|bad idea|devil.?s advocate|convince/.test(s))return'challenge';if(/changed|change my mind|opposite|reverse|instead/.test(s))return'change';return null}
function answer(q){const i=intent(q);if(!i)return null;const p=project(q),m=bestMemory(q,p),old=textOf(m);if(i==='history')return old?`The relevant remembered decision is: “${old}” I would treat that as context, not scripture; if the build now contradicts it, the build wins.`:`I do not have a useful stored decision for ${p||'that subject'} yet. I would rather say that than invent history.`;if(i==='challenge'){if(old)return `I would push back using our own earlier direction: “${old}” If the new idea contradicts that, it needs to buy us something concrete in play, readability or identity. Otherwise it is drift.`;return `I can challenge the idea without pretending we decided something earlier. What does it improve in play, what does it cost in clarity, and is that trade actually visible to the player?`;}if(i==='change'){if(old)return `Changing direction is fine, but name the trade. We previously held: “${old}” I would replace it only if the new direction solves a problem we can demonstrate, not because novelty feels like progress.`;return `I am open to reversing it, but I want a falsifiable reason: what current problem does the opposite direction solve, and what do we knowingly give up?`;}}
function append(who,text){const log=document.querySelector('.toko-chat .tc-log');if(!log)return;const d=document.createElement('div');d.className=who==='you'?'tc-you':'tc-me';d.textContent=text;log.appendChild(d)}
addEventListener('keydown',e=>{if(e.key!=='Enter')return;const input=e.target;if(!(input instanceof HTMLInputElement)||!input.closest('.toko-chat'))return;const q=input.value.trim(),r=answer(q);if(!q||!r)return;e.preventDefault();e.stopImmediatePropagation();append('you',q);input.value='';setTimeout(()=>{append('toko',r);dispatchEvent(new CustomEvent('toko:deep-answer',{detail:{text:r,project:project(q)}}))},90)},true);
window.TokoDebateMemory={answer,bestMemory,memories};
