const E={
'TINY HAWK':[
 {visual:'skate',source:'tinyhawk/DESIGN.md + current runtime',shows:'The project is currently code-rendered rather than driven by a repository image library.',critique:'Judge the low chase camera, readable board/body separation, flick-control legibility and sparse Skate Story atmosphere. A pretty still is secondary to whether motion reads.'},
 {visual:'skate',source:'tinyhawk/DESIGN.md',shows:'The locked intent is third-person free-roam skating with Skate-style load/flick controls and THPS vocabulary.',critique:'Reject anything that turns the game into a forward runner, fights the camera, or hides the board response.'},
 {visual:'next',source:'tinyhawk/DESIGN.md / VERSIONS.md',shows:'The useful next evidence is control feel and camera behavior in the playable build.',critique:'Prioritize right-stick load/flick reliability and chase-camera readability before decorative art.'}],
'EERI':[
 {visual:'../eeri/assets/2d/card_detail_v2.png',source:'eeri/assets/2d/card_detail_v2.png',shows:'A real repository material/detail asset from the Crafted World visual system.',critique:'Check whether the handmade material reads instantly at gameplay scale without obscuring platforms or hazards.'},
 {visual:'../eeri/assets/2d/felt_detail_v2.png',source:'eeri/assets/2d/felt_detail_v2.png + eeri/DESIGN.md',shows:'The felt/craft material language supporting the 80% platformer spine.',critique:'The craft texture should add charm, not visual noise. Traversable edges and machine interactions must stay obvious to a young player.'},
 {visual:'../eeri/assets/2d/day_sky_v2.webp',source:'eeri/assets/2d/day_sky_v2.webp + eeri/DESIGN.md',shows:'The current daytime world backdrop and palette direction.',critique:'Keep foreground interaction contrast stronger than the sky. World atmosphere should never compete with the next jump or machine cue.'}],
'PIRITORI':[
 {visual:'../piritori/art/v3/scenes/courtyard-prototype-v02.webp',source:'piritori/art/v3/scenes/courtyard-prototype-v02.webp',shows:'The repository courtyard prototype for the miniature physical-diorama direction.',critique:'Protect the clear central gameplay slab. Perimeter detail can sell Kallio, but must not collapse tactical silhouettes or route readability.'},
 {visual:'../piritori/art/v3/scenes/karhupuisto-v01.webp',source:'piritori/art/v3/scenes/karhupuisto-v01.webp + ART_BIBLE',shows:'A real location treatment testing grounded Helsinki identity inside the diorama language.',critique:'Push recognizable place-specific structure over generic Nordic scenery while keeping the playfield tactically clean.'},
 {visual:'../piritori/art/v3/scenes/toko-slomo-noodles-prototype-v01.webp',source:'piritori/art/v3/scenes/toko-slomo-noodles-prototype-v01.webp',shows:'The authored Toko Slomo location memory.',critique:'The location should feel narratively specific before it feels busy: restaurant identity, information/gambling function and character staging first.'}],
'BETTERMENT':[
 {visual:'../kindling/art/camp-night-clean.png',source:'kindling/art/camp-night-clean.png + BETTERMENT_OWNER_DIRECTION.md',shows:'The approved dark-fantasy bonfire environment direction.',critique:'The surrounding world can feel threatening, but the self-care surface itself must remain warm, safe and immediately usable.'},
 {visual:'../kindling/art/ashling.png',source:'kindling/art/ashling.png',shows:'A real companion asset from the current repository.',critique:'Companion personality should reward attention without turning missed days into guilt, punishment or streak anxiety.'},
 {visual:'../kindling/art/fire-states.png',source:'kindling/art/fire-states.png + owner direction',shows:'The fire-state reward language tied to daily progress.',critique:'Five daily goals is the locked target. Fire progression should make completion legible at a glance without becoming a punitive meter.'}],
'HYPER DAGGER':[
 {visual:'../hyperdagger/icon-512.png',source:'hyperdagger/icon-512.png + hyperdagger/assets/*.glb',shows:'The live project has a substantial 3D enemy asset set including skull, skulldread, brute, revenant and others; the icon is the available 2D repository preview.',critique:'The current target is Devil Daggers feel: oppressive silhouettes, immediate threat readability and sparse background. Asset quantity is not the goal.'},
 {visual:'../hyperdagger/icon-192.png',source:'hyperdagger/ART_PIPELINE.md + assets/skull.glb',shows:'The art pipeline and real skull model are present even though Toko Live cannot directly rasterize GLB memories.',critique:'Basic skulls need stronger menace and mouth animation. Avoid ornamental environment density that weakens threat focus.'},
 {visual:'../hyperdagger/favicon.png',source:'hyperdagger/VERSIONS.md',shows:'A repository-backed project marker while the next useful evidence remains runtime feel.',critique:'Evaluate weapon presence, enemy contrast, speed and dread second-to-second rather than chasing Hyper Demon spectacle.'}],
'FLASH PRINCE':[
 {visual:'../flashprince/ref/flash-prince.png',source:'flashprince/ref/flash-prince.png + flashprince/ART.md',shows:'A real Flash Prince repository reference image.',critique:'Animation identity must stay coherent per character. Do not mix old and new animation styles on the default character.'},
 {visual:'../flashprince/ref/conrad.png',source:'flashprince/ref/conrad.png + animation-locks.json',shows:'The Conrad/Flashback movement reference used to anchor rotoscope readability.',critique:'Low climbs, jumps and ledge transitions should read as deliberate authored movement, not animation-state glitches.'},
 {visual:'../flashprince/ref/flash-prince-classic.png',source:'flashprince/ref/flash-prince-classic.png + VERSIONS.md',shows:'The classic visual reference retained in the repository.',critique:'Preserve cinematic silhouette and timing while adding shooting/shield mechanics without making movement feel like a generic action platformer.'}],
'SUDS JACK':[
 {visual:'grid',source:'Suds Jack runtime + project direction',shows:'The project is primarily vector/code-rendered, so the meaningful evidence is its live lane geometry and camera rather than a PNG asset.',critique:'Camera must be lower and more Tempest-like. Side ramps and topography need depth while the nine-lane score-attack read remains immediate.'},
 {visual:'grid',source:'current Suds Jack implementation',shows:'The core visual problem is perspective and topography, not missing illustration.',critique:'If the camera change is not instantly visible, it is not enough. Depth should change the second-to-second spatial read.'},
 {visual:'next',source:'project direction',shows:'The next evidence should be a visibly versioned playable camera/topography pass.',critique:'Test horizon, ramp silhouette and lane readability together; do not add detail that hides the dive line.'}],
'TOKO DROP':[
 {visual:'drop',source:'GDD.md + TOKO_DROP_ROADMAP.md',shows:'The repository currently expresses the strongest authority through design documents and code rather than a dedicated visual memory set.',critique:'The visual target should support slow readable movement, dash commitment, preset combat rounds and gelatinous identity rather than generic twin-stick noise.'},
 {visual:'drop',source:'GDD.md',shows:'The core combat identity is authored rounds followed by roguelite upgrades.',critique:'Enemies, bullets and upgrade feedback need hierarchy. Gelatin style should make impacts juicy without making danger ambiguous.'},
 {visual:'next',source:'TOKO_DROP_ROADMAP.md',shows:'Roadmap evidence should drive the NEXT card until stronger runtime captures exist.',critique:'Prioritize the core round/dash/shoot loop and readable feedback before expanding content breadth.'}]
};
export function evidence(project,slot=0){return E[project]?.[slot]||null}
export function critiquePrompt(project,slot=0){const e=evidence(project,slot);if(!e)return `Critique ${project} against its design direction.`;return `Critique ${project} using ${e.source}. The evidence shows: ${e.shows} Check this specifically: ${e.critique}`}
export function evidenceNote(project,slot=0){const e=evidence(project,slot);return e?`${e.shows} SOURCE: ${e.source}`:''}
export const PROJECT_EVIDENCE=E;