// Toko Live v45 — opinions move with project evidence, explicit decisions and structured playtest feedback.
const KEY='tokoLive.evidenceOpinions.v1';
const norm=s=>String(s||'').toLowerCase();
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}};
const write=x=>{try{localStorage.setItem(KEY,JSON.stringify(x))}catch{}};
function project(q){return window.TokoProjectState?.project?.(q)||window.TokoResponseEngine?.detectProject?.(q)||String(window.TokoLiveContext?.snapshot?.().project||'').toUpperCase()||null}
function evidence(p){const state=window.TokoProjectState?.summary?.(p);if(!state)return null;const mem=window.TokoDecisionMemory?.relevant?.(p)||{};const accepted=(mem.accepted||mem.approved||[]).slice(0,3),rejected=(mem.rejected||[]).slice(0,3),superseded=(mem.superseded||[]).slice(0,2),feedback=window.TokoFeedback?.evidence?.(p)||null;return{state,accepted,rejected,superseded,feedback}}
function signature(e){return JSON.stringify({next:e.state.next,problems:e.state.problems,accepted:e.accepted.map(x=>x.topic||x.text),rejected:e.rejected.map(x=>x.topic||x.text),superseded:e.superseded.map(x=>x.topic||x.text),feedback:e.feedback?{id:e.feedback.id,strong:e.feedback.strong?.map(x=>[x.question,x.topAnswer,x.consensus])}:null})}
function position(p,e){const pressure=e.state.problems?.[0]||'the core experience';const locked=e.accepted[0]?.topic||e.state.decisions?.[0]||'';const rejected=e.rejected[0]?.topic||'';let text=`I would push ${e.state.next}. The strongest project evidence is that ${pressure} is still unresolved.`;if(e.feedback?.strong?.length){const f=e.feedback.strong[0];text+=` The latest playtest signal also points to “${f.topAnswer}” (${Math.round(f.consensus*100)}% on “${f.question}”).`}if(locked)text+=` Your explicit decision remains authoritative: ${locked}.`;if(rejected)text+=` I would not reopen ${rejected} unless new evidence gives us a reason.`;if(e.feedback?.contested?.length)text+=` Some feedback is still contested, so I would treat that as a question to test, not a decision.`;return text}
function answer(q){const s=norm(q);if(!/(what do you think|your opinion|do you agree|do you disagree|would you change|changed your mind|still think|convince me|should we)/.test(s))return null;const p=project(q),e=evidence(p);if(!p||!e)return null;const sig=signature(e),db=read(),old=db[p],now=position(p,e);let prefix='';if(old&&old.signature!==sig)prefix='My position moved because the project evidence, feedback, or an explicit decision changed. ';else if(old&&/changed your mind|still think/.test(s))prefix='I have not changed position from the current evidence. ';db[p]={signature:sig,text:now,updated:Date.now()};write(db);return `${p}: ${prefix}${now}`}
function append(who,text){const log=document.querySelector('.toko-chat .tc-log');if(!log)return;const d=document.createElement('p');d.className=who==='you'?'tc-you':'tc-me';d.textContent=text;log.appendChild(d);log.scrollTop=log.scrollHeight}
function boot(){const input=document.querySelector('.toko-chat .tc-say-row input');if(!input)return requestAnimationFrame(boot);input.addEventListener('keydown',e=>{if(e.key!=='Enter')return;const q=input.value.trim(),r=answer(q);if(!q||!r)return;e.preventDefault();e.stopImmediatePropagation();append('you',q);input.value='';const st=document.querySelector('.stage');if(st)st.dataset.reaction=/agree/.test(norm(q))?'agree':/disagree|change/.test(norm(q))?'considering':'curious';setTimeout(()=>append('toko',r),70)},true)}boot();
addEventListener('toko:decision',()=>{const st=document.querySelector('.stage');if(st)st.dataset.reaction='considering'});addEventListener('toko:feedback',()=>{const st=document.querySelector('.stage');if(st)st.dataset.reaction='considering'});
window.TokoEvidenceOpinion={version:45,answer,evidence,read};