// Toko Live v4 — character presence: persistent conversational mood + spatial project cards.
// Live implementation is mirrored on gh-pages; keep this source version aligned.
import '../toko/js/mind.js?v=10';
import '../toko/js/project-conversation.js?v=2';
import '../toko/js/brain-conversation.js?v=1';
import '../toko/js/conversation-plus.js?v=10';
import '../toko/js/chat-layout-fix.js?v=1';
import { mountChat } from '../toko/js/chat.js?v=20';
import { drawFace } from '../toko/js/face.js';
import { TOKO } from '../toko/js/palette.js';
const slot=document.querySelector('#chat-slot'),chat=mountChat(slot,{where:'in',openOnLoad:true});window.__tokoLiveChat=chat;
const canvas=document.querySelector('#toko-stage'),ctx=canvas.getContext('2d'),stage=document.querySelector('.stage'),label=document.querySelector('#state-label'),thought=document.querySelector('#thought');
let state='listening',stateUntil=0,mx=0,my=0,gaze=0,answerStart=0,mood=0,moodUntil=0,focus=null,cards=[];
const PROJECTS=[['TINY HAWK','FLICK / FREE ROAM / THE PART'],['EERI','CRAFTED / PLATFORM / MACHINES'],['PIRITORI','KALLIO / MARKET / CONSEQUENCE'],['BETTERMENT','TODAY / FIVE / BONFIRE'],['HYPER DAGGER','DEVIL DAGGERS / FEEL / SKULLS'],['SUDS JACK','TEMPEST / DIVE / TOPOGRAPHY'],['FLASH PRINCE','ROTOSCOPE / CLIMB / SHIELD'],['TOKO DROP','ROUNDS / DASH / GELATIN']];
const projectFrom=s=>PROJECTS.find(p=>s.toUpperCase().includes(p[0]))||null;
function setState(s,ms,note,text=''){state=s;stateUntil=performance.now()+ms;stage.dataset.state=s;label.textContent=s.toUpperCase();if(note)thought.textContent=note.toUpperCase();if(text)answerStart=performance.now()}
function setMood(v){mood=Math.max(-1,Math.min(1,mood*.45+v));moodUntil=performance.now()+12000}
addEventListener('pointermove',e=>{mx=(e.clientX/innerWidth-.5)*2;my=(e.clientY/innerHeight-.5)*2},{passive:true});
function rr(x,y,w,h,r,f){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=f;ctx.fill()}
function limb(x,y,len,a){ctx.save();ctx.translate(x,y);ctx.rotate(a);rr(-15,0,30,len,13,'#0c0c10');ctx.fillStyle='#f0027f';ctx.beginPath();ctx.arc(0,len,13,0,Math.PI*2);ctx.fill();ctx.restore()}
function spawnCards(p){focus=p;cards=p?[{title:p[0],sub:p[1],a:-.8},{title:'WHY?',sub:'DESIGN INTENT',a:.05},{title:'NEXT',sub:'CURRENT DIRECTION',a:.85}]:[]}
function drawCards(cx,cy,t){ctx.save();ctx.textAlign='center';cards.forEach((c,i)=>{const a=c.a+Math.sin(t*.001+i)*.035,x=cx+Math.cos(a)*230,y=cy+40+Math.sin(a)*165;rr(x-85,y-29,170,58,4,'rgba(8,8,12,.88)');ctx.strokeStyle=i?'#4a2940':'#f0027f';ctx.strokeRect(x-85,y-29,170,58);ctx.font='bold 13px Courier New';ctx.fillStyle=i?'#f0027f':'#fff';ctx.fillText(c.title,x,y-6);ctx.font='10px Courier New';ctx.fillStyle='#9a9aa2';ctx.fillText(c.sub,x,y+13)});ctx.restore()}
function draw(t){if(moodUntil&&t>moodUntil)mood*=.96;const W=canvas.width,H=canvas.height;ctx.clearRect(0,0,W,H);gaze+=(mx-gaze)*.055;const cx=W*.5+gaze*13,cy=H*.37+my*6+Math.sin(t*.0017)*5;drawCards(cx,cy,t);ctx.save();ctx.translate(cx,H*.53+Math.sin(t*.0012)*4);ctx.fillStyle='#101015';ctx.beginPath();ctx.moveTo(-138,58);ctx.quadraticCurveTo(-120,-40,-72,-58);ctx.lineTo(72,-58);ctx.quadraticCurveTo(120,-40,138,58);ctx.lineTo(106,188);ctx.lineTo(-106,188);ctx.closePath();ctx.fill();let la=.04,ra=-.04;if(state==='thinking'){la=-.78;ra=.14}if(state==='talking'){la=-.35+Math.sin(t*.012)*.25;ra=.38+Math.sin(t*.01+1)*.23}if(state==='pleased'){la=-.86;ra=.86}if(state==='glitch'){la=.58;ra=-.58}if(state==='project'){la=-.18;ra=.98}if(focus&&state==='talking')la=-.65;limb(-108,28,128,la);limb(108,28,128,ra);ctx.restore();ctx.save();ctx.translate(cx-118,cy-118);ctx.fillStyle=TOKO.MAGENTA||'#f0027f';ctx.beginPath();ctx.arc(118,118,112,0,Math.PI*2);ctx.fill();ctx.fillStyle='#050507';ctx.beginPath();ctx.arc(118,118,94,0,Math.PI*2);ctx.fill();let open=.08+mood*.035;if(state==='talking'||state==='pleased')open=.12+Math.max(0,Math.sin((t-answerStart)*.019))*.45;if(state==='thinking')open=.02;if(state==='glitch')open=.72;drawFace(ctx,18,18,200,{color:'#fff',open});ctx.restore();ctx.font='12px Courier New';ctx.fillStyle='rgba(240,2,127,.72)';ctx.fillText(`${mood>0?'WARM':mood<0?'TENSE':'NEUTRAL'} / ${focus?focus[0]:'LOCAL'} / ${state.toUpperCase()}`,24,H-26)}
function loop(t){if(stateUntil&&t>stateUntil){state='listening';label.textContent='LISTENING';stateUntil=0}draw(t);requestAnimationFrame(loop)}requestAnimationFrame(loop);
const log=document.querySelector('.toko-chat .tc-log');if(log)new MutationObserver(ms=>{for(const n of ms.flatMap(m=>[...m.addedNodes]).filter(n=>n.nodeType===1)){const text=(n.textContent||'').trim(),who=n.classList.contains('tc-you')?'you':n.classList.contains('tc-me')?'me':null;if(!text||!who)continue;const p=projectFrom(text);if(p){spawnCards(p);setState('project',who==='you'?1500:3200,`${p[0]} CONTEXT ON THE TABLE.`,who==='me'?text:'');continue}if(who==='you'&&/^(NO|ACTUALLY|CORRECTION|YOU ARE WRONG|THAT IS WRONG|NOT QUITE)/i.test(text)){setMood(-.35);setState('glitch',1700,'CORRECTION RECEIVED. RE-WEIGHTING MEMORY.');continue}if(who==='you'){if(/thanks|great|good|yes|exactly/i.test(text))setMood(.28);setState('thinking',1100,'LOOKING FOR RELATED MEMORY, DESIGN AND PROJECT EVIDENCE.')}else{if(/good|yes|right|favourite|beaut|fun|thank/i.test(text))setMood(.2);setState(mood>.3?'pleased':'talking',Math.min(3800,1300+text.length*11),text,text)}}}).observe(log,{childList:true,subtree:true});
document.querySelectorAll('[data-say]').forEach(b=>b.addEventListener('click',()=>{const input=document.querySelector('.toko-chat .tc-say-row input');if(input){input.value=b.dataset.say;input.focus();input.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}))}}));