import { mountChat } from '../toko/js/chat.js?v=20';import { drawFace } from '../toko/js/face.js';import { TOKO } from '../toko/js/palette.js';
const slot=document.querySelector('#chat-slot'),chat=mountChat(slot,{where:'in',openOnLoad:true});window.__tokoLiveChat=chat;await import('../toko/js/mind.js?v=10');await import('../toko/js/project-conversation.js?v=2');await import('../toko/js/brain-conversation.js?v=1');await import('../toko/js/conversation-plus.js?v=10');await import('../toko/js/chat-layout-fix.js?v=1');
const canvas=document.querySelector('#toko-stage'),ctx=canvas.getContext('2d'),stage=document.querySelector('.stage'),label=document.querySelector('#state-label'),thought=document.querySelector('#thought');let state='listening',until=0,mx=0,my=0,gaze=0,mood=0,moodUntil=0,focus=null,cards=[],cardRects=[],answerStart=0,pointAt=-1;
const PROJECTS=[['TINY HAWK','FLICK / FREE ROAM / THE PART'],['EERI','CRAFTED / PLATFORM / MACHINES'],['PIRITORI','KALLIO / MARKET / CONSEQUENCE'],['BETTERMENT','TODAY / FIVE / BONFIRE'],['HYPER DAGGER','DEVIL DAGGERS / FEEL / SKULLS'],['SUDS JACK','TEMPEST / DIVE / TOPOGRAPHY'],['FLASH PRINCE','ROTOSCOPE / CLIMB / SHIELD'],['TOKO DROP','ROUNDS / DASH / GELATIN']];const projectFrom=s=>PROJECTS.find(p=>s.toUpperCase().includes(p[0]))||null;
function setState(s,ms,note,text=''){state=s;until=performance.now()+ms;stage.dataset.state=s;label.textContent=s.toUpperCase();if(note)thought.textContent=note.toUpperCase();if(text)answerStart=performance.now()}
function moodBy(v){mood=Math.max(-1,Math.min(1,mood*.45+v));moodUntil=performance.now()+12000}
function spawn(p){focus=p;cards=p?[{title:p[0],sub:p[1],ask:`Tell me the design of ${p[0]}`},{title:'WHY?',sub:'DESIGN INTENT',ask:`Why is ${p[0]} designed this way?`},{title:'NEXT',sub:'CURRENT DIRECTION',ask:`What is next for ${p[0]}?`}]:[]}
function say(q){const input=document.querySelector('.toko-chat .tc-say-row input');if(!input)return;input.value=q;input.focus();input.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true}))}
addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();mx=(e.clientX/innerWidth-.5)*2;my=(e.clientY/innerHeight-.5)*2;const x=(e.clientX-r.left)*canvas.width/r.width,y=(e.clientY-r.top)*canvas.height/r.height;pointAt=cardRects.findIndex(c=>x>=c.x&&x<=c.x+c.w&&y>=c.y&&y<=c.y+c.h);canvas.style.cursor=pointAt>=0?'pointer':'default'},{passive:true});canvas.addEventListener('click',()=>{if(pointAt>=0&&cards[pointAt]){setState('thinking',900,`OPENING ${cards[pointAt].title}.`);say(cards[pointAt].ask)}});
function rr(x,y,w,h,r,f){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=f;ctx.fill()}function limb(x,y,len,a){ctx.save();ctx.translate(x,y);ctx.rotate(a);rr(-15,0,30,len,13,'#0c0c10');ctx.fillStyle='#f0027f';ctx.beginPath();ctx.arc(0,len,13,0,Math.PI*2);ctx.fill();ctx.restore()}
function drawCards(cx,cy,t){cardRects=[];ctx.save();ctx.textAlign='center';cards.forEach((c,i)=>{const a=[-.8,.05,.85][i]+Math.sin(t*.001+i)*.025,x=cx+Math.cos(a)*230,y=cy+40+Math.sin(a)*165,w=176,h=62;cardRects.push({x:x-w/2,y:y-h/2,w,h});rr(x-w/2,y-h/2,w,h,5,pointAt===i?'rgba(42,13,32,.96)':'rgba(8,8,12,.9)');ctx.strokeStyle=pointAt===i?'#fff':i?'#4a2940':'#f0027f';ctx.lineWidth=pointAt===i?2:1;ctx.strokeRect(x-w/2,y-h/2,w,h);ctx.font='bold 13px Courier New';ctx.fillStyle=i?'#f0027f':'#fff';ctx.fillText(c.title,x,y-7);ctx.font='10px Courier New';ctx.fillStyle='#aaa';ctx.fillText(c.sub,x,y+12);if(pointAt===i){ctx.fillStyle='#fff';ctx.fillText('OPEN',x,y+25)}});ctx.restore()}
function draw(t){if(moodUntil&&t>moodUntil)mood*=.96;const W=canvas.width,H=canvas.height;ctx.clearRect(0,0,W,H);gaze+=(mx-gaze)*.05;const cx=W*.5+gaze*13,cy=H*.37+my*5+Math.sin(t*.0017)*5;const glow=ctx.createRadialGradient(cx,H*.72,20,cx,H*.72,280);glow.addColorStop(0,mood>0?'rgba(240,2,127,.26)':'rgba(240,2,127,.16)');glow.addColorStop(1,'rgba(240,2,127,0)');ctx.fillStyle=glow;ctx.fillRect(0,H*.35,W,H*.65);drawCards(cx,cy,t);ctx.save();ctx.translate(cx,H*.53+Math.sin(t*.0012)*4);ctx.fillStyle='#101015';ctx.beginPath();ctx.moveTo(-138,58);ctx.quadraticCurveTo(-120,-40,-72,-58);ctx.lineTo(72,-58);ctx.quadraticCurveTo(120,-40,138,58);ctx.lineTo(106,188);ctx.lineTo(-106,188);ctx.closePath();ctx.fill();let la=.04,ra=-.04;if(state==='thinking'){la=-.78;ra=.14}if(state==='talking'){la=-.35+Math.sin(t*.012)*.24;ra=.38+Math.sin(t*.01+1)*.22}if(state==='pleased'){la=-.86;ra=.86}if(state==='glitch'){la=.58;ra=-.58}if(state==='project'){la=-.18;ra=.98}if(pointAt>=0){const target=cardRects[pointAt],tx=target.x+target.w/2;la=tx<cx?-1.0:-.15;ra=tx>=cx?1.0:.15}limb(-108,28,128,la);limb(108,28,128,ra);ctx.restore();ctx.save();ctx.translate(cx-118,cy-118);if(state==='glitch')ctx.translate(Math.sin(t*.08)*5,0);ctx.fillStyle=TOKO.MAGENTA||'#f0027f';ctx.beginPath();ctx.arc(118,118,112,0,Math.PI*2);ctx.fill();ctx.fillStyle='#050507';ctx.beginPath();ctx.arc(118,118,94,0,Math.PI*2);ctx.fill();let open=.08+mood*.035;if(state==='talking'||state==='pleased')open=.12+Math.max(0,Math.sin((t-answerStart)*.019))*.45;if(state==='thinking')open=.02;if(state==='glitch')open=.72;drawFace(ctx,18,18,200,{color:'#fff',open});ctx.restore();ctx.font='12px Courier New';ctx.fillStyle='rgba(240,2,127,.72)';ctx.fillText(`${mood>0?'WARM':mood<0?'TENSE':'NEUTRAL'} / ${focus?focus[0]:'LOCAL'} / ${state.toUpperCase()}`,24,H-26)}function loop(t){if(until&&t>until){state='listening';label.textContent='LISTENING';until=0}draw(t);requestAnimationFrame(loop)}requestAnimationFrame(loop);
function classify(text,who){const p=projectFrom(text);if(p){spawn(p);return['project',who==='you'?1500:3200,`${p[0]} CONTEXT ON THE TABLE.`]}if(who==='you'&&/^(no|actually|correction|you are wrong|that is wrong|not quite)/i.test(text)){moodBy(-.35);return['glitch',1700,'CORRECTION RECEIVED. RE-WEIGHTING MEMORY.']}if(who==='you'){if(/thanks|great|good|yes|exactly/i.test(text))moodBy(.28);return['thinking',1100,'LOOKING FOR RELATED MEMORY, DESIGN AND PROJECT EVIDENCE.']}if(/good|yes|right|favourite|beaut|fun|thank/i.test(text))moodBy(.2);return[mood>.3?'pleased':'talking',Math.min(4000,1300+text.length*11),text]}
const log=document.querySelector('.toko-chat .tc-log');if(log)new MutationObserver(ms=>{for(const n of ms.flatMap(m=>[...m.addedNodes]).filter(n=>n.nodeType===1)){const text=(n.textContent||'').trim(),who=n.classList.contains('tc-you')?'you':n.classList.contains('tc-me')?'me':null;if(!text||!who)continue;const [s,d,note]=classify(text,who);setState(s,d,note,who==='me'?text:'')}}).observe(log,{childList:true,subtree:true});document.querySelectorAll('[data-say]').forEach(b=>b.addEventListener('click',()=>say(b.dataset.say)));