// Toko Live v36: evolving opinions grounded strictly in user-authored turns.
const KEY='tokoLive.opinions.v1';
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{"items":{}}')}catch{return{items:{}}}};
const write=x=>{try{localStorage.setItem(KEY,JSON.stringify(x))}catch{}};
const norm=s=>String(s||'').toLowerCase().replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim();
function project(q=''){return window.TokoResponseEngine?.detectProject?.(q)||String(window.TokoLiveContext?.snapshot?.().project||'').toUpperCase()||'GENERAL'}
function stance(text){const s=norm(text);let n=0;if(/\b(love|good|works|better|strong|right|keep|yes|great|like)\b/.test(s))n++;if(/\b(bad|weak|wrong|hate|worse|broken|remove|cut)\b|\b(no|dont|do not)\b/.test(s))n--;return n}
function subject(text){const stop=new Set('this that what with from have should would could about there their then than more really think toko project into only also just does dont good bad right wrong'.split(' '));return norm(text).split(' ').filter(w=>w.length>3&&!stop.has(w)).slice(0,5).join(' ')||'current direction'}
function observe(text,who='you'){if(!text||who!=='you')return;const p=project(text),sub=subject(text),delta=stance(text);if(!delta)return;const s=read();s.items[p] ||= {};const x=s.items[p][sub]||{score:0,hits:0,last:'',updated:0,source:'user'};x.score=Math.max(-4,Math.min(4,x.score+delta));x.hits++;x.last=text;x.updated=Date.now();x.source='user';s.items[p][sub]=x;write(s)}
function strongest(p){const xs=Object.entries(read().items[p]||{}).filter(([,x])=>!x.source||x.source==='user').map(([subject,x])=>({subject,...x}));return xs.sort((a,b)=>Math.abs(b.score)*2+b.hits-(Math.abs(a.score)*2+a.hits))[0]||null}
function answer(q){const s=norm(q);if(!/(your opinion|what do you think|where do you stand|changed your mind|still think|strongest opinion|convince me)/.test(s))return null;const p=project(q),x=strongest(p);if(!x)return `I have a point of view, but not enough repeated conversation on ${p==='GENERAL'?'this':p} to pretend it has evolved yet. Give me something to react to and I will keep the pressure of that discussion.`;const strength=Math.abs(x.score)>=3?'strongly':Math.abs(x.score)>=2?'fairly clearly':'slightly';const direction=x.score>0?'toward keeping or strengthening it':'toward changing or cutting it';return `My accumulated position on “${x.subject}” leans ${strength} ${direction}. That comes from what you have pushed for or against, not from me feeding my own replies back into memory. If new evidence in the build contradicts it, I should move.`}
function append(who,text){const log=document.querySelector('.toko-chat .tc-log');if(!log)return;const d=document.createElement('div');d.className=who==='you'?'tc-you':'tc-me';d.textContent=text;log.appendChild(d)}
function boot(){const log=document.querySelector('.toko-chat .tc-log');if(!log)return requestAnimationFrame(boot);new MutationObserver(ms=>{for(const m of ms)for(const n of m.addedNodes){if(n.nodeType!==1)continue;const users=n.matches?.('.tc-you')?[n]:[...(n.querySelectorAll?.('.tc-you')||[])];for(const u of users)observe(u.textContent,'you')}}).observe(log,{childList:true,subtree:true})}boot();
addEventListener('keydown',e=>{if(e.key!=='Enter')return;const input=e.target;if(!(input instanceof HTMLInputElement)||!input.closest('.toko-chat'))return;const q=input.value.trim(),r=answer(q);if(!q||!r)return;e.preventDefault();e.stopImmediatePropagation();append('you',q);input.value='';setTimeout(()=>append('toko',r),80)},true);
window.TokoOpinionMemory={read,observe,strongest,answer,reset(){write({items:{}})}};
