// Toko Live v41 — compact project-state authority with typo-tolerant explicit project resolution.
const S={
'TINY HAWK':{goal:'THPS vocabulary with Skate-style free-roam feel and a fat bird skater',current:'playable movement/camera work is the meaningful evidence',problems:['right-stick load/flick reliability','low chase-camera readability'],decisions:['movement feel before trick breadth','playable builds belong on the hub'],next:'lock deterministic board control and camera readability'},
'EERI':{goal:'young-player-first crafted platformer with big rideable machines',current:'four-world platforming structure with crafted material language',problems:['jump/climb edge cases','machine affordance readability'],decisions:['80% platforming spine','generous retries','craft detail must not hide gameplay'],next:'stabilize traversal and machine interactions before decorative expansion'},
'PIRITORI':{goal:'Kallio Drug Wars economy fused with consequential tactical encounters',current:'Era I map/market/encounter foundation and miniature-diorama art direction',problems:['complete economy loop','location specificity','combat readability'],decisions:['Era I before Era II','Kalasatama east cutoff','clean central tactical slabs'],next:'complete one buy-travel-encounter-sell-consequence loop'},
'BETTERMENT':{goal:'five-goal self-care loop expressed through a dark-fantasy bonfire',current:'Today/navigation/companion foundation',problems:['daily-loop clarity','functional destination depth'],decisions:['no punishment for absence','five daily goals','dark mode primary'],next:'finish the complete Today loop before deeper fantasy systems'},
'HYPER DAGGER':{goal:'Devil Daggers look-and-feel pressure rather than feature parity',current:'playable arena with enemy/weapon foundation',problems:['skull menace','weapon/enemy readability','background restraint'],decisions:['Devil Daggers is the reference','look and feel beats enemy-count parity'],next:'tighten threat silhouettes, skull mouth motion and gameplay-speed readability'},
'SUDS JACK':{goal:'nine-lane Bomb Jack score attack through a Tempest perspective',current:'vector/code-rendered lane game',problems:['camera still needs unmistakable Tempest depth','topography must stay readable'],decisions:['lower camera','ramped sides','visible versioning'],next:'make camera/topography change unmistakable in the playable hub build'},
'FLASH PRINCE':{goal:'Flashback-like cinematic traversal with shooting and shield layered on top',current:'two character styles and a broad traversal animation set',problems:['mixed animation identities','low-climb/jump glitches'],decisions:['old style becomes secondary character','default new character gets its own full animation set'],next:'separate animation sets completely and fix traversal transitions'},
'TOKO DROP':{goal:'slow readable top-down shooter with dash commitment and gelatin identity',current:'round/dash/shoot design foundation',problems:['core combat feel','feedback hierarchy'],decisions:['right-stick aim/shoot','roguelite upgrades after preset rounds','slower movement plus dash'],next:'prove the small round/dash/shoot loop before content breadth'}
};
const ALIASES={'TINY HAWK':['tiny hawk','tinyhawk'],'EERI':['eeri'],'PIRITORI':['piritori'],'BETTERMENT':['betterment','kindling'],'HYPER DAGGER':['hyper dagger','hyperdagger'],'SUDS JACK':['suds jack','sudsjack'],'FLASH PRINCE':['flash prince','flashprince'],'TOKO DROP':['toko drop','tokodrop']};
const norm=s=>String(s||'').toLowerCase().replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim();
function dist(a,b){if(Math.abs(a.length-b.length)>2)return 99;const d=Array.from({length:a.length+1},(_,i)=>[i]);for(let j=1;j<=b.length;j++)d[0][j]=j;for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++)d[i][j]=Math.min(d[i-1][j]+1,d[i][j-1]+1,d[i-1][j-1]+(a[i-1]===b[j-1]?0:1));return d[a.length][b.length]}
function explicitProject(q=''){const n=norm(q),compact=n.replace(/ /g,'');for(const [p,as] of Object.entries(ALIASES)){for(const a of as){if(n.includes(a)||compact.includes(a.replace(/ /g,'')))return p;const words=n.split(' '),aw=a.split(' ');if(aw.length===1&&words.some(w=>w.length>=4&&dist(w,a)<=1))return p;if(aw.length===2){for(let i=0;i<words.length-1;i++)if(dist(words[i],aw[0])<=1&&dist(words[i+1],aw[1])<=1)return p}}}return null}
function project(q=''){return explicitProject(q)||window.TokoResponseEngine?.detectProject?.(q)||String(window.TokoLiveContext?.snapshot?.().project||'').toUpperCase()||null}
function get(p){return S[p]||null}
function summary(p){const x=get(p);if(!x)return null;const mem=window.TokoDecisionMemory?.list?.(p)||[];const accepted=mem.filter(d=>d.status==='accepted'||d.type==='approved').slice(0,3).map(d=>d.topic||d.text);const rejected=mem.filter(d=>d.status==='rejected'||d.type==='rejected').slice(0,3).map(d=>d.topic||d.text);const superseded=mem.filter(d=>d.status==='superseded').slice(0,2).map(d=>d.topic||d.text);return {project:p,...x,memory:{accepted,approved:accepted,rejected,superseded}}}
function answer(q){const p=project(q),x=summary(p);if(!x)return null;const s=String(q).toLowerCase();if(/\b(status|where are we|current state|state of)\b/.test(s))return `${p}: goal — ${x.goal}. Current — ${x.current}. Main pressure — ${x.problems.join(' / ')}. Next — ${x.next}.`;if(/\b(decided|decision|locked|already decided|preserve)\b/.test(s)){const live=x.memory.accepted.length?` Recent remembered decisions: ${x.memory.accepted.join(' / ')}.`:'';const changed=x.memory.superseded.length?` Superseded: ${x.memory.superseded.join(' / ')}.`:'';return `${p}: established direction — ${x.decisions.join(' / ')}.${live}${changed}`;}if(/\b(next|nxt|priority|work on|do now)\b/.test(s))return `${p}: ${x.next}. That follows the established direction: ${x.decisions[0]}.`;return null}
window.TokoProjectState={version:41,get,summary,answer,project,explicitProject};