// Toko Live v33: safer project routing + less canned voice.
import { PROJECT_EVIDENCE } from './evidence.js?v=1';
const PROJECTS={
'TINY HAWK':{aliases:['tiny hawk','tinyhawk','tiny h','hawk'],identity:['third-person free-roam skating','Skate-style load/flick controls','THPS vocabulary','a fat bird on a skateboard'],pillars:['board/body/camera coherence','right-stick control reliability','low chase-camera readability','movement feel before content','sparse Skate Story atmosphere'],risks:['camera hiding board response','controls feeling arbitrary','adding tricks before movement is trustworthy','visual detail obscuring the board','turning free-roam skating into a runner'],actions:['lock the low chase camera','make right-stick load/flick deterministic','show board response clearly','test movement before expanding tricks','add visual polish only after control feel is stable']},
'EERI':{aliases:['eeri','eerin peli','eeris game','crafted world game'],identity:['a young-player-first crafted platformer','an 80% platforming spine','big machines to ride and small hazards to dodge','a handmade world with generous retries'],pillars:['run/jump/climb readability','machine interaction clarity','young-player legibility','craft materials supporting gameplay','short readable levels'],risks:['craft detail hiding traversable edges','low-climb glitches','unclear machine affordances','punishing timing','background detail competing with the route'],actions:['fix traversal edge cases','make machine interactions obvious','protect platform contrast','add environmental life around readable routes','keep retries generous and immediate']},
'PIRITORI':{aliases:['piritori','piritori to eden','eden','kallio game'],identity:['Drug Wars economy plus tactical encounters','Kallio as both story and system','East of Eden character mapping','a miniature Helsinki diorama world'],pillars:['map/market/encounter loop','Era I completion','Kallio specificity','clean tactical slab readability','consequential information and combat'],risks:['generic Helsinki scenery','expanding before the economy loop works','diorama detail collapsing tactical silhouettes','combat becoming detached from the market','too many systems before one complete day works'],actions:['complete one buy-travel-encounter-sell-consequence loop','lock Era I before Era II expansion','push real Kallio identity','keep central tactical spaces clean','make information meaningfully avoid or alter conflict']},
'BETTERMENT':{aliases:['betterment','kindling','bonfire app'],identity:['a self-care loop wrapped in dark fantasy','five daily goals','a bonfire as progress language','a companion without guilt mechanics'],pillars:['mobile Today usability','five-goal clarity','warm progress feedback','functional navigation','absence without punishment'],risks:['streak anxiety','guilt for missed days','fantasy obscuring usability','companion becoming judgmental','visual atmosphere overpowering the daily task'],actions:['finish the Today loop','make five-goal progress instantly readable','tie fire response gently to completion','keep navigation functional','make companion reactions warm but non-punitive']},
'HYPER DAGGER':{aliases:['hyper dagger','hyperdagger','dagger','devil daggers clone'],identity:['a Devil Daggers look-and-feel target','oppressive threat readability','speed and dread over spectacle','a sparse hostile arena'],pillars:['enemy silhouette threat','weapon presence','pressure at speed','background restraint','mouth/skull animation'],risks:['decorative environment stealing attention','weak skull menace','weapon disappearing visually','chasing Hyper Demon spectacle','asset quantity replacing second-to-second feel'],actions:['strip background noise','strengthen skull silhouette and mouth motion','tune weapon contrast','judge every pass at gameplay speed','add only visuals that increase pressure or readability']},
'SUDS JACK':{aliases:['suds jack','sudsjack','suds','tempest game'],identity:['a nine-lane vector score attack','Bomb Jack through a Tempest perspective','a dive-focused arcade loop','topography expressed through the lane field'],pillars:['lower Tempest-like camera','ramp/topography depth','lane readability','horizon clarity','visible versioned changes'],risks:['camera staying too high','topography feeling flat','ramps hurting lane reading','detail masking the dive line','changes being too subtle to verify'],actions:['lower the camera unmistakably','shape side ramps with lane depth','test horizon and lanes together','keep the dive line obvious','version every playable visual pass']},
'FLASH PRINCE':{aliases:['flash prince','flashprince','flash','prince'],identity:['Flashback-style cinematic movement','rotoscope readability','two distinct character animation identities','shooting and shield layered onto authored traversal'],pillars:['coherent animation set per character','low-climb reliability','jump/ledge transitions','cinematic silhouette','combat that respects locomotion timing'],risks:['hybrid animation sets','low-climb state glitches','generic action-platformer combat','shooting interrupting movement language','detail before traversal is stable'],actions:['separate character animation sets fully','fix low-climb and jump transitions','add shooting states carefully','add shield states carefully','polish environments after movement is trustworthy']},
'TOKO DROP':{aliases:['toko drop','tokodrop','drop'],identity:['a slow readable top-down shooter','dash commitment plus right-stick aim','authored combat rounds','roguelite upgrades between rounds','gelatinous visual identity'],pillars:['round/dash/shoot loop','combat hierarchy','readable bullets and enemies','upgrade cadence','juicy but legible gel feedback'],risks:['generic twin-stick noise','too many effects hiding danger','upgrades becoming pure stat inflation','movement becoming too fast','content breadth before core feel'],actions:['finish the small round loop','make dash commitment readable','establish bullet/enemy/impact hierarchy','make upgrades alter decisions','expand content only after the core is fun']}
};
const GENERAL={
game:['games are strongest when the verb, feedback and consequence agree','a mechanic earns its place when it changes a decision','feel is information delivered through timing','scope is a design tool, not just a production constraint','clarity and mystery can coexist if the player understands what they can do','the second-to-second loop is where promises become real','a strong game teaches through consequence more than explanation','repetition is useful when each repeat sharpens a decision'],
art:['art direction is a filtering system: it decides what not to show','a strong style survives at gameplay scale, not only in a still image','specificity beats generic polish','visual hierarchy matters more than raw detail','the image should support the action unless the image itself is the action','materials become meaningful when they change attention or mood','silhouette is often more valuable than surface detail','a coherent limitation can create stronger identity than endless options'],
ai:['AI is useful when it increases iteration without erasing authorship','the seam can be visible; pretending the tool is magic makes the work less interesting','authorship means choosing, rejecting and editing, not merely generating','AI should reduce mechanical effort while leaving taste accountable','a tool becomes dangerous creatively when it replaces judgment rather than extending it','generated breadth is cheap; selection is where taste appears','AI can accelerate prototypes, but prototypes still need a point of view','automation is strongest when it removes repetition rather than responsibility'],
industry:['most market talk is downstream of whether people care about the work','trend-chasing works only when the team understands why the trend feels good','marketing cannot permanently repair a weak product promise','the interesting question is what behavior the audience is rewarding','production reality and creative identity have to meet somewhere concrete','scale is easy to count and distinctiveness is not','teams often add features when they cannot name what must remain sacred','technology changes quickly while taste changes slowly'],
nature:['nature is useful because it changes scale, pace and attention','going outside is not a streak or achievement','distance from the screen can reveal which problems were actually important','a walk is sometimes a better design tool than another hour of staring','balance is not anti-technology; it keeps technology from becoming the only frame','weather makes time physical again','natural systems are complex without asking for engagement metrics','changing surroundings often changes the question you thought you were solving'],
monetization:['monetization should not make the game worse in order to create the purchase','payment works best when it expresses support, status or expansion rather than relief from pain','price communicates what relationship you expect with the player','a business model is part of the design whether the team admits it or not','friction created only to sell relief damages trust','fair monetization can still be ambitious if the value exchange is legible'],
news:['facts first, opinion second','a headline matters when it changes a decision or understanding','sources and dates matter more than urgency styling','news becomes useful when connected back to games, art, tools or players','current events need a factual layer before interpretation','the interesting part is often the consequence, not the announcement']
};
const INTENTS={why:['why','reason','point','purpose','intent','matter','because'],fix:['fix','improve','change','better','solve','repair'],next:['next','priority','prioritize','first','roadmap','after','now'],problem:['problem','wrong','weak','issue','bug','bad','critique','broken'],explain:['explain','tell','describe','what is','what are','how does','design','core'],compare:['compare','versus','vs','difference','similar','better than'],agree:['agree','yes','right','correct','exactly'],disagree:['disagree','no','wrong','dont','do not','not really','actually'],more:['more','go on','continue','else','deeper','further','expand','elaborate'],look:['look','visual','art','style','feel','aesthetic','presentation'],test:['test','verify','check','qa','playtest','prove'],risk:['risk','danger','avoid','mistake','concern','worry'],news:['news','headline','latest','today','breaking','announcement']};
const AMBIGUOUS=new Set(['hawk','flash','prince','drop','dagger','eden','suds','tiny h']);
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim();
function lev(a,b){a=norm(a);b=norm(b);const m=a.length,n=b.length;if(!m)return n;if(!n)return m;const d=Array(n+1).fill(0).map((_,j)=>j);for(let i=1;i<=m;i++){let prev=d[0];d[0]=i;for(let j=1;j<=n;j++){const old=d[j];d[j]=Math.min(d[j]+1,d[j-1]+1,prev+(a[i-1]===b[j-1]?0:1));prev=old}}return d[n]}
function sim(a,b){a=norm(a);b=norm(b);if(!a||!b)return 0;if(a.includes(b)||b.includes(a))return 1;return 1-lev(a,b)/Math.max(a.length,b.length)}
function fuzzyHas(text,phrase,threshold=.78){const t=norm(text),p=norm(phrase);if(!t||!p)return false;if(t.includes(p))return true;const words=t.split(' '),pw=p.split(' ');if(pw.length===1)return p.length>=5&&words.some(w=>w.length>=4&&sim(w,p)>=threshold);for(let i=0;i<=words.length-pw.length;i++)if(sim(words.slice(i,i+pw.length).join(' '),p)>=threshold)return true;return false}
function detectProject(text){const q=norm(text);if(!q)return null;let best=null,bestScore=0;for(const [name,p] of Object.entries(PROJECTS)){for(let i=0;i<p.aliases.length;i++){const a=norm(p.aliases[i]);const canonical=i===0;if(canonical&&(q===a||q.includes(a)))return name;if(!AMBIGUOUS.has(a)&&q.includes(a))return name;if(AMBIGUOUS.has(a)){if(q.split(' ').includes(a)&&/game|project|build|level|controls|art|version|playable|camera|animation/.test(q)&&.76>bestScore){best=name;bestScore=.76}continue}if(a.length>=5){const s=Math.max(...q.split(' ').map(w=>sim(w,a)));if(s>=.84&&s>bestScore){best=name;bestScore=s}}}}return bestScore>=.84?best:null}
function detectIntent(text){let best=null,score=0;for(const [name,phrases] of Object.entries(INTENTS)){let s=0;for(const p of phrases)if(fuzzyHas(text,p,.78))s+=p.includes(' ')?2:1;if(s>score){score=s;best=name}}return best}
function detectTopic(text){const q=norm(text);if(/\b(visual|style|image|look|aesthetic|art)\b/.test(q))return'art';if(/\b(mechanic|player|gameplay|system|level|game)\b/.test(q))return'game';if(/\b(ai|model|generate|automation|artificial)\b/.test(q))return'ai';if(/\b(market|studio|publisher|sales|industry)\b/.test(q))return'industry';if(/money|monetiz|price|microtransaction|business model/.test(q))return'monetization';if(/\b(outside|forest|nature|walk|weather)\b/.test(q))return'nature';if(/\b(news|headline|latest|breaking|announcement)\b/.test(q))return'news';return null}
function context(){const c=window.TokoLiveContext?.snapshot?.()||{};const recentYou=[...document.querySelectorAll('.toko-chat .tc-log .tc-you')].slice(-6).map(n=>n.textContent||'').join(' ');return {project:(c.project||detectProject(recentYou)||'').toUpperCase()||null,lastYou:c.lastYou||'',lastToko:c.lastToko||'',recent:recentYou}}
function pick(a,avoid=''){const xs=a.filter(x=>!avoid||!avoid.includes(x));const src=xs.length?xs:a;return src[Math.floor(Math.random()*src.length)]}
function sentence(s){return s?`${s.charAt(0).toUpperCase()}${s.slice(1)}.`:''}
function pair(a,b){return Math.random()<.5?`${sentence(a)} ${sentence(b)}`:`${sentence(b)} ${sentence(a)}`}
function projectReply(p,i,last=''){const x=PROJECTS[p];if(!x)return null;const pillar=pick(x.pillars,last),risk=pick(x.risks,last),action=pick(x.actions,last),identity=pick(x.identity,last),pillar2=pick(x.pillars.filter(v=>v!==pillar),last),action2=pick(x.actions.filter(v=>v!==action),last),risk2=pick(x.risks.filter(v=>v!==risk),last);switch(i){case'why':return Math.random()<.5?`${sentence(identity)} The reason is ${pillar}. If that slips, ${risk} starts to take over.`:`Because ${pillar} is doing the real work. ${sentence(identity)} ${sentence(`I would protect that before anything that risks ${risk}`)}`;case'fix':return Math.random()<.5?`First: ${action}. Then ${action2}. If neither improves ${pillar}, they are the wrong fixes.`:`I would change one thing: ${action}. Watch ${pillar}; only then decide whether ${action2} is still needed.`;case'next':return Math.random()<.5?`${sentence(action)} That unlocks the next decision: ${action2}.`:`The next useful move is to ${action}. Not because it is large, but because it tells us whether ${pillar} is holding.`;case'problem':return Math.random()<.5?`${sentence(risk)} That is the part currently fighting ${pillar}. ${sentence(`The clean response is to ${action}`)}`:`The weak point is ${risk}. Fix that before chasing ${risk2}.`;case'explain':return `${sentence(identity)} In practice it lives or dies on ${pillar}, ${pillar2}, and ${pick(x.pillars.filter(v=>v!==pillar&&v!==pillar2),last)}.`;case'compare':return `Do not compare feature lists. Compare ${pillar}. ${sentence(identity)} The better direction is whichever makes ${action} more legible in play.`;case'disagree':return Math.random()<.5?`Fair. Then drop my assumption and test the consequence. If ${risk} is not actually hurting the build, move on to ${risk2}.`:`Then I should move, not defend the sentence. Show me where ${risk} is harmless and I will re-weight the problem toward ${risk2}.`;case'agree':return Math.random()<.5?`Good. Lock ${pillar} and spend the next pass on ${action}.`:`Then that decision is closed for now. Next pressure point: ${action}.`;case'more':return Math.random()<.5?`${sentence(pillar)} The tension is ${risk}; pushing one too hard can damage the other. ${sentence(`That makes ${action} a useful next experiment`)}`:`There is another layer: ${pillar2}. It matters because ${risk} can look like polish while quietly weakening the game.`;case'look':return `Protect ${pillar} first. Visually, ${pillar2} should read before decoration; ${risk} is the failure mode.`;case'test':return `Run it at gameplay speed. Push until ${risk} appears, then back off. The pass is working when ${action} reads without explanation.`;case'risk':return `${sentence(risk)} It matters because it attacks ${pillar}. The counter is simple: ${action}.`;default:return `${sentence(identity)} Right now ${pillar} is the useful pressure point. ${sentence(`I would ${action}`)}`}}
function generalReply(topic,i,last=''){const bank=GENERAL[topic]||GENERAL.game,a=pick(bank,last),b=pick(bank.filter(x=>x!==a),last),c=pick(bank.filter(x=>x!==a&&x!==b),last);if(i==='why')return pair(a,b);if(i==='problem'||i==='risk')return Math.random()<.5?`The trap is treating the label as the answer. ${sentence(a)} ${sentence(c)}`:`I would watch the consequence, not the category. ${sentence(c)} ${sentence(a)}`;if(i==='fix'||i==='next')return Math.random()<.5?`${sentence(a)} Make one concrete change, watch what moves, then decide whether ${b}.`:`Start small. ${sentence(b)} ${sentence(a)}`;if(i==='disagree')return `Then revise the position. I am more interested in what survives contact with the work than in protecting the previous answer. ${sentence(b)}`;if(i==='more')return `${sentence(a)} ${sentence(b)} ${sentence(c)}`;return pair(a,b)}
function fallback(raw,c){const q=norm(raw),topic=detectTopic(q);if(topic)return generalReply(topic,detectIntent(q),c.lastToko);if(c.project&&/\b(it|that|this|there|more|why|next|continue|go on|fix|problem)\b/.test(q))return projectReply(c.project,detectIntent(q)||'more',c.lastToko);if(/\b(who|toko|you)\b/.test(q))return 'Toko Midori. Artist, developer, audience, mask. I care about authored games, useful technology, strong taste, and knowing when to leave the screen.';if(/\b(hello|hi|hey|moi|yo)\b/.test(q))return 'I am here. Give me a game, a design problem, a piece of news, or something you think I am wrong about.';return 'I do not have enough signal to pretend I know what you mean yet. Give me the subject or the decision and I will take a position.'}
function answer(raw){const c=context(),direct=detectProject(raw),follow=/^(why|how|more|next|continue|go on|fix it|what else|and\?)\??$/i.test(raw.trim()),p=direct||(follow?c.project:null),i=detectIntent(raw)||(/\?$/.test(raw.trim())?'explain':'more');if(i==='news'&&window.TokoNewsConversation)return null;return p?projectReply(p,i,c.lastToko):fallback(raw,c)}
function append(raw,reply){const log=document.querySelector('.toko-chat .tc-log');if(!log)return;const you=document.createElement('p');you.className='tc-you';you.textContent=raw.toUpperCase();const me=document.createElement('p');me.className='tc-me';me.textContent=reply;log.append(you,me);log.scrollTop=log.scrollHeight}
function boot(){const input=document.querySelector('.toko-chat .tc-say-row input');if(!input)return requestAnimationFrame(boot);input.addEventListener('keydown',e=>{if(e.key!=='Enter')return;const raw=input.value.trim();if(!raw)return;const reply=answer(raw);if(!reply)return;e.preventDefault();e.stopImmediatePropagation();input.value='';append(raw,reply);dispatchEvent(new CustomEvent('toko:deep-answer',{detail:{question:raw,reply}}))},true)}boot();
window.TokoResponseEngine={answer,detectProject,detectIntent,detectTopic,fuzzyHas,sim,projects:PROJECTS,evidence:PROJECT_EVIDENCE};