// Toko Live v21: broad fuzzy/contextual response engine.
// Compositional project/topic banks produce thousands of useful variants.
import { PROJECT_EVIDENCE } from './evidence.js?v=1';
const PROJECTS={
'TINY HAWK':{aliases:['tiny hawk','tinyhawk','tiny h','hawk'],identity:['third-person free-roam skating','Skate-style load/flick controls','THPS vocabulary','a fat bird on a skateboard'],pillars:['board/body/camera coherence','right-stick control reliability','low chase-camera readability','movement feel before content','sparse Skate Story atmosphere'],risks:['camera hiding board response','controls feeling arbitrary','adding tricks before movement is trustworthy','visual detail obscuring the board','turning free-roam skating into a runner'],actions:['lock the low chase camera','make right-stick load/flick deterministic','show board response clearly','test movement before expanding tricks','add visual polish only after control feel is stable']},
'EERI':{aliases:['eeri','eerin peli','eeris game','crafted world game'],identity:['a young-player-first crafted platformer','an 80% platforming spine','big machines to ride and small hazards to dodge','a handmade world with generous retries'],pillars:['run/jump/climb readability','machine interaction clarity','young-player legibility','craft materials supporting gameplay','short readable levels'],risks:['craft detail hiding traversable edges','low-climb glitches','unclear machine affordances','punishing timing','background detail competing with the route'],actions:['fix traversal edge cases','make machine interactions obvious','protect platform contrast','add environmental life around readable routes','keep retries generous and immediate']},
'PIRITORI':{aliases:['piritori','piritori to eden','eden','kallio game'],identity:['Drug Wars economy plus tactical encounters','Kallio as both story and system','East of Eden character mapping','a miniature Helsinki diorama world'],pillars:['map/market/encounter loop','Era I completion','Kallio specificity','clean tactical slab readability','consequential information and combat'],risks:['generic Helsinki scenery','expanding before the economy loop works','diorama detail collapsing tactical silhouettes','combat becoming detached from the market','too many systems before one complete day works'],actions:['complete one buy-travel-encounter-sell-consequence loop','lock Era I before Era II expansion','push real Kallio identity','keep central tactical spaces clean','make information meaningfully avoid or alter conflict']},
'BETTERMENT':{aliases:['betterment','kindling','bonfire app'],identity:['a self-care loop wrapped in dark fantasy','five daily goals','a bonfire as progress language','a companion without guilt mechanics'],pillars:['mobile Today usability','five-goal clarity','warm progress feedback','functional navigation','absence without punishment'],risks:['streak anxiety','guilt for missed days','fantasy obscuring usability','companion becoming judgmental','visual atmosphere overpowering the daily task'],actions:['finish the Today loop','make five-goal progress instantly readable','tie fire response gently to completion','keep navigation functional','make companion reactions warm but non-punitive']},
'HYPER DAGGER':{aliases:['hyper dagger','hyperdagger','dagger','devil daggers clone'],identity:['a Devil Daggers look-and-feel target','oppressive threat readability','speed and dread over spectacle','a sparse hostile arena'],pillars:['enemy silhouette threat','weapon presence','pressure at speed','background restraint','mouth/skull animation'],risks:['decorative environment stealing attention','weak skull menace','weapon disappearing visually','chasing Hyper Demon spectacle','asset quantity replacing second-to-second feel'],actions:['strip background noise','strengthen skull silhouette and mouth motion','tune weapon contrast','judge every pass at gameplay speed','add only visuals that increase pressure or readability']},
'SUDS JACK':{aliases:['suds jack','sudsjack','suds','tempest game'],identity:['a nine-lane vector score attack','Bomb Jack through a Tempest perspective','a dive-focused arcade loop','topography expressed through the lane field'],pillars:['lower Tempest-like camera','ramp/topography depth','lane readability','horizon clarity','visible versioned changes'],risks:['camera staying too high','topography feeling flat','ramps hurting lane reading','detail masking the dive line','changes being too subtle to verify'],actions:['lower the camera unmistakably','shape side ramps with lane depth','test horizon and lanes together','keep the dive line obvious','version every playable visual pass']},
'FLASH PRINCE':{aliases:['flash prince','flashprince','flash','prince'],identity:['Flashback-style cinematic movement','rotoscope readability','two distinct character animation identities','shooting and shield layered onto authored traversal'],pillars:['coherent animation set per character','low-climb reliability','jump/ledge transitions','cinematic silhouette','combat that respects locomotion timing'],risks:['hybrid animation sets','low-climb state glitches','generic action-platformer combat','shooting interrupting movement language','detail before traversal is stable'],actions:['separate character animation sets fully','fix low-climb and jump transitions','add shooting states carefully','add shield states carefully','polish environments after movement is trustworthy']},
'TOKO DROP':{aliases:['toko drop','tokodrop','drop'],identity:['a slow readable top-down shooter','dash commitment plus right-stick aim','authored combat rounds','roguelite upgrades between rounds','gelatinous visual identity'],pillars:['round/dash/shoot loop','combat hierarchy','readable bullets and enemies','upgrade cadence','juicy but legible gel feedback'],risks:['generic twin-stick noise','too many effects hiding danger','upgrades becoming pure stat inflation','movement becoming too fast','content breadth before core feel'],actions:['finish the small round loop','make dash commitment readable','establish bullet/enemy/impact hierarchy','make upgrades alter decisions','expand content only after the core is fun']}
};
const GENERAL={
game:['games are strongest when the verb, feedback and consequence agree','a mechanic earns its place when it changes a decision','feel is information delivered through timing','scope is a design tool, not just a production constraint','clarity and mystery can coexist if the player understands what they can do','the second-to-second loop is where promises become real','a strong game teaches through consequence more than explanation','repetition is useful when each repeat sharpens a decision'],
art:['art direction is a filtering system: it decides what not to show','a strong style survives at gameplay scale, not only in a still image','specificity beats generic polish','visual hierarchy matters more than raw detail','the image should support the action unless the image itself is the action','materials become meaningful when they change attention or mood','silhouette is often more valuable than surface detail','a coherent limitation can create stronger identity than endless options'],
ai:['AI is useful when it increases iteration without erasing authorship','the seam can be visible; pretending the tool is magic makes the work less interesting','authorship means choosing, rejecting and editing, not merely generating','AI should reduce mechanical effort while leaving taste accountable','a tool becomes dangerous creatively when it replaces judgment rather than extending it','generated breadth is cheap; selection is where taste appears','AI can accelerate prototypes, but prototypes still need a point of view','automation is strongest when it removes repetition rather than responsibility'],
industry:['most market talk is downstream of whether people care about the work','trend-chasing works only when the team understands why the trend feels good','marketing cannot permanently repair a weak product promise','the interesting question is what behavior the audience is rewarding','production reality and creative identity have to meet somewhere concrete','scale is easy to count and distinctiveness is not','teams often add features when they cannot name what must remain sacred','technology changes quickly while taste changes slowly'],
nature:['nature is useful because it changes scale, pace and attention','going outside is not a streak or achievement','distance from the screen can reveal which problems were actually important','a walk is sometimes a better design tool than another hour of staring','balance is not anti-technology; it keeps technology from becoming the only frame','weather makes time physical again','natural systems are complex without asking for engagement metrics','changing surroundings often changes the question you thought you were solving'],
monetization:['monetization should not make the game worse in order to create the purchase','payment works best when it expresses support, status or expansion rather than relief from pain','price communicates what relationship you expect with the player','a business model is part of the design whether the team admits it or not','friction created only to sell relief damages trust','fair monetization can still be ambitious if the value exchange is legible'],
news:['facts first, opinion second','a headline matters when it changes a decision or understanding','sources and dates matter more than urgency styling','news becomes useful when connected back to games, art, tools or players','current events need a factual layer before interpretation','the interesting part is often the consequence, not the announcement']
};
const INTENTS={why:['why','reason','point','purpose','intent','matter','because'],fix:['fix','improve','change','better','solve','repair'],next:['next','priority','prioritize','first','roadmap','after','now'],problem:['problem','wrong','weak','issue','bug','bad','critique','broken'],explain:['explain','tell','describe','what is','what are','how does','design','core'],compare:['compare','versus','vs','difference','similar','better than'],agree:['agree','yes','right','correct','exactly'],disagree:['disagree','no','wrong','dont','do not','not really','actually'],more:['more','go on','continue','else','deeper','further','expand','elaborate'],look:['look','visual','art','style','feel','aesthetic','presentation'],test:['test','verify','check','qa','playtest','prove'],risk:['risk','danger','avoid','mistake','concern','worry'],news:['news','headline','latest','today','industry','current']};
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim();
function lev(a,b){a=norm(a);b=norm(b);const m=a.length,n=b.length;if(!m)return n;if(!n)return m;const d=Array(n+1).fill(0).map((_,j)=>j);for(let i=1;i<=m;i++){let prev=d[0];d[0]=i;for(let j=1;j<=n;j++){const old=d[j];d[j]=Math.min(d[j]+1,d[j-1]+1,prev+(a[i-1]===b[j-1]?0:1));prev=old}}return d[n]}
function sim(a,b){a=norm(a);b=norm(b);if(!a||!b)return 0;if(a.includes(b)||b.includes(a))return 1;return 1-lev(a,b)/Math.max(a.length,b.length)}
function fuzzyHas(text,phrase,threshold=.68){const t=norm(text),p=norm(phrase);if(t.includes(p))return true;const words=t.split(' '),pw=p.split(' ');if(pw.length===1)return words.some(w=>sim(w,p)>=threshold);for(let i=0;i<=words.length-pw.length;i++)if(sim(words.slice(i,i+pw.length).join(' '),p)>=threshold)return true;return sim(t,p)>=threshold}
function detectProject(text){let best=null,score=.52;for(const [name,p] of Object.entries(PROJECTS)){for(const a of p.aliases){if(fuzzyHas(text,a,.66))return name;for(const w of norm(text).split(' ')){const s=sim(w,a);if(s>score){score=s;best=name}}}}return best}
function detectIntent(text){let best=null,score=0;for(const [name,phrases] of Object.entries(INTENTS)){let s=0;for(const p of phrases)if(fuzzyHas(text,p,.66))s+=p.includes(' ')?2:1;if(s>score){score=s;best=name}}return best}
function detectTopic(text){const q=norm(text);if(/visual|style|image|look|aesthetic|art/.test(q))return'art';if(/mechanic|player|gameplay|system|level|game/.test(q))return'game';if(/ai|model|generate|automation|artificial/.test(q))return'ai';if(/market|studio|publisher|sales|industry/.test(q))return'industry';if(/money|monetiz|price|microtransaction|business model/.test(q))return'monetization';if(/outside|forest|nature|walk|weather/.test(q))return'nature';if(/news|headline|latest|today|current/.test(q))return'news';return null}
function context(){const c=window.TokoLiveContext?.snapshot?.()||{};const recent=[...document.querySelectorAll('.toko-chat .tc-log .tc-you,.toko-chat .tc-log .tc-me')].slice(-14).map(n=>n.textContent||'').join(' ');return {project:(c.project||detectProject(recent)||'').toUpperCase()||null,lastYou:c.lastYou||'',lastToko:c.lastToko||'',recent}}
function pick(a,avoid=''){const xs=a.filter(x=>!avoid||!avoid.includes(x));const src=xs.length?xs:a;return src[Math.floor(Math.random()*src.length)]}
function sentence(s){return s?`${s.charAt(0).toUpperCase()}${s.slice(1)}.`:''}
function projectReply(p,i,last=''){const x=PROJECTS[p];if(!x)return null;const pillar=pick(x.pillars,last),risk=pick(x.risks,last),action=pick(x.actions,last),identity=pick(x.identity,last),pillar2=pick(x.pillars.filter(v=>v!==pillar),last),action2=pick(x.actions.filter(v=>v!==action),last);switch(i){case'why':return `${sentence(identity)} ${sentence(pillar)} That is why ${risk} is the thing I would resist.`;case'fix':return `${sentence(action)} Then ${action2}. I would measure the change against ${pillar}, not against how much new material was added.`;case'next':return `${sentence(action)} After that: ${action2}. The gate is ${pillar}.`;case'problem':return `The biggest risk is ${risk}. It weakens ${pillar}. I would answer it by ${action}.`;case'explain':return `${sentence(identity)} The design hangs on ${pillar}, ${pillar2}, and ${pick(x.pillars.filter(v=>v!==pillar&&v!==pillar2),last)}.`;case'compare':return `I would compare it through ${pillar}, not feature count. ${sentence(identity)} Its own standard is whether ${action} improves the second-to-second experience.`;case'disagree':return `Good. Then I would not defend the wording; I would test the consequence. If ${risk} is not hurting the experience, we should drop that concern and look at ${pick(x.risks.filter(v=>v!==risk),last)} instead.`;case'agree':return `Then I would treat ${pillar} as locked direction and move to ${action}. Agreement should narrow the next decision, not end the discussion.`;case'more':return `${sentence(pillar)} A second layer is ${pillar2}. The interesting tension is that improving one can worsen ${risk}, so the next pass should test both together.`;case'look':return `${sentence(pillar)} Visually I would protect ${pillar2}. The failure mode is ${risk}.`;case'test':return `Test ${pillar} at gameplay speed. Then deliberately push toward ${risk} and see where readability breaks. The pass succeeds only if ${action} is obvious in play.`;case'risk':return `The risk I would watch is ${risk}. It matters because of ${pillar}. The countermeasure is to ${action}.`;default:return `${sentence(identity)} Right now I would focus on ${pillar}. The risk is ${risk}; the useful next move is to ${action}.`}}
function generalReply(topic,i,last=''){const bank=GENERAL[topic]||GENERAL.game,a=pick(bank,last),b=pick(bank.filter(x=>x!==a),last),c=pick(bank.filter(x=>x!==a&&x!==b),last);if(i==='why')return `${sentence(a)} ${sentence(b)}`;if(i==='problem'||i==='risk')return `The failure mode is treating the label as the answer. ${sentence(a)} ${sentence(c)}`;if(i==='fix'||i==='next')return `${sentence(a)} So I would make one concrete change, observe what it changes, and only then add another layer. ${sentence(b)}`;if(i==='disagree')return `That is useful friction. I would rather revise the position than protect it. ${sentence(b)}`;if(i==='more')return `${sentence(a)} ${sentence(b)} ${sentence(c)}`;return `${sentence(a)} ${sentence(b)}`}
function fallback(raw,c){const q=norm(raw),topic=detectTopic(q);if(topic)return generalReply(topic,detectIntent(q),c.lastToko);if(c.project)return projectReply(c.project,detectIntent(q)||'more',c.lastToko);if(/who|toko|you/.test(q))return 'Toko Midori. Artist, developer, audience, mask. I care about games as authored work, useful technology, and knowing when to leave the screen.';if(/hello|hi|hey|moi|yo/.test(q))return 'I am here. Give me a game, a design problem, a piece of news, or something you think I am wrong about.';return 'I can still pull on that. Ask for the reason, the problem, the next action, what I would change, or how it connects to what we were discussing.'}
function answer(raw){const c=context(),p=detectProject(raw)||c.project,i=detectIntent(raw)||(/\?$/.test(raw.trim())?'explain':'more');if(i==='news'&&window.TokoNewsConversation)return null;return p?projectReply(p,i,c.lastToko):fallback(raw,c)}
function append(raw,reply){const log=document.querySelector('.toko-chat .tc-log');if(!log)return;const you=document.createElement('p');you.className='tc-you';you.textContent=raw.toUpperCase();const me=document.createElement('p');me.className='tc-me';me.textContent=reply;log.append(you,me);log.scrollTop=log.scrollHeight}
function boot(){const input=document.querySelector('.toko-chat .tc-say-row input');if(!input)return requestAnimationFrame(boot);input.addEventListener('keydown',e=>{if(e.key!=='Enter')return;const raw=input.value.trim();if(!raw)return;const reply=answer(raw);if(!reply)return;e.preventDefault();e.stopImmediatePropagation();input.value='';append(raw,reply);dispatchEvent(new CustomEvent('toko:deep-answer',{detail:{question:raw,reply}}))},true)}boot();
window.TokoResponseEngine={answer,detectProject,detectIntent,detectTopic,fuzzyHas,sim,projects:PROJECTS};
