// Toko Live v21 — typo-tolerant conversational response engine.
// Structured knowledge + compositional replies gives thousands of useful variants
// without turning the UI back into a giant fixed dialogue menu.
const PROJECTS={
'TINY HAWK':{aliases:['tiny hawk','tinyhawk','hawk'],core:'third-person free-roam skating: THPS vocabulary with Skate-like load/flick control and a low chase camera',problem:'control feel and camera readability still matter more than content breadth',next:'lock right-stick load/flick reliability and the low chase-camera read before decorative expansion',why:'the board, body and camera must communicate one physical action',look:'sparse Skate Story atmosphere with strong board/body separation and readable motion',risk:'adding tricks, scenery or progression before the board response feels dependable',test:'play at speed and judge whether every stick motion produces an obvious board/body consequence'},
'EERI':{aliases:['eeri','eeris game'],core:'a crafted-world platform adventure built first for a young player: run, jump, climb, stomp and interact with machines',problem:'traversal and interaction readability can break before the craft art does',next:'fix low climbs, jump/climb transitions and machine affordances, then add environmental life',why:'the handmade world only works if the route remains easier to read than the decoration',look:'80% Crafted World warmth with restrained Tropical Freeze-style staging and clear foreground gameplay',risk:'letting charming materials obscure platforms, hazards or machine interactions',test:'watch whether a child can identify the next safe action without explanation'},
'PIRITORI':{aliases:['piritori','piritori to eden','eden'],core:'an early-2000s Kallio crime/economy narrative: Drug Wars economy, route planning and consequential turn-based encounters',problem:'the world can become broad before the Era I buy-travel-encounter-sell loop is fully convincing',next:'finish one complete Era I economic and encounter loop before widening the map or content set',why:'the city must function as both authored story and understandable system',look:'grounded miniature Helsinki dioramas with recognizable Kallio identity and clean tactical slabs',risk:'generic Nordic scenery, excessive perimeter detail, or narrative scope outrunning the playable spine',test:'start at Piritori and see whether purchase-to-first-profit is clear, tense and consequential'},
'BETTERMENT':{aliases:['betterment','kindling'],core:'a gentle self-care loop expressed through a dark-fantasy bonfire, companion and five daily goals',problem:'reward language can accidentally become guilt or streak pressure',next:'make Today, five-goal progress, fire response and navigation fully functional before companion polish',why:'the fantasy should make care meaningful without making absence a failure state',look:'warm layered 2D bonfire safety inside a darker surrounding world',risk:'turning missed days into punishment, shame or mechanical debt',test:'leave for several days, return, and check whether the experience still feels welcoming rather than corrective'},
'HYPER DAGGER':{aliases:['hyper dagger','hyperdagger','dagger'],core:'a sparse high-pressure first-person survival shooter aiming for Devil Daggers-like immediacy and dread',problem:'background density and weak enemy presentation can dilute threat readability',next:'strengthen skull threat, mouth motion, weapon presence and contrast while keeping the environment restrained',why:'pressure comes from instantly readable danger, not asset quantity',look:'oppressive silhouettes, hard contrast, sparse space and a weapon that feels physically present',risk:'chasing spectacle or environmental detail that steals attention from enemies',test:'play at full speed and ask whether every enemy silhouette and threat direction reads instantly'},
'SUDS JACK':{aliases:['suds jack','sudsjack','suds'],core:'a nine-lane vector score attack shaped by Bomb Jack and Tempest, with diving and lane movement as the spatial game',problem:'camera and topography can look changed in code without feeling changed to the player',next:'make the camera visibly lower and shape side ramps/topography around lane readability',why:'perspective is the game board here; it changes how danger and depth are perceived second to second',look:'clean vector space, strong horizon, deep lane geometry and unmistakable Tempest-like perspective',risk:'adding surface variation without actually changing the spatial read',test:'compare old and new builds side by side; the camera/topography change should be obvious in one second'},
'FLASH PRINCE':{aliases:['flash prince','flashprince','prince'],core:'a cinematic rotoscope action platformer built around deliberate Flashback-like movement, now adding shooting and shield systems',problem:'mixed animation sets and low-climb/jump glitches break the authored movement illusion',next:'separate each character animation set completely, fix low traversal transitions, then add shooting and shield states',why:'cinematic movement is the identity, so every state transition has to look intentional',look:'clean silhouettes, measured rotoscope timing and richer environments without losing movement clarity',risk:'bolting action mechanics onto unstable locomotion or mixing old/new animation languages',test:'repeat low climbs, ledges and jumps until no state visibly snaps or borrows the wrong character style'},
'TOKO DROP':{aliases:['toko drop','tokodrop','drop'],core:'a slower readable top-down shooter with dash commitment, right-stick aim/shoot and roguelite upgrades after authored rounds',problem:'effects and upgrade breadth can overwhelm the simple combat hierarchy',next:'finish the round-dash-shoot loop and enemy/bullet readability before expanding upgrades',why:'the player should make deliberate spatial decisions rather than swim through generic twin-stick noise',look:'juicy gelatin impact and shape language with very clear danger hierarchy',risk:'too much visual noise, too-fast movement or upgrades that add effects without changing decisions',test:'use a small enemy set and verify that movement, dash timing, bullets and impacts remain readable under pressure'}
};
const GENERAL={
art:['Games become art when mechanics, form and point of view agree. I care less about whether a game looks expensive than whether it knows what it is saying through play.','A visual style is useful when it changes what the player notices. Decoration that does not affect attention, mood or understanding is usually just cost.','I like games that leave a residue after you stop playing: an image, a rhythm, a decision, a place. That is a better target than content volume.'],
ai:['AI is useful when it increases iteration without erasing authorship. The seam can stay visible; pretending the tool made the decisions is the boring part.','The interesting question is not whether AI touched the work. It is who selected, rejected, shaped and took responsibility for the result.','Use AI for breadth, comparison and fast material generation; keep taste, constraints and final judgment authored.'],
design:['Start from the second-to-second verb. If that is weak, meta systems only make a larger weak game.','A design decision should change player behavior, perception or emotion. If it changes none of those, it is probably implementation detail.','I prefer one strong rule with consequences over five systems that merely coexist.'],
monetization:['Monetization should not make the game worse in order to create the purchase. If the business model needs frustration as fuel, it is designing against the player.','I like models where payment expresses support, status or expansion rather than relief from pain deliberately inserted by the designer.','Price is part of the artwork too: it tells the player what kind of relationship you expect to have with them.'],
industry:['The industry overvalues scale because scale is easy to count. Distinctiveness, trust and replayable craft are harder to put in a spreadsheet.','A lot of game strategy problems are actually identity problems: teams add features because they cannot say what must remain sacred.','Technology changes quickly; taste changes slowly. I would build around durable player feelings and use new tools opportunistically.'],
nature:['Go outside when the screen has become the only scale you can feel. Not as a streak, not as proof, just to reset proportion.','Nature is useful to me because it is full of systems that are not asking for engagement metrics. It reminds you that complexity can exist without UI.','A walk is sometimes a better design tool than another hour of references. You return noticing rhythm, distance, weather and material again.'],
news:['For news, I want the factual layer first: what happened, source, date and why it matters. Opinion comes after that, clearly marked as opinion.','News is useful when it changes a decision. Otherwise it is often just weather for the mind. I would connect a story back to what it means for games, art, tools or players.']
};
const INTENTS={
next:['next','after','priority','prioritize','work on','do now','what should','where next'],
why:['why','reason','point','intent','purpose','because'],
fix:['fix','improve','change','wrong','problem','issue','weak','bad','broken','glitch'],
look:['look','visual','art','style','feel','aesthetic','presentation'],
test:['test','verify','check','qa','playtest','prove'],
risk:['risk','danger','avoid','mistake','concern','worry'],
core:['design','gameplay','core','idea','concept','what is','tell me about','explain'],
opinion:['think','opinion','take','feel about','view'],
more:['more','continue','go on','deeper','else','expand','elaborate']};
const TOPICS={art:['art','artist','aesthetic','creative','beauty'],ai:['ai','artificial intelligence','machine learning','generative'],design:['design','game design','mechanic','system','gameplay'],monetization:['money','monetization','monetisation','price','business model','microtransaction'],industry:['industry','games industry','studio','publisher','market'],nature:['nature','outside','forest','walk'],news:['news','headline','current','today','latest']};
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]+/g,' ').replace(/\s+/g,' ').trim();
function dist(a,b){const m=a.length,n=b.length,d=Array.from({length:m+1},()=>Array(n+1));for(let i=0;i<=m;i++)d[i][0]=i;for(let j=0;j<=n;j++)d[0][j]=j;for(let i=1;i<=m;i++)for(let j=1;j<=n;j++)d[i][j]=Math.min(d[i-1][j]+1,d[i][j-1]+1,d[i-1][j-1]+(a[i-1]===b[j-1]?0:1));return d[m][n]}
function sim(a,b){a=norm(a);b=norm(b);if(!a||!b)return 0;if(a.includes(b)||b.includes(a))return 1;return 1-dist(a,b)/Math.max(a.length,b.length)}
function fuzzyHas(text,phrase){const t=norm(text),p=norm(phrase);if(t.includes(p))return true;const tw=t.split(' '),pw=p.split(' ');if(pw.length===1)return tw.some(w=>w.length>2&&sim(w,p)>=0.72);if(tw.length<pw.length)return sim(t,p)>=0.7;for(let i=0;i<=tw.length-pw.length;i++)if(sim(tw.slice(i,i+pw.length).join(' '),p)>=0.72)return true;return false}
function detectProject(text){let best=null,score=.66;for(const [name,p] of Object.entries(PROJECTS))for(const a of p.aliases){if(fuzzyHas(text,a))return name;const s=sim(norm(text).split(' ').slice(-3).join(' '),a);if(s>score){score=s;best=name}}return best||window.TokoLiveContext?.snapshot?.().project?.toUpperCase()||null}
function detectIntent(text){for(const [intent,keys] of Object.entries(INTENTS))if(keys.some(k=>fuzzyHas(text,k)))return intent;return null}
function detectTopic(text){for(const [topic,keys] of Object.entries(TOPICS))if(keys.some(k=>fuzzyHas(text,k)))return topic;return null}
const pick=a=>a[Math.floor(Math.random()*a.length)];
const LEADS=['I would frame it this way: ','The useful part is this: ','My read: ','The thing I would protect is this: ','If we reduce it to the decision: '];
const LINKS=[' That matters because ',' The consequence is that ',' In practice, ',' So I would judge it by this: '];
function projectReply(p,intent){const x=PROJECTS[p];if(!x)return null;switch(intent){case'next':return pick(LEADS)+x.next+'. '+pick(LINKS)+x.test+'.';case'why':return pick(LEADS)+x.why+'. '+x.core+'.';case'fix':return pick(LEADS)+x.problem+'. I would '+x.next+'.';case'look':return pick(LEADS)+x.look+'. Avoid '+x.risk+'.';case'test':return pick(LEADS)+x.test+'. The failure mode I would watch for is '+x.risk+'.';case'risk':return pick(LEADS)+x.risk+'. The countermeasure is to '+x.next+'.';case'more':return x.core+'. '+x.why+'. Right now '+x.problem+', so I would '+x.next+'.';case'opinion':return pick(LEADS)+x.core+'. I like the direction when '+x.why+', but '+x.problem+'.';default:return x.core+'. Right now '+x.problem+'. Next I would '+x.next+'.'}}
function generalReply(topic,intent){const bank=GENERAL[topic]||GENERAL.design;let r=pick(bank);if(intent==='more')r+=' '+pick(bank.filter(x=>x!==r)||bank);return r}
function fallback(){const c=window.TokoLiveContext?.snapshot?.()||{},p=c.project?.toUpperCase();if(p&&PROJECTS[p])return projectReply(p,'more');const last=c.lastToko||'';if(last)return `I can keep going from that. The useful question is what it changes in the player's experience, what tradeoff it creates, and what we should do differently because of it.`;return pick(GENERAL.design)}
function answer(raw){const q=norm(raw);if(!q)return null;const p=detectProject(q),intent=detectIntent(q),topic=detectTopic(q);if(p)return projectReply(p,intent||'core');if(topic)return generalReply(topic,intent);if(intent==='more'||intent==='why'||intent==='opinion'||intent==='next'||intent==='fix')return fallback();return null}
function append(raw,reply){const log=document.querySelector('.toko-chat .tc-log');if(!log)return;const you=document.createElement('p');you.className='tc-you';you.textContent=raw.toUpperCase();const me=document.createElement('p');me.className='tc-me';me.textContent=reply;log.append(you,me);log.scrollTop=log.scrollHeight}
function boot(){const input=document.querySelector('.toko-chat .tc-say-row input');if(!input)return requestAnimationFrame(boot);input.addEventListener('keydown',e=>{if(e.key!=='Enter')return;const raw=input.value.trim(),reply=answer(raw);if(!reply)return;e.preventDefault();e.stopImmediatePropagation();input.value='';append(raw,reply);dispatchEvent(new CustomEvent('toko:deep-answer',{detail:{question:raw,reply}}))},true)}boot();
window.TokoResponseEngine={answer,detectProject,detectIntent,detectTopic,fuzzyHas,sim};
