// Toko Move v2.11 — ten courier jobs played by catching existing HSL services.
export const DELIVERY_TARGET=10;
export const CARGO={documents:{icon:'DOC',rule:'Flexible routing',modes:null},'hot food':{icon:'HOT',rule:'Freshness falls fast',modes:null,freshness:.60},parts:{icon:'PRT',rule:'No special restriction',modes:null},fragile:{icon:'FRG',rule:'Tram only — avoid transfers',modes:['tram'],fragile:true},equipment:{icon:'HVY',rule:'Transit only; no walking shortcut',modes:['tram','metro'],heavy:true},express:{icon:'EXP',rule:'Priority courier — metro or tram',modes:['metro','tram'],express:true},'fresh food':{icon:'FRESH',rule:'Freshness bonus for speed',modes:null,freshness:.70},'market goods':{icon:'MRKT',rule:'Tram network only',modes:['tram'],heavy:true}};
export const JOBS=[
 {stops:['lasipalatsi','rautatientori'],label:'Press proofs to Central',cargo:'documents',limit:125,value:100,lesson:'Read the centre. Catch an existing service.'},
 {stops:['rautatientori','hietalahti'],label:'Hot lunch to Hietalahti',cargo:'hot food',limit:155,value:140,lesson:'Choose a useful tram before the food cools.'},
 {stops:['hietalahti','lansiterminaali'],label:'Dock parts to West Harbour',cargo:'parts',limit:155,value:130,lesson:'Follow the existing tram corridor west.'},
 {stops:['lansiterminaali','kamppi','toolontori'],label:'Fragile parcel via Kamppi to Töölö',cargo:'fragile',limit:250,value:190,lesson:'First deliberate change of tram.'},
 {stops:['toolontori','ooppera','meilahti'],label:'Medical equipment via Opera to Meilahti',cargo:'equipment',limit:220,value:210,lesson:'Read overlapping HSL services.'},
 {stops:['meilahti','pasila','messukeskus'],label:'Expo courier through Pasila',cargo:'express',limit:225,value:230,rush:true,event:{name:'RUSH PERIOD',text:'Central services are crowded; catch the cleanest northbound connection.'}},
 {stops:['messukeskus','kapyla','arabia'],label:'Fresh food across the north-east',cargo:'fresh food',limit:260,value:220,event:{name:'TRAM DELAY',text:'One easy corridor is slow today — a transfer may beat waiting.',penalty:18}},
 {stops:['arabia','sornainen','kalasatama'],label:'Express run down the eastern spine',cargo:'express',limit:205,value:200,event:{name:'METRO WINDOW',text:'Metro is the fast option once you reach it.'}},
 {stops:['kalasatama','senaatintori','kauppatori','olympiaterminaali'],label:'Harbour manifest to the Olympia terminal',cargo:'documents',limit:320,value:270,event:{name:'HARBOUR EVENT',text:'South harbour is busy. Multiple stops, one clock.'}},
 {stops:['olympiaterminaali','eira','kauppatori','katajanokka','rautatientori'],label:'Final market circuit across Helsinki',cargo:'market goods',limit:360,value:320,event:{name:'FINAL CIRCUIT',text:'Tram-only cargo. Catch the right services and change cleanly.'}}
];
const sameNodes=(a,b)=>a.length===b.length&&a.every((n,i)=>n===b[i]);
export class DeliveryChallenge{
 constructor(flow,say){this.flow=flow;this.say=say;this.index=0;this.leg=0;this.active=null;this.activeTrip=null;this.selectedPlan=null;this.waitingForCatch=false;this.seen=new Set;this.startedAt=0;this.score=0;this.late=0;this.rushTriggered=false;this.bonuses=0;}
 cargoRule(){return CARGO[this.active?.cargo]||CARGO.documents;}
 start(){this.launchJob();}
 launchJob(){if(this.index>=JOBS.length)return false;this.active=JOBS[this.index];this.leg=0;this.startedAt=this.flow.clock.tick;if(this.active.rush&&!this.rushTriggered){this.rushTriggered=true;this.makeRushHour();}if(this.active.event)this.say(`${this.active.event.name} · ${this.active.event.text}`);this.launchLeg();const c=this.cargoRule();this.say(`${this.index+1}/${DELIVERY_TARGET} · ${c.icon} · ${this.routeLabel()} · ${c.rule}`);return true;}
 launchLeg(){this.activeTrip=null;this.selectedPlan=null;this.waitingForCatch=true;const from=this.currentFrom(),to=this.currentTo();this.say(`WAITING · ${this.name(from)} → ${this.name(to)} · choose a tram or metro to catch.`);}
 runtimeRoute(line){return this.flow.routes.list.find(r=>r.fixed&&r.mode===line.mode&&r.label===line.label&&sameNodes(r.nodes,line.nodes));}
 catchChoice(choice){if(!this.active||!this.waitingForCatch||this.activeTrip||!choice?.legs?.length)return{error:'not waiting for a service'};const c=this.cargoRule();if(c.modes&&choice.legs.some(l=>!c.modes.includes(l.line.mode)))return{error:`${this.active.cargo} cannot use that service`};const legs=[];for(const leg of choice.legs){const route=this.runtimeRoute(leg.line);if(!route)return{error:`${leg.line.label} is not running on the gameplay network`};const fromIdx=route.indexOf(leg.from),toIdx=route.indexOf(leg.to);if(fromIdx<0||toIdx<0||fromIdx===toIdx)return{error:'that service does not cover the selected leg'};legs.push({routeId:route.id,from:leg.from,to:leg.to,fromIdx,toIdx});}const from=this.currentFrom(),to=this.currentTo();const t=this.flow.inject(from,to,{kind:'delivery',job:this.index,leg:this.leg,label:this.active.label,cargo:this.active.cargo,n:1},{allowedModes:c.modes,urgency:c.express?2:1});t.legs=legs;t.legIdx=0;this.activeTrip=t;this.selectedPlan=choice;this.waitingForCatch=false;this.say(`CATCH · ${choice.legs.map(l=>l.line.label).join(' → ')} · ${this.name(from)} → ${this.name(to)}`);return{trip:t};}
 makeRushHour(){const pairs=[['pasila','rautatientori'],['kalasatama','hakaniemi'],['sornainen','rautatientori'],['toolontori','kamppi']];for(let wave=0;wave<4;wave++)for(const[a,b]of pairs)this.flow.inject(a,b,{kind:'rush',n:2});this.say('RUSH HOUR · Central services are filling up.');}
 step(){for(const trip of this.flow.trips.completed){if(!trip.payload||trip.payload.kind!=='delivery'||this.seen.has(trip.id))continue;this.seen.add(trip.id);if(trip.payload.job!==this.index||trip.payload.leg!==this.leg)continue;if(this.leg<this.active.stops.length-2){this.leg++;this.launchLeg();this.say(`TRANSFER STOP · now catch a service to ${this.name(this.active.stops[this.leg+1])}.`);return true;}const elapsed=this.elapsed()+(this.active.event?.penalty||0),c=this.cargoRule(),late=elapsed>this.active.limit;let earned=late?Math.round(this.active.value*.5):this.active.value,note=late?'LATE':'ON TIME';if(c.freshness){const freshLimit=Math.round(this.active.limit*c.freshness);if(elapsed<=freshLimit){const bonus=Math.round(this.active.value*.25);earned+=bonus;this.bonuses+=bonus;note='FRESH BONUS';}else if(!late){earned=Math.round(earned*.8);note='COOLED';}}if(c.fragile&&trip.legs?.length===1&&!late){const bonus=35;earned+=bonus;this.bonuses+=bonus;note='FRAGILE SAFE';}if(c.express&&elapsed<=Math.round(this.active.limit*.7)){const bonus=40;earned+=bonus;this.bonuses+=bonus;note='EXPRESS BONUS';}this.score+=earned;if(late)this.late++;this.say(`${note} · +${earned} · ${this.active.label}`);this.index++;this.leg=0;this.active=null;this.activeTrip=null;this.selectedPlan=null;this.waitingForCatch=false;if(this.index<JOBS.length)this.launchJob();return true;}return false;}
 elapsed(){return this.active?this.flow.clock.tick-this.startedAt:0;}
 remaining(){return this.active?Math.max(0,this.active.limit-this.elapsed()):0;}
 routeLabel(){return this.active?this.active.stops.map(id=>this.name(id)).join(' → '):'';}
 currentFrom(){return this.active?.stops[this.leg];}
 currentTo(){return this.active?.stops[this.leg+1];}
 get complete(){return this.index>=DELIVERY_TARGET;}
 name(id){return this.flow.graph.node(id)?.name||id;}
}
