// Toko Move v2.12.1 — turn walking into a readable transit interception skill.
// Uses the deterministic gameplay fleet, never HSL realtime data.
const nearestPathIndex=(tm,layer,nodeId)=>{const n=tm.city?.resolved?.[nodeId];if(!n||!layer?.path?.length)return null;let bi=0,bd=Infinity;for(let i=0;i<layer.path.length;i++){const q=layer.path[i],d=(q[0]-n.lat)**2+(q[1]-n.lon)**2;if(d<bd){bd=d;bi=i;}}return bi;};
const layerFor=(tm,line)=>tm.transit?.layers?.find(x=>x.id===line.sourceId);
const timingBand=(wait,window)=>{if(wait>=2&&wait<=8)return'TIGHT';if(wait<=16)return'GOOD';if(window>=5)return'WIDE';return'LONG';};
function firstArrival(tm,layer,idx,start,horizon){for(let dt=0;dt<=horizon;dt++){const near=tm.liveNetwork?.nearestTo(layer,idx,start+dt,2.2);if(!near)continue;let windowTicks=1;for(let w=1;w<=12;w++){const still=tm.liveNetwork?.nearestTo(layer,idx,start+dt+w,2.2);if(!still||still.vehicle?.id!==near.vehicle?.id)break;windowTicks++;}return{dt,vehicle:near.vehicle,windowTicks};}return null;}
export function interceptionOptions(tm,{max=3,horizon=120}={}){const ch=tm.challenge,m=tm.mobility;if(!ch?.active||!ch.waitingForCatch||!m?.canWalk?.())return[];const from=ch.currentFrom(),target=ch.currentTo(),now=tm.flow.clock.tick,out=[];for(const walk of m.walks?.()||[]){const arrive=now+walk.cost;for(const line of tm.city?.lines||[]){if(!line.nodes?.includes(walk.to)||!line.nodes.includes(target))continue;const a=line.nodes.indexOf(walk.to),b=line.nodes.indexOf(target);if(a<0||b<0||a===b)continue;const layer=layerFor(tm,line),idx=nearestPathIndex(tm,layer,walk.to);if(!layer||idx==null)continue;const hit=firstArrival(tm,layer,idx,arrive,horizon);if(!hit)continue;const timing=timingBand(hit.dt,hit.windowTicks);out.push({walk,line,layer,vehicle:hit.vehicle,walkTicks:walk.cost,waitTicks:hit.dt,windowTicks:hit.windowTicks,timing,totalTicks:walk.cost+hit.dt,from,hub:walk.to,target});}}
const seen=new Set;return out.sort((a,b)=>{const rank={TIGHT:0,GOOD:1,WIDE:2,LONG:3};return(rank[a.timing]-rank[b.timing])||a.totalTicks-b.totalTicks||b.windowTicks-a.windowTicks||a.walkTicks-b.walkTicks;}).filter(x=>{const k=`${x.hub}:${x.line.mode}:${x.line.label}`;if(seen.has(k))return false;seen.add(k);return true;}).slice(0,max);}
export function bestInterception(tm){return interceptionOptions(tm,{max:1})[0]||null;}
