// Toko Move v2.12.2 — deterministic gameplay fleet on every exact HSL route layer.
// These are schedule-like gameplay vehicles, not HSL realtime positions.
const hash=s=>{let h=2166136261;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;};
export class LiveNetwork{
 constructor(transit,{vehiclesPerLine=2,dwellTicks=3}={}){this.transit=transit;this.vehiclesPerLine=vehiclesPerLine;this.dwellTicks=dwellTicks;this.vehicles=[];this.selectedVehicleId=null;for(const layer of transit?.layers||[]){if(layer.mode!=='TRAM'&&layer.mode!=='SUBWAY')continue;const count=layer.mode==='SUBWAY'?Math.max(2,vehiclesPerLine):vehiclesPerLine;for(let i=0;i<count;i++)this.vehicles.push({id:`${layer.id}:${i}`,layer,phase:(hash(layer.id)+i*997)%10000/10000,speed:layer.mode==='SUBWAY'?.00072:.00048});}}
 position(v,tick){const path=v.layer.path||[];if(path.length<2)return null;const cycle=(v.phase+tick*v.speed)%2,q=cycle<=1?cycle:2-cycle,at=q*(path.length-1),i=Math.min(path.length-2,Math.floor(at)),f=at-i,a=path[i],b=path[i+1];return{lat:a[0]+(b[0]-a[0])*f,lon:a[1]+(b[1]-a[1])*f,pathIndex:at,direction:cycle<=1?1:-1};}
 vehicle(id){return this.vehicles.find(v=>v.id===id)||null;}
 select(id){this.selectedVehicleId=this.vehicle(id)?.id||null;return this.vehicle(this.selectedVehicleId);}
 clearSelection(){this.selectedVehicleId=null;}
 nearestTo(layer,nodePathIndex,tick,maxPathDistance=2.2,direction=null){let best=null;for(const v of this.vehicles){if(v.layer.id!==layer.id)continue;const p=this.position(v,tick);if(!p||(direction&&p.direction!==direction))continue;const d=Math.abs(p.pathIndex-nodePathIndex);if(d<=maxPathDistance&&(!best||d<best.distance))best={vehicle:v,position:p,distance:d};}return best;}
 draw(ctx,tick,project,dpr=1){const boxes=[];ctx.save();ctx.font=`bold ${Math.round(8*dpr)}px ui-monospace,monospace`;ctx.textAlign='center';ctx.textBaseline='middle';for(const v of this.vehicles){if(!v.layer.visible)continue;const p=this.position(v,tick);if(!p)continue;const q=project(p.lat,p.lon),selected=v.id===this.selectedVehicleId,w=(selected?29:24)*dpr,h=(selected?18:14)*dpr;ctx.fillStyle=v.layer.colour;ctx.strokeStyle=selected?'#17242b':'#fffdf7';ctx.lineWidth=(selected?4:2)*dpr;ctx.beginPath();ctx.roundRect(q.x-w/2,q.y-h/2,w,h,3*dpr);ctx.fill();ctx.stroke();if(selected){ctx.strokeStyle='#fffdf7';ctx.lineWidth=1*dpr;ctx.stroke();}ctx.fillStyle='#fff';ctx.fillText(v.layer.name,q.x,q.y+.5*dpr);boxes.push({x:q.x-w/2,y:q.y-h/2,w,h});}ctx.restore();return boxes;}
}
