// Toko Move v2.9 — readable delivery game on real HSL geography.
import { createFlow } from '../../flow-core/sim.js?v=2';
import { FlowRenderer } from '../../flow-core/render.js?v=3';
import { RouteDrawer } from '../../flow-core/input.js?v=1';
import { THEME } from './palette.js?v=1';
import { DeliveryChallenge, DELIVERY_TARGET, CARGO } from './deliveries.js?v=9';
import { TransitLayers } from './transit-layers.js?v=5';
import { buildRealHelsinki } from './real-helsinki.js?v=2';
const BUILD_VERSION='2.9', $=id=>document.getElementById(id);
const MAP_THEME={...THEME,latent:THEME.paper,hideQueues:true,hideLoadMarks:true,hideCarriers:true,modeColours:{metro:'rgba(0,0,0,0)',tram:'rgba(0,0,0,0)',car:'rgba(0,0,0,0)'}};
let flow,challenge,renderer,drawer,draft=null,sel=null,done=false,msgs=[],transitLayers=null,transitView=false,realCity=null,sourcePack=null,waterPack=null;
const say=s=>{msgs.unshift(s);msgs.length=Math.min(msgs.length,10);paintFeed();};
function boot(seed=7){if(!realCity)return;flow=createFlow({city:realCity,seed,days:1,demand:{rate:22,pairs:[{from:'home',to:'work',weight:2},{from:'transfer',to:'shop',weight:1}]},hooks:{onTick:()=>{if(challenge?.step()){paintHud();paintSheet();if(challenge.complete)finish();}},onDay:()=>finish()}});challenge=new DeliveryChallenge(flow,say);done=false;msgs=[];sel=null;$('map').style.aspectRatio=`${flow.graph.bounds.w} / ${flow.graph.bounds.h}`;drawer?.destroy();renderer=new FlowRenderer($('map'),MAP_THEME);drawer=new RouteDrawer($('map'),renderer,flow,{markersProvider:markers,onCommit:(mode,nodes)=>{if(transitView)return;const r=flow.addRoute(mode,nodes);say(r.error?`— ${r.error}`:`NEW LINE · ${nodes.map(id=>flow.graph.node(id).name).join(' → ')}`);paintHud();},onTap:(hit,p)=>{if(transitView)return;if(hit.kind==='node'){sel=hit.id;paintSheet();hidePop();}else showPop(hit,p);},onDraft:d=>draft=d});challenge.start();paintHud();paintSheet();}
async function init(){$('play').disabled=true;$('play').textContent='LOADING HELSINKI…';try{const [r,w]=await Promise.all([fetch('./cities/helsinki.json',{cache:'no-store'}),fetch('../flow-core/data/kallio-water-v1.json',{cache:'no-store'})]);if(!r.ok)throw new Error(`HSL pack ${r.status}`);sourcePack=await r.json();if(w.ok)waterPack=await w.json();transitLayers=new TransitLayers(sourcePack);realCity=buildRealHelsinki(sourcePack);paintTransitPanel();boot();$('play').disabled=false;$('play').textContent='START SHIFT';requestAnimationFrame(frame);}catch(err){$('play').textContent='MAP LOAD FAILED';$('transitMeta').textContent=err.message;console.error(err);}}
function coverageLabel(source){return source.clippedTo?`exact inside ${source.clippedTo.s}–${source.clippedTo.n} N`:'full Helsinki source pack';}
function paintTransitPanel(){if(!transitLayers)return;const s=transitLayers.source;$('transitMeta').textContent=`${s.source} · ${s.fetched} · ${transitLayers.layers.length} source lines · ${coverageLabel(s)}`;const rows=$('transitRows');rows.innerHTML='';for(const layer of transitLayers.layers){const row=document.createElement('div');row.className='lineRow';row.innerHTML=`<span class="lineSwatch" style="background:${layer.colour}"></span><label><input type="checkbox" ${layer.visible?'checked':''}> ${esc(layer.name)} <small>${layer.mode==='SUBWAY'?'metro':'tram'}</small></label><button class="ctl">SOLO</button>`;row.querySelector('input').onchange=e=>transitLayers.setVisible(layer.id,e.target.checked);row.querySelector('button').onclick=()=>{transitLayers.solo(layer.id);paintTransitPanel();};rows.append(row);}}
function showTransit(mode='all'){if(!transitLayers)return;transitView=true;document.body.classList.add('transit-view');$('transitPanel').hidden=false;if(mode==='TRAM')transitLayers.showAll('TRAM');else if(mode==='SUBWAY')transitLayers.showAll('SUBWAY');else transitLayers.showAll();paintTransitPanel();}function hideTransit(){transitView=false;document.body.classList.remove('transit-view');$('transitPanel').hidden=true;}
function gameplayTransitFit(lat,lon){const p=realCity.projectLatLon(lat,lon),f=flow.graph.fit($('map').width,$('map').height);return{x:f.x(p.x),y:f.y(p.y)};}
function drawExactTransitOnGameMap(){if(!transitLayers||!realCity||!flow)return;const c=$('map'),ctx=c.getContext('2d');transitLayers.draw(ctx,c.width,c.height,{fit:gameplayTransitFit,alpha:.6,lineWidth:1.65*(renderer?.dpr||1)});}
function drawTransitView(){if(!transitLayers)return;const c=$('map'),ctx=c.getContext('2d');ctx.fillStyle='#edf4f2';ctx.fillRect(0,0,c.width,c.height);drawWaterContext(.8);transitLayers.draw(ctx,c.width,c.height,{alpha:.96,lineWidth:2.6*(renderer?.dpr||1)});}
const cargoColour=c=>({documents:'#4c7fb0','hot food':'#d65a31',parts:'#6b747b',fragile:'#b16aa5',equipment:'#6d604b',express:'#ca3f37','fresh food':'#5b9d58','market goods':'#b0803c'}[c]||'#e2683c');
function markers(){if(!flow||!challenge||transitView)return[];const out=[],slots={};const slot=n=>(slots[n]=(slots[n]??-1)+1);for(const t of flow.trips.active){if(t.payload?.kind!=='delivery')continue;const col=cargoColour(t.payload.cargo);out.push({id:`job:${t.id}`,node:t.dest,slot:slot(t.dest),glyph:'▣',color:col,data:t});out.push({id:`pickup:${t.id}`,node:t.origin,slot:slot(t.origin),glyph:'○',color:'#2f9fb8',data:t});}return out;}
const esc=s=>String(s).replace(/[&<>"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[ch]));
function relevantTrams(){if(!challenge?.active||!realCity)return[];const from=challenge.currentFrom(),to=challenge.currentTo(),scored=[];for(const l of realCity.lines){if(l.mode!=='tram')continue;const a=l.nodes.includes(from),b=l.nodes.includes(to);if(!a&&!b)continue;const layer=transitLayers.layers.find(x=>x.id===l.sourceId);if(layer)scored.push({layer,score:(a&&b)?3:a?2:1});}return scored.sort((a,b)=>b.score-a.score||String(a.layer.name).localeCompare(String(b.layer.name))).slice(0,6).map(x=>x.layer);}
function nearestPathIndex(layer,nodeId){const n=realCity.resolved[nodeId];if(!n||!layer?.path?.length)return 0;let bi=0,bd=Infinity;for(let i=0;i<layer.path.length;i++){const[lat,lon]=layer.path[i],d=(lat-n.lat)**2+((lon-n.lon)*.5)**2;if(d<bd){bd=d;bi=i;}}return bi;}
function drawNearbyTrams(){if(!challenge?.active||!transitLayers)return;const ctx=$('map').getContext('2d'),d=renderer?.dpr||1,from=challenge.currentFrom(),layers=relevantTrams();ctx.save();for(let k=0;k<layers.length;k++){const layer=layers[k],base=nearestPathIndex(layer,from),span=Math.min(16,Math.max(2,layer.path.length-1)),offset=Math.floor((flow.clock.tick/7+k*5)%span)-Math.floor(span/2),i=Math.max(0,Math.min(layer.path.length-1,base+offset)),[lat,lon]=layer.path[i],p=gameplayTransitFit(lat,lon),w=24*d,h=14*d;ctx.fillStyle=layer.colour;ctx.strokeStyle='#fffdf7';ctx.lineWidth=2*d;ctx.beginPath();ctx.roundRect(p.x-w/2,p.y-h/2,w,h,3*d);ctx.fill();ctx.stroke();ctx.fillStyle='#fff';ctx.font=`bold ${Math.round(8*d)}px ui-monospace,monospace`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(layer.name,p.x,p.y+.5*d);}ctx.restore();}
function tramHintHtml(){const ls=relevantTrams();if(!ls.length)return'<p class="hint">No tram directly touches this leg — build or transfer.</p>';return `<p class="cargoRule">TRAMS NEAR THIS LEG</p><p class="hint">${ls.map(l=>`<span style="display:inline-block;border-bottom:4px solid ${l.colour};margin-right:8px"><b>${esc(l.name)}</b></span>`).join('')}</p>`;}
function showPop(hit,p){const body=popBody(hit);if(!body){hidePop();return;}$('popBody').innerHTML=body;const b=$('pop');b.hidden=false,r=$('map').getBoundingClientRect(),w=Math.min(300,innerWidth-20);b.style.width=w+'px';b.style.left=Math.max(10,Math.min(innerWidth-w-10,r.left+p.x-w/2))+'px';b.style.top=Math.max(10,Math.min(innerHeight-170,r.top+p.y+14))+'px';}function hidePop(){$('pop').hidden=true;}function popBody(hit){if(hit.kind!=='marker')return null;const t=hit.marker.data;if(!t)return null;const c=CARGO[t.payload?.cargo]||CARGO.documents;return `<h3>${hit.marker.id.startsWith('pickup:')?'PICKUP':'DELIVER'} · ${c.icon}</h3><p>${esc(flow.graph.node(t.origin).name)} → ${esc(flow.graph.node(t.dest).name)}</p><p class="dim">${esc(t.payload?.label||'Delivery')}</p>`;}
function paintHud(){if(!challenge)return;const c=challenge.active?challenge.cargoRule():null;$('done').textContent=`${challenge.index}/${DELIVERY_TARGET}`;$('reach').textContent=challenge.active?`${challenge.name(challenge.currentFrom())} → ${challenge.name(challenge.currentTo())}`:'complete';$('emit').textContent=challenge.active?`${challenge.remaining()}t`:`${challenge.score} pts`;$('cargoHud').textContent=c?c.icon:'DONE';$('cargoHud').style.borderColor=challenge.active?cargoColour(challenge.active.cargo):'';$('clock').textContent=`${String(6+Math.floor(flow.clock.dayProgress*16)).padStart(2,'0')}:00`;$('lines').textContent=`${flow.routes.drawn.length}/${flow.routes.maxRoutes} lines`;}
function paintSheet(){const b=$('sheet');if(challenge?.active&&!sel){const j=challenge.active,c=challenge.cargoRule(),multi=j.stops.length>2?` · ${j.stops.length-1} legs`:'';b.innerHTML=`<div class="jobTop"><span class="cargoBadge" style="border-color:${cargoColour(j.cargo)}">${c.icon}</span><div><h2>JOB ${challenge.index+1}/${DELIVERY_TARGET}</h2><p class="route"><b>${challenge.routeLabel()}</b></p></div></div><p class="hint">${j.label} · ${j.cargo}${multi}</p><p class="cargoRule">${c.rule}</p>${tramHintHtml()}<div class="meter"><i style="width:${Math.max(0,Math.min(100,100*challenge.remaining()/j.limit))}%"></i></div><p class="hint">${challenge.remaining()} ticks remaining · score ${challenge.score}</p>`;return;}if(!sel){b.innerHTML='<p class="hint">Tap a named stop for details.</p>';return;}const n=flow.graph.node(sel),hsl=realCity.nodes.find(x=>x.id===sel);b.innerHTML=`<h2>${n.name}</h2><p class="hint">HSL: ${esc(hsl?.hslStopName||n.name)} · ${flow.routes.routesAt(sel).length} services call here</p><button class="btn wide" id="jobBack">SHOW CURRENT JOB</button>`;$('jobBack').onclick=()=>{sel=null;paintSheet();};}
function paintFeed(){const f=$('feed');f.innerHTML='';for(const m of msgs.slice(0,3)){const d=document.createElement('div');d.textContent=m;f.append(d);}}
function drawWaterContext(alpha=.55){if(!waterPack||!realCity||!flow)return;const ctx=$('map').getContext('2d'),d=renderer?.dpr||1;ctx.save();ctx.globalAlpha=alpha;ctx.strokeStyle='#72a9bd';ctx.fillStyle='rgba(132,190,211,.18)';ctx.lineWidth=1.2*d;for(const area of waterPack.areas||[]){if(!area.shape?.length)continue;ctx.beginPath();area.shape.forEach(([lat,lon],i)=>{const p=gameplayTransitFit(lat,lon);i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y);});ctx.closePath();ctx.fill();ctx.stroke();}ctx.strokeStyle='#4f95af';ctx.lineWidth=1.6*d;for(const edge of waterPack.edges||[]){if(!edge.shape?.length)continue;ctx.beginPath();edge.shape.forEach(([lat,lon],i)=>{const p=gameplayTransitFit(lat,lon);i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y);});ctx.stroke();}ctx.restore();}
function drawCityOverlay(){const c=$('map'),ctx=c.getContext('2d');if(!flow||!renderer)return;const f=flow.graph.fit(c.width,c.height),d=renderer.dpr||1;ctx.save();ctx.globalAlpha=.58;ctx.fillStyle='#5d6a72';ctx.font=`${Math.round(8*d)}px ui-monospace,monospace`;ctx.textAlign='center';for(const[id,label]of[['kapyla','KÄPYLÄ'],['pasila','PASILA'],['toolontori','TÖÖLÖ'],['kallionkirkko','KALLIO'],['rautatientori','CENTRE'],['kalasatama','KALASATAMA'],['lansiterminaali','WEST HARBOUR'],['eira','EIRA'],['katajanokka','KATAJANOKKA']]){const n=flow.graph.node(id);if(n)ctx.fillText(label,f.x(n.x),f.y(n.y)-18*d);}if(challenge?.active){for(const[id,col]of[[challenge.currentFrom(),'#2f9fb8'],[challenge.currentTo(),cargoColour(challenge.active.cargo)]]){const n=flow.graph.node(id);if(!n)continue;ctx.strokeStyle=col;ctx.globalAlpha=.9;ctx.lineWidth=3*d;ctx.beginPath();ctx.arc(f.x(n.x),f.y(n.y),13*d,0,Math.PI*2);ctx.stroke();}}ctx.restore();}
function finish(){if(done)return;done=true;flow.clock.setPaused(true);$('endTitle').textContent=challenge.complete?'ALL DELIVERED':'DAY OVER';$('endStats').innerHTML=`<p>deliveries <b>${challenge.index}/${DELIVERY_TARGET}</b></p><p>score <b>${challenge.score}</b></p><p>cargo bonuses <b>${challenge.bonuses}</b></p><p>late jobs <b>${challenge.late}</b></p>`;$('endNote').textContent=challenge.complete?'Ten real-Helsinki jobs complete.':'Run it again and finish the route.';$('end').hidden=false;}
let last=0;function frame(now){const dt=last?Math.min(120,now-last):0;last=now;if(flow){flow.update(dt);if(transitView)drawTransitView();else{renderer.draw(flow,{draft,selected:sel,alpha:flow.clock.alpha(),markers:markers()});drawWaterContext();drawExactTransitOnGameMap();drawNearbyTrams();drawCityOverlay();}if(flow.clock.tick%10===0){paintHud();if(!sel)paintSheet();}}requestAnimationFrame(frame);}
addEventListener('resize',()=>renderer?.resize());$('play').onclick=()=>{if(!flow)return;$('title').hidden=true;flow.clock.setPaused(false);};$('pause').onclick=()=>{if(!flow)return;flow.clock.setPaused(!flow.clock.paused);$('pause').textContent=flow.clock.paused?'▶':'❚❚';};$('speed').onclick=()=>{if(!flow)return;const s=flow.clock.speed>=4?1:flow.clock.speed*2;flow.clock.setSpeed(s);$('speed').textContent=`×${s}`;};$('again').onclick=()=>{$('end').hidden=true;boot(7);flow.clock.setPaused(false);};$('popClose').onclick=hidePop;$('transit').onclick=()=>transitView?hideTransit():showTransit('all');$('transitClose').onclick=hideTransit;$('tramOnly').onclick=()=>showTransit('TRAM');$('metroOnly').onclick=()=>showTransit('SUBWAY');$('allTransit').onclick=()=>showTransit('all');addEventListener('keydown',e=>{if(e.key==='Escape'){if(transitView)hideTransit();else hidePop();}});init();window.__tm={version:BUILD_VERSION,get flow(){return flow;},get challenge(){return challenge;},get transit(){return transitLayers;},get city(){return realCity;},debug:{boot,finish,markers,relevantTrams,showTransit,hideTransit}};
