// Toko Move v2.12 — Toko-specific mobility state layered around DeliveryChallenge.
// Keeps shared flow-core untouched.
export class MobilityController{
 constructor(tm){this.tm=tm;this.ch=tm.challenge;this.location=null;this.walking=null;this.pendingGetOff=null;this.lastLegKey=this.legKey();this.baseCurrentFrom=this.ch.currentFrom.bind(this.ch);this.baseStep=this.ch.step.bind(this.ch);this.ch.currentFrom=()=>this.location||this.baseCurrentFrom();this.ch.step=()=>this.step();}
 legKey(){return `${this.ch.index}:${this.ch.leg}:${this.ch.active?.label||''}`;}
 syncLeg(){const k=this.legKey();if(k!==this.lastLegKey){this.lastLegKey=k;this.location=null;this.walking=null;this.pendingGetOff=null;}}
 canWalk(){const c=this.ch.cargoRule?.();return Boolean(this.ch.active&&!c?.modes);}
 walks(){if(!this.ch.active||!this.ch.waitingForCatch||this.walking||this.pendingGetOff)return[];return (this.tm.walksFrom?.(this.ch.currentFrom())||[]).map(link=>({...link,cost:this.walkCost(link)}));}
 walkCost(link){const a=this.tm.city?.resolved?.[link.from],b=this.tm.city?.resolved?.[link.to];if(!a||!b)return 18;const lat=(a.lat+b.lat)*.5*Math.PI/180,dy=(a.lat-b.lat)*111320,dx=(a.lon-b.lon)*111320*Math.cos(lat),metres=Math.hypot(dx,dy);return Math.max(7,Math.round(metres/85));}
 beginWalk(link){if(!this.canWalk())return{error:`${this.ch.active?.cargo||'cargo'} must stay on transit`};if(!this.ch.waitingForCatch||this.walking||this.pendingGetOff)return{error:'cannot walk now'};const valid=this.walks().find(x=>x.to===link?.to&&x.street===link?.street);if(!valid)return{error:'that walking link is not available'};this.walking={...valid,startTick:this.tm.flow.clock.tick,arriveTick:this.tm.flow.clock.tick+valid.cost};this.ch.waitingForCatch=false;this.ch.say?.(`WALK · ${this.ch.name(valid.from)} → ${this.ch.name(valid.to)} · ${valid.street} · ${valid.cost}t`);return{walking:this.walking};}
 getOff(){if(!this.pendingGetOff)return{error:'not waiting to get off'};const at=this.ch.currentTo();this.pendingGetOff=null;this.location=at;const changed=this.baseStep();this.ch.say?.(`GET OFF · ${this.ch.name(at)}`);this.syncLeg();return{ok:true,changed};}
 step(){this.syncLeg();if(this.walking){if(this.tm.flow.clock.tick>=this.walking.arriveTick){const w=this.walking;this.location=w.to;this.walking=null;this.ch.waitingForCatch=true;this.ch.say?.(`ARRIVED ON FOOT · ${this.ch.name(this.location)} · choose transit or keep walking.`);return true;}return false;}if(this.pendingGetOff)return false;for(const trip of this.tm.flow.trips.completed||[]){if(trip.payload?.kind!=='delivery'||this.ch.seen?.has(trip.id))continue;if(trip.payload.job!==this.ch.index||trip.payload.leg!==this.ch.leg)continue;this.pendingGetOff=trip;this.location=this.ch.currentTo();this.ch.activeTrip=null;this.ch.waitingForCatch=false;this.ch.say?.(`ARRIVED · ${this.ch.name(this.location)} · GET OFF.`);return true;}return this.baseStep();}
 status(){if(this.pendingGetOff)return{kind:'getoff',at:this.location};if(this.walking)return{kind:'walking',...this.walking,remaining:Math.max(0,this.walking.arriveTick-this.tm.flow.clock.tick)};if(this.ch.waitingForCatch)return{kind:'waiting',at:this.ch.currentFrom()};return{kind:'riding'};}
}
