// Toko Move v2.11 — catch existing HSL services; never draw a new transit line.
const uniq=a=>[...new Set(a)];
const serviceKey=l=>`${l.mode}:${l.label}`;
function orderedLeg(line,from,to){const a=line.nodes.indexOf(from),b=line.nodes.indexOf(to);if(a<0||b<0||a===b)return null;return{line,from,to,stops:Math.abs(b-a),direction:b>a?1:-1};}
function routeChoices(city,from,to,max=3){if(!city||!from||!to)return[];const direct=[];for(const line of city.lines||[]){const leg=orderedLeg(line,from,to);if(leg)direct.push({kind:'direct',legs:[leg],transfers:0,cost:leg.stops+(line.mode==='metro'?-0.25:0)});}const transfers=[];for(const a of city.lines||[]){if(!a.nodes.includes(from))continue;for(const b of city.lines||[]){if(serviceKey(a)===serviceKey(b)||!b.nodes.includes(to))continue;const shared=uniq(a.nodes.filter(n=>b.nodes.includes(n)&&n!==from&&n!==to));for(const at of shared){const l1=orderedLeg(a,from,at),l2=orderedLeg(b,at,to);if(!l1||!l2)continue;transfers.push({kind:'transfer',legs:[l1,l2],transfer:at,transfers:1,cost:l1.stops+l2.stops+2});}}}const seen=new Set(),all=[...direct,...transfers].sort((x,y)=>x.cost-y.cost||x.transfers-y.transfers).filter(c=>{const k=c.legs.map(x=>serviceKey(x.line)).join('>')+':'+(c.transfer||'');if(seen.has(k))return false;seen.add(k);return true;});return all.slice(0,max);}
function servicesAt(city,node){return(city?.lines||[]).filter(l=>l.nodes.includes(node));}
globalThis.__tmRouteChoiceCore={routeChoices,servicesAt};
function esc(s){return String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c));}
function nodeName(city,id){return city?.nodes?.find(n=>n.id===id)?.name||id;}
function directionName(city,leg){const i=leg.line.nodes.indexOf(leg.to),next=leg.line.nodes[i+leg.direction];return next?nodeName(city,next):nodeName(city,leg.to);}
function layerFor(tm,line){return tm.transit?.layers?.find(x=>x.id===line.sourceId);}
function chip(tm,leg){const layer=layerFor(tm,leg.line),colour=layer?.colour||'#52676d';return `<span style="display:inline-block;border-bottom:4px solid ${colour};background:#fffdf7;padding:5px 7px;margin:3px 5px 3px 0;font:700 11px ui-monospace,monospace"><b>${esc(leg.line.label)}</b> ${esc(leg.line.mode)} → ${esc(directionName(tm.city,leg))}</span>`;}
function render(tm){const sheet=document.getElementById('sheet'),ch=tm.challenge;if(!sheet||!ch?.active||!tm.city)return;const key=`${ch.index}:${ch.leg}:${ch.currentFrom()}:${ch.currentTo()}:${ch.waitingForCatch}:${ch.activeTrip?.id||''}`;let box=document.getElementById('routeChoices');if(box?.dataset.key===key)return;if(!box){box=document.createElement('section');box.id='routeChoices';box.style.cssText='margin-top:10px;padding-top:9px;border-top:1px dashed #c5cec8';sheet.append(box);}box.dataset.key=key;const choices=routeChoices(tm.city,ch.currentFrom(),ch.currentTo(),3),from=nodeName(tm.city,ch.currentFrom()),to=nodeName(tm.city,ch.currentTo());if(!ch.waitingForCatch&&ch.selectedPlan){box.innerHTML=`<b style="font-size:11px">ON THE WAY · ${esc(from)} → ${esc(to)}</b><div style="margin-top:6px;padding:8px;background:#eef5ef;border-radius:7px">${ch.selectedPlan.legs.map(l=>chip(tm,l)).join('')}<p style="font-size:11px;color:#69777a;margin-top:4px">Ride the selected service${ch.selectedPlan.transfers?' and change at '+esc(nodeName(tm.city,ch.selectedPlan.transfer)):''}.</p></div>`;return;}if(!choices.length){box.innerHTML=`<b style="font-size:11px">CATCH A SERVICE</b><p style="font-size:11px;color:#69777a;margin-top:4px">No fixed HSL chain connects ${esc(from)} → ${esc(to)}.</p>`;return;}box.innerHTML=`<b style="font-size:11px">CATCH A SERVICE · ${esc(from)} → ${esc(to)}</b><p style="font-size:10px;color:#69777a;margin:4px 0">All real colored lines stay visible. Pick the tram/metro you want to ride.</p>`+choices.map((c,i)=>`<button class="catchChoice" data-choice="${i}" style="display:block;width:100%;min-height:52px;text-align:left;margin-top:6px;padding:7px 8px;background:${i===0?'#eef5ef':'#f7f5ee'};border:1px solid #c5cec8;border-radius:7px;font:inherit;cursor:pointer"><span style="font-size:10px;color:#69777a">${i===0?'FASTEST READ':`OPTION ${i+1}`} · ${c.transfers?`CHANGE AT ${esc(nodeName(tm.city,c.transfer))}`:'DIRECT'}</span><div>${c.legs.map(l=>chip(tm,l)).join('')}</div><b style="font-size:11px">CATCH</b></button>`);box.querySelectorAll('.catchChoice').forEach(btn=>btn.onclick=()=>{const choice=choices[Number(btn.dataset.choice)],res=ch.catchChoice(choice);if(res?.error){box.insertAdjacentHTML('beforeend',`<p style="font-size:11px;color:#b34a36">${esc(res.error)}</p>`);}else render(tm);});}
function disableDrawing(){const c=document.getElementById('map');if(!c||c.dataset.catchOnly)return;c.dataset.catchOnly='1';for(const ev of ['pointerdown','pointermove','pointerup','pointercancel'])c.addEventListener(ev,e=>{e.stopImmediatePropagation();},{capture:true});c.style.cursor='default';}
function mount(){if(typeof window==='undefined')return;let last='';setInterval(()=>{const tm=window.__tm;if(!tm?.challenge)return;disableDrawing();tm.transit?.showAll?.();const lineHud=document.getElementById('lines');if(lineHud)lineHud.textContent='HSL network';const ch=tm.challenge,k=ch.active?`${ch.index}:${ch.leg}:${ch.currentFrom()}:${ch.currentTo()}:${ch.waitingForCatch}:${ch.activeTrip?.id||''}`:'done';if(k!==last||!document.getElementById('routeChoices')){last=k;render(tm);}},250);}
mount();
