// generated by scripts/hub-finish.mjs — do not edit
const CACHE = 'kindling-hub-98729fa8';
const SHELL = [
  "./",
  "./art/ashling-portrait.png",
  "./art/ashling.png",
  "./art/camp.jpg",
  "./art/ember-portrait.png",
  "./art/ember.png",
  "./art/mossknight-portrait.png",
  "./art/mossknight.png",
  "./art/mossling-portrait.png",
  "./art/mossling.png",
  "./art/path.jpg",
  "./assets/client-9TTsPYGB.js",
  "./assets/index-DpweD1XA.js",
  "./assets/jsx-runtime-Cltr0gcK.js",
  "./assets/login-D4CgLARc.js",
  "./assets/routes-CjIALjDd.js",
  "./assets/styles-CEedHFVi.css",
  "./favicon.svg",
  "./hub-shell.js",
  "./index.html",
  "./og.jpg",
  "./x-banner.jpg"
];
self.addEventListener('install', e => e.waitUntil((async () => {
  const c = await caches.open(CACHE);
  await Promise.all(SHELL.map(u => c.add(new Request(u, { cache: 'reload' })).catch(() => {})));
  self.skipWaiting();
})()));
self.addEventListener('activate', e => e.waitUntil((async () => {
  for (const k of await caches.keys()) if (k !== CACHE) await caches.delete(k);
  await self.clients.claim();
})()));
self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== location.origin) return;
  e.respondWith((async () => {
    const hit = await caches.match(req);
    if (hit) return hit;
    try { return await fetch(req); }
    catch {
      if (req.mode === 'navigate') {
        const shell = await caches.match('./index.html');
        if (shell) return shell;
      }
      throw new Error('offline and uncached');
    }
  })());
});
