// generated by scripts/hub-finish.mjs — do not edit
const CACHE = 'kindling-hub-54c3f3fd';
const SHELL = [
  "./",
  "./VERSIONS.md",
  "./art/ashling-idle-runtime.png",
  "./art/ashling-portrait.png",
  "./art/ashling.png",
  "./art/ashwood-clean.svg",
  "./art/bell-keep-clean.svg",
  "./art/birch-ruins-clean.png",
  "./art/birch-ruins-clean.svg",
  "./art/birch-ruins.png",
  "./art/camp-night-clean.png",
  "./art/camp.jpg",
  "./art/camp/camp-q1.png",
  "./art/camp/camp-q2.png",
  "./art/camp/camp-q3.png",
  "./art/camp/camp-q4.png",
  "./art/drowned-courtyard-clean.svg",
  "./art/ember-idle-runtime-fixed.svg",
  "./art/ember-idle-runtime.svg",
  "./art/ember-portrait.png",
  "./art/ember.png",
  "./art/fire-states.png",
  "./art/mossknight-idle-runtime.png",
  "./art/mossknight-portrait.png",
  "./art/mossknight.png",
  "./art/mossling-idle-runtime.png",
  "./art/mossling-portrait.png",
  "./art/mossling.png",
  "./art/path.png",
  "./art/path.webp",
  "./art/ui/ui-kit.png",
  "./assets/client-9TTsPYGB.js",
  "./assets/dev.sprites-DcjDmiQz.js",
  "./assets/ember-atlas-sprite-BOwJqyY4.js",
  "./assets/index-r6UvjU0X.js",
  "./assets/jsx-runtime-Cltr0gcK.js",
  "./assets/login-BBX-TjgR.js",
  "./assets/routes-D21qLubW.js",
  "./assets/styles-B1P4cpIh.css",
  "./favicon.svg",
  "./hub-shell.js",
  "./index.html",
  "./og.jpg",
  "./x-banner.jpg"
];
self.addEventListener('install', e => e.waitUntil((async () => {
  const c = await caches.open(CACHE);
  await Promise.all(SHELL.map(u => c.add(new Request(u, { cache: 'reload' })).catch(() => {})));
  self.skipWaiting();
})()));
self.addEventListener('activate', e => e.waitUntil((async () => {
  for (const k of await caches.keys()) if (k !== CACHE) await caches.delete(k);
  await self.clients.claim();
})()));
self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== location.origin) return;
  e.respondWith((async () => {
    const hit = await caches.match(req);
    if (hit) return hit;
    try { return await fetch(req); }
    catch {
      if (req.mode === 'navigate') {
        const shell = await caches.match('./index.html');
        if (shell) return shell;
      }
      throw new Error('offline and uncached');
    }
  })());
});
