// Lightweight i18n for Toko Drop. Localizes the DOM-overlay UI (title, controls,
// death screen, feedback panel, wave banner). The on-canvas HUD and the
// roguelike upgrade cards intentionally stay English (canvas monospace fonts
// render CJK unreliably and the HUD layout is space-tight).
//
// t(key, ...args) returns the string for the active language, falling back to
// English for any missing key. Values may be plain strings or functions (for
// templated strings that interpolate a runtime label).

const STRINGS = {
  en: {
    subtitle: 'TWIN-STICK SWARM SURVIVAL',   // v199: the movement game is the game
    best: 'BEST', pts: 'PTS', wave: 'WAVE',
    tapStart: 'TAP OR PRESS SPACE TO START',
    ctrlMove: 'Move',        ctrlMoveH: 'left stick / WASD',
    ctrlAim: 'Aim & fire',   ctrlAimH: 'right stick / hold LMB',
    ctrlDash: 'Dash',        ctrlDashH: 'A / bumper / Space',
    ctrlPause: 'Pause',      ctrlPauseH: 'Start / ESC',
    ctrlEyes: 'Eyes',        ctrlEyesH: 'E',
    orientation: 'ORIENTATION', landscape: 'LANDSCAPE', portrait: 'PORTRAIT',
    orientLandH: 'Wide arena — Steam Deck / sideways mobile',
    orientPortH: 'Tall arena — upright mobile',
    rogue: 'ROGUELIKE MODE', on: 'ON', off: 'OFF',
    rush: 'RUSH MODE',
    rushOnH: 'Boost is the answer — it kills on contact and shields you, but firing drops the shield. Watch the heat',
    rushOffH: 'Classic rules — dash, standard gun',
    rushHeat: 'HEAT', rushChain: 'CHAIN', rushLevel: 'LEVEL', rushOverheat: 'OVERHEAT',
    rushLadder: 'RUSH LADDER', rushStars: 'stars',
    rogueOnH: 'A: upgrade cards every 3rd wave',
    rogueBH: 'B: cards + rare BONUS GAUNTLET runs (big multipliers)',
    rogueOffH: 'No upgrades — pure arcade survival',
    daily: 'DAILY RUN',
    dailyOnH: "Everyone plays today's seed — compare scores",
    dailyOffH: 'Random seed every run',
    dailyBest: 'DAILY BEST',
    tokotron: 'TOKOTRON',
    tokotronH: 'Arcade cabinet: dark room, rescue the civilians!',
    gaundrop: 'GAUNDROP',
    gaundropH: 'Arcade cabinet: dungeon levels — smash the generators, find the exit!',
    binding: 'BINDING OF TOKO',
    bindingH: 'Arcade cabinet: room by room, build your blob — items are everything!',
    loadout: 'LOADOUT',
    loadoutH: 'Arcade cabinet: pick your kit, run the missions!',
    cabRow: 'CABINET',
    cabRowH: 'Arcade cabinets — pick one at a time; TAP TO START plays it.',
    cabBest: 'BEST',
    nexdeus: 'NEX DEUS',
    nexLockedH: 'LOCKED — push every cabinet past its mark to power it on',
    nexReadyH: 'UNLOCKED — the cycle button now reaches the sixth slot',
    nexdeusH: 'The FINAL cabinet: five games bleed together. Your dash cuts now.',
    todayMod: 'TODAY',
    kaikki: 'KAIKKI IRTI 3',
    kaikkiH: 'Arcade cabinet: kill everything, get paid, buy bigger!',
    kkShop: 'THE SHOP',
    kkCash: 'CASH',
    // v206: witnesses on the street — the wallet earns half while watched
    kkWatched: 'WITNESSES:',
    kkHalf: 'CASH HALVED',
    kkClear: 'STREET CLEAR — FULL CASH',
    // v208: street jobs — the order rotates, and the HUD names it
    kkJob: 'JOB',
    kkJobDone: 'JOB DONE!',
    kkJobClear: 'STREETS CLEARED',
    kkJ_purge: 'PURGE', kkJ_payday: 'PAYDAY',
    kkJ_mark: 'THE MARK', kkJ_shakedown: 'SHAKEDOWN',
    kkLeft: 'LEFT', kkCratesLeft: 'CRATES LEFT', kkMarkRuns: 'HE RUNS. RUN HIM DOWN',
    kkBrief_purge: 'KILL EVERYTHING ON THE BLOCK',
    kkBrief_payday: 'MAKE THE QUOTA — KILLS AND CRATES BOTH PAY',
    kkBrief_mark: 'ONE NAME. RINGED IN RED. HE CANNOT LEAVE',
    kkBrief_shakedown: 'CRACK EVERY GOLD CRATE ON THE STREET',
    kkNext: 'NEXT MISSION »',
    kkOwned: 'OWNED',
    kk_uzi: 'KONEPISTOOLI',
    kk_uzi_d: 'Rapid pod + fire rate.',
    kk_shotgun: 'HAULIKKO',
    kk_shotgun_d: 'Twin spread + bigger rounds.',
    kk_laser: 'LASERI',
    kk_laser_d: 'Laser + piercing rounds.',
    kk_sinko: 'SINKO',
    kk_sinko_d: 'Heavy burst, pierces, huge rounds.',
    kk_medkit: 'MEDKIT',
    kk_medkit_d: '+2 HP right now.',
    kk_kevlar: 'KEVLAR',
    kk_kevlar_d: '+1 max HP.',
    kk_boots: 'NITROSAAPPAAT',
    kk_boots_d: 'Move 20% faster.',
    kk_liekki: 'LIEKINHEITIN',   kk_liekki_d: 'Tier 2: a hose of fat, fast fire.',
    kk_magneetti: 'MAGNEETTI',   kk_magneetti_d: 'Tier 2: cash and pickups fly to you.',
    kk_kilpi: 'KILPI',           kk_kilpi_d: 'Tier 2: a shield charge, restocked.',
    q_kaikki: 'KAIKKI IRTI HIT',
    q_kaikki_d: 'Bonus quest: clear 2 street missions. Score climbs like pinball!',
    q_nexdeus: 'NEX DEUS COMMUNION',
    q_nexdeus_d: 'Bonus quest: survive 2 surge waves inside the god-machine. Score climbs like pinball!',
    q_tokotron: 'TOKOTRON RAID',
    q_tokotron_d: 'Bonus quest: survive 2 flood waves in the vector dark. Score climbs like pinball!',
    q_gaundrop: 'GAUNDROP DELVE',
    q_gaundrop_d: 'Bonus quest: find the exit of one dungeon level. Score climbs like pinball!',
    q_loadout: 'LOADOUT OP',
    q_loadout_d: 'Bonus quest: complete 2 missions with the build you brought. Score climbs like pinball!',
    q_binding: 'BASEMENT DETOUR',
    q_binding_d: 'Bonus quest: clear 3 basement rooms. Score climbs like pinball!',
    loPick: 'PICK YOUR LOADOUT',
    // v204: mission briefings — the radio callout that opens every op
    loMsn: 'MISSION',
    loBrief_purge:    'PURGE THE FIELD',
    loBrief_demolish: 'DEMOLISH THE GENERATORS',
    loBrief_holdout:  'HOLD THE LINE',
    loBrief_assault:  'ASSAULT THE COMMAND POST',
    loBrief_rescue:   'GET THEM OUT ALIVE',
    lo_gunner: 'Gunner',
    lo_gunner_d: 'Twin spread + fire rate.',
    lo_lancer: 'Lancer',
    lo_lancer_d: 'Laser + piercing rounds.',
    lo_runner: 'Runner',
    lo_runner_d: 'Rapid fire + speed.',
    lo_tank: 'Juggernaut',
    lo_tank_d: 'Heavy burst + extra HP.',
    lbTitle: 'DAILY TOP 10',
    lbPost: 'POST SCORE', lbPosted: 'POSTED ✓',
    lbNone: 'No scores yet today — be first!',
    language: 'LANGUAGE',
    volume: 'VOLUME', annVolume: 'ANNOUNCER VOL.', reduceMotion: 'REDUCE MOTION',
    reduceMotionOnH: 'No camera shake', reduceMotionOffH: 'Full screen-shake feedback',
    haptics: 'HAPTICS', hapticsOnH: 'Vibrate on hits, death, overheat (Android Chrome only)',
    hapticsOffH: 'No vibration',
    rushAbilityRow: 'RUSH ABILITY', rushAbilityRowH: 'Pick one — fires on the dash button in RUSH MODE.',
    rushAbilityReady: 'READY',
    heatExchange: 'HEAT EXCHANGE', heatExchangeH: 'Dump your heat as a burn around you — bigger the hotter you are.',
    hyperBomb: 'HYPER BOMB', hyperBombH: 'A big clear that costs no heat. The panic button.',
    overcharge: 'OVERCHARGE', overchargeH: 'A window where boosting is free and the chain climbs double.',
    quantumShield: 'QUANTUM SHIELD', quantumShieldH: 'A window where enemy fire is reflected back as yours.',
    settings: 'SETTINGS', settingsHint: 'Settings are in the pause menu (⏸)',
    options: 'OPTIONS',
    smashTV: 'SMASH TV MODE',
    smashOnH: 'Enemies rush from 4 doors, bigger waves, more prizes — from the next wave',
    smashOffH: 'Standard waves surround the arena',
    meleeMode: 'CLOSE COMBAT',
    meleeOnH: 'Its own roster, nobody fires — every body hurts, and corpses strike back in kind: aimed bursts, fans, rings',
    meleeOffH: 'Standard arsenal — shooters shoot',
    gpuMode: 'WEBGPU (BETA)',
    gpuOnH: 'Experimental renderer — real WebGPU where the browser grants it, WebGL2 otherwise (HUD tag shows which); reloads now',
    gpuOffH: 'Classic WebGL renderer — toggling reloads the page',
    announcer: 'ANNOUNCER',
    annOnH: 'Loud game-show commentary (spoken, English)',
    annOffH: 'No commentary',
    graze: 'GRAZE',
    testMode: 'TEST MODE',
    testOnH: 'All enemies from wave 1 — no records kept',
    testOffH: 'Normal progression',
    pixelMode: 'PIXEL PREVIEW',
    pixelOnH: 'Chunky retro rendering (arcade tribute look, WIP)',
    pixelOffH: 'Modern rendering',
    introVoice: 'INTRO VOICE',
    introOnH: 'Recorded title shout ("TOKO DROP!")',
    introOffH: 'Silent title screen',
    perfMode: 'PERFORMANCE MODE',
    perfOnH: 'Lower resolution, no glass or shadows — for slower phones', perfOffH: 'Full visual quality',
    runHistory: 'RUN HISTORY', noRuns: 'No runs yet — play one!',
    rhScore: 'SCORE', rhWave: 'WAVE', rhTime: 'TIME', rhMode: 'MODE', close: 'CLOSE',
    youDied: 'YOU DIED',
    bestScore: '★ BEST SCORE', bestTime: '★ BEST TIME', bestWave: '★ BEST WAVE',
    seed: 'SEED',
    // v212: contextual death-screen questions — the arg is the killer's name
    fbq_killerRead:  n => `You went down to a ${n}. Could you read what it was about to do?`,
    fbq_killerShot:  n => `A ${n} shot you. Did you see the shot coming, or did it arrive out of nowhere?`,
    fbq_killerLob:   n => `A ${n} got you from range. Was there enough warning on the ground?`,
    fbq_hazard:      () => 'The arena killed you, not an enemy. Did the hazard telegraph clearly enough?',
    fbq_swarmRead:   n => `You died in a crowd. With that many bodies on screen, could you still tell a ${n} apart?`,
    fbq_movement:    n => `How did the ${n} MOVE? Did it behave like its own creature, or like everything else?`,
    fbq_general:     () => 'What was the last thing that surprised you in that run?',
    fbqPlaceholder: 'a sentence is plenty…',
    fbEnjoy: 'WHAT DID YOU ENJOY?  (optional)',
    fbWrong: 'WHAT WENT WRONG?  (optional)',
    fbElse: 'Anything else? (optional)',
    fbSend: 'SEND & CONTINUE', fbContinue: 'CONTINUE', fbSkip: 'SKIP',
    fbShare: 'SHARE', fbCopied: 'COPIED!',
    likeWeapons: 'The weapon pods', likeBosses: 'Boss fights',
    likeFeel: 'Movement / dash feel', likeDodging: 'Bullet-hell dodging',
    likeVariety: 'Enemy variety', likeVibe: 'Visuals / vibe',
    likeRooms: 'Room-to-room doors', likeLoot: 'Cash & prizes',
    likeGraze: 'Close-call grazes',
    fbTooFast: 'Enemies / bullets too fast', fbUnfair: 'Felt unfair / cheap',
    fbUnclear: "Couldn't read the threat",
    fbHit: (l) => `${l} hit me too often`,
    fbMany: (l) => `Too many ${l}s at once`,
    fbDash: 'Dash was on cooldown',
    fbBullets: 'Too many bullets onscreen',
    fbBlender: 'Got swarmed all at once',
    fbWarden: 'Wardens blocked my shots',
    fbDoors: 'Room exits confused me',
    hudStreak: 'STREAK', hudShld: 'SHLD', hudHi: 'HI', hudScoreMult: 'SCORE',
    chooseUpgrade: 'CHOOSE UPGRADE',
    // v205: BINDING floor item pools — the pedestal names the floor's character
    bdPool_blood: 'THE BLOOD OFFERS',
    bdPool_iron:  'THE IRON OFFERS',
    bdPool_quick: 'THE QUICK OFFERS',
    bdPool_deep:  'THE DEEP OFFERS',
    // v207: BINDING room revisits — the floor is a map you can walk back through
    bdCleared: 'CLEARED',
    bdBack: 'BACK',
    chooseRare: 'CHOOSE RARE UPGRADE',
    g_t1: 'BONUS GAUNTLET', g_t1_d: '4 rooms + a boss. Rising score multiplier. Clear it → a RARE upgrade. Death is death.',
    g_t2: 'GAUNTLET TIER 2', g_t2_d: '2 brutal rooms, a boss, then a MEGA boss. Bigger multiplier, same rules.',
    c_r_hp: 'Iron Heart',      c_r_hp_d: '+2 HP.',
    c_r_rate: 'Overdrive',     c_r_rate_d: 'Fire 40% faster permanently.',
    c_r_speed: 'Mercury Soles',c_r_speed_d: 'Move 40% faster permanently.',
    c_r_pierce: 'Lance Rounds',c_r_pierce_d: 'Piercing + 30% bigger bullets.',
    c_hp: '+1 HP',                  c_hp_d: 'Gain one extra hit point.',
    c_speed: 'Speed Up',            c_speed_d: 'Move 20% faster permanently.',
    c_firerate: 'Fire Rate Up',     c_firerate_d: 'Fire 20% faster permanently.',
    c_bigbullets: 'Bigger Bullets', c_bigbullets_d: 'Player bullets are 30% larger.',
    c_dashcd: 'Dash Refresh',       c_dashcd_d: 'Dash cooldown −0.15 s.',
    c_nuke: 'Nuke',                 c_nuke_d: 'Clear all enemy bullets now.',
    c_pierce: 'Pierce',             c_pierce_d: 'Bullets pass through enemies.',
    c_magnet: 'Magnet',             c_magnet_d: 'Pickups drift toward you.',
    c_shield: 'Shield',             c_shield_d: 'Absorbs one hit; resets each wave.',
    c_dashboom: 'Dash Boom',        c_dashboom_d: 'Radial explosion on every dash.',
    c_graze: 'Close Shave',         c_graze_d: 'Grazing bullets pays TRIPLE score.',
    c_vampire: 'Suds Feast',        c_vampire_d: 'Every 25 kills restores 1 HP.',
    c_longdash: 'Long Slide',       c_longdash_d: 'Dash carries 30% farther.',
    c_ripple: 'Ripple Rounds',      c_ripple_d: 'Big kills\' shockwaves damage everything they rattle. Chain it.',
    c_tiredlegs: 'Tired Legs',      c_tiredlegs_d: 'Every dodge costs the dodger 1 HP. Train them to death.',
    c_minnow: 'Minnow Bounty',      c_minnow_d: 'Split-spawned minnows pay TRIPLE score.',
    cursedTag: 'CURSED',
    c_x_berserk: 'Berserk Oath',    c_x_berserk_d: 'Fire 40% faster — but lose 1 max HP.',
    c_x_glasscannon: 'Glass Cannon', c_x_glasscannon_d: 'Huge piercing shots — but lose 1 max HP.',
    c_x_leadfeet: 'Lead Boots',     c_x_leadfeet_d: '+2 max HP — but move 15% slower.',
    c_x_gambler: 'Blood Money',     c_x_gambler_d: 'Kills pay DOUBLE — but dash recharges slower.',
  },
  ja: {
    subtitle: 'ツインスティック群れサバイバル',
    best: 'ベスト', pts: '点', wave: 'ウェーブ',
    tapStart: 'タップまたはスペースでスタート',
    ctrlMove: '移動',          ctrlMoveH: '左スティック / WASD',
    ctrlAim: '照準＆射撃',      ctrlAimH: '右スティック / 左クリック長押し',
    ctrlDash: 'ダッシュ',       ctrlDashH: 'A / バンパー / スペース',
    ctrlPause: 'ポーズ',        ctrlPauseH: 'スタート / ESC',
    ctrlEyes: '目',             ctrlEyesH: 'E',
    orientation: '画面の向き', landscape: '横', portrait: '縦',
    orientLandH: '横長アリーナ — Steam Deck / 横向きモバイル',
    orientPortH: '縦長アリーナ — 縦向きモバイル',
    rogue: 'ローグライク', on: 'オン', off: 'オフ',
    rush: 'ラッシュモード',
    rushOnH: 'ブーストが答え — 触れれば倒し、無敵になる。だが撃てば盾は消える。熱に注意',
    rushOffH: '通常ルール — ダッシュと標準の銃',
    rushHeat: 'ヒート', rushChain: 'チェイン', rushLevel: 'レベル', rushOverheat: 'オーバーヒート',
    rushLadder: 'ラッシュ・ラダー', rushStars: '個の星',
    rogueOnH: 'A：3ウェーブごとにアップグレード',
    rogueBH: 'B：カード + レアなボーナスガントレット（高倍率）',
    rogueOffH: 'アップグレードなし — 純粋なアーケード',
    daily: 'デイリーラン',
    dailyOnH: '今日は全員同じシード — スコアで勝負',
    dailyOffH: '毎回ランダムシード',
    dailyBest: 'デイリーベスト',
    tokotron: 'TOKOTRON',
    tokotronH: 'アーケード筐体：暗い部屋で市民を救出せよ！',
    gaundrop: 'GAUNDROP',
    gaundropH: 'アーケード筐体：ダンジョン階層 — ジェネレーターを壊して出口へ！',
    binding: 'BINDING OF TOKO',
    bindingH: 'アーケード筐体：部屋から部屋へ、ブロブをビルドせよ — アイテムがすべて！',
    loadout: 'LOADOUT',
    loadoutH: 'アーケード筐体：装備を選んでミッションに挑め！',
    cabRow: 'キャビネット',
    cabRowH: 'アーケード筐体 — 選べるのは1台だけ。タップでスタート！',
    cabBest: 'ベスト',
    nexdeus: 'NEX DEUS',
    nexLockedH: 'ロック中 — 全キャビネットで基準を超えると起動する',
    nexReadyH: 'アンロック — 切替ボタンに6番目のスロットが現れた',
    nexdeusH: '最後の筐体：5つのゲームが溶け合う。ダッシュが刃になる。',
    todayMod: '今日',
    kaikki: 'KAIKKI IRTI 3',
    kaikkiH: 'アーケード筐体：皆殺しにして、稼いで、もっとデカい銃を買え！',
    kkShop: 'ショップ',
    kkCash: '所持金',
    kkWatched: '目撃者:',
    kkHalf: '稼ぎ半減',
    kkClear: '通りは無人 — 稼ぎ全額',
    kkJob: '依頼',
    kkJobDone: '依頼完了！',
    kkJobClear: '通りは片付いた',
    kkJ_purge: '掃討', kkJ_payday: '稼ぎ日',
    kkJ_mark: '標的', kkJ_shakedown: 'ゆすり',
    kkLeft: '残り', kkCratesLeft: '箱 残り', kkMarkRuns: '逃げる。追い詰めろ',
    kkBrief_purge: 'この区画を皆殺しにしろ',
    kkBrief_payday: 'ノルマを稼げ — 敵も木箱も金になる',
    kkBrief_mark: '標的は一人。赤い輪。逃げ場はない',
    kkBrief_shakedown: '金色の木箱をすべて叩き割れ',
    kkNext: '次のミッション »',
    kkOwned: '購入済み',
    kk_uzi: 'KONEPISTOOLI',
    kk_uzi_d: 'ラピッドポッド＋連射速度。',
    kk_shotgun: 'HAULIKKO',
    kk_shotgun_d: '二連スプレッド＋大型弾。',
    kk_laser: 'LASERI',
    kk_laser_d: 'レーザー＋貫通弾。',
    kk_sinko: 'SINKO',
    kk_sinko_d: 'ヘビーバースト、貫通、特大弾。',
    kk_medkit: 'MEDKIT',
    kk_medkit_d: '即座にHP+2。',
    kk_kevlar: 'KEVLAR',
    kk_kevlar_d: '最大HP+1。',
    kk_boots: 'NITROSAAPPAAT',
    kk_boots_d: '移動速度20%アップ。',
    kk_liekki: 'LIEKINHEITIN',   kk_liekki_d: 'ティア2：太く速い火線のホース。',
    kk_magneetti: 'MAGNEETTI',   kk_magneetti_d: 'ティア2：現金とアイテムが吸い寄せられる。',
    kk_kilpi: 'KILPI',           kk_kilpi_d: 'ティア2：シールド1枚、毎回補充可。',
    q_kaikki: 'KAIKKI IRTI 襲撃',
    q_kaikki_d: 'ボーナスクエスト：ストリートミッションを2つクリアせよ。スコアはピンボール式に倍増！',
    q_nexdeus: 'NEX DEUS交信',
    q_nexdeus_d: 'ボーナスクエスト：神の筐体でサージ2波を生き延びろ。スコアはピンボール式に倍増！',
    q_tokotron: 'TOKOTRONレイド',
    q_tokotron_d: 'ボーナスクエスト：ベクターの闇で2ウェーブを生き延びろ。スコアはピンボール式に倍増！',
    q_gaundrop: 'GAUNDROPの探索',
    q_gaundrop_d: 'ボーナスクエスト：ダンジョン1階の出口を見つけろ。スコアはピンボール式に倍増！',
    q_loadout: 'LOADOUT作戦',
    q_loadout_d: 'ボーナスクエスト：今のビルドでミッションを2つ完了せよ。スコアはピンボール式に倍増！',
    q_binding: '地下室の寄り道',
    q_binding_d: 'ボーナスクエスト：地下室の部屋を3つクリアせよ。スコアはピンボール式に倍増！',
    loPick: 'ロードアウトを選べ',
    loMsn: '任務',
    loBrief_purge:    '敵性排除',
    loBrief_demolish: '発電機を破壊せよ',
    loBrief_holdout:  '戦線を維持せよ',
    loBrief_assault:  '司令部を制圧せよ',
    loBrief_rescue:   '全員生きて連れ出せ',
    lo_gunner: 'ガンナー',
    lo_gunner_d: '二連スプレッド＋連射速度。',
    lo_lancer: 'ランサー',
    lo_lancer_d: 'レーザー＋貫通弾。',
    lo_runner: 'ランナー',
    lo_runner_d: '速射＋移動速度。',
    lo_tank: 'ジャガーノート',
    lo_tank_d: 'ヘビーバースト＋HP増加。',
    lbTitle: 'デイリーTOP10',
    lbPost: 'スコア送信', lbPosted: '送信済み ✓',
    lbNone: 'まだ記録なし — 一番乗りしよう！',
    language: '言語',
    volume: '音量', annVolume: 'アナウンサー音量', reduceMotion: '手ぶれ軽減',
    reduceMotionOnH: 'カメラ揺れなし', reduceMotionOffH: '画面揺れ演出あり',
    haptics: '振動', hapticsOnH: '被弾・死亡・オーバーヒート時に振動（Android Chromeのみ）',
    hapticsOffH: '振動なし',
    rushAbilityRow: 'RUSHアビリティ', rushAbilityRowH: '1つ選択 — RUSHモードでダッシュボタンに発動。',
    rushAbilityReady: '準備完了',
    heatExchange: 'ヒートエクスチェンジ', heatExchangeH: '熱を爆発として周囲に放出 — 熱いほど大きい。',
    hyperBomb: 'ハイパーボム', hyperBombH: '熱を消費しない大範囲一掃。パニックボタン。',
    overcharge: 'オーバーチャージ', overchargeH: 'ブーストが無料になり、チェーンが2倍になる時間。',
    quantumShield: 'クォンタムシールド', quantumShieldH: '敵弾を跳ね返して自分の弾にする時間。',
    settings: '設定', settingsHint: '設定はポーズメニューにあります（⏸）',
    options: 'オプション',
    smashTV: 'SMASH TVモード',
    smashOnH: '敵が4つの扉から突入、ウェーブ増強、賞品も増加 — 次のウェーブから',
    smashOffH: '通常ウェーブ（全方向から出現）',
    meleeMode: '接近戦モード',
    meleeOnH: '専用の敵編成、誰も撃たない — 触れれば痛い。死体は種族ごとに撃ち返す：狙い撃ち、扇、リング',
    meleeOffH: '通常の武装 — 射撃する敵は撃ってくる',
    gpuMode: 'WEBGPU（ベータ）',
    gpuOnH: '実験的レンダラー — 対応ブラウザでは本物のWebGPU、それ以外はWebGL2（HUD表示で判別）。すぐ再読み込み',
    gpuOffH: '従来のWebGLレンダラー — 切り替えると再読み込み',
    announcer: 'アナウンサー',
    annOnH: 'にぎやかな実況コメント（音声・英語）',
    annOffH: '実況なし',
    graze: 'かすり',
    testMode: 'テストモード',
    testOnH: '全敵がウェーブ1から登場 — 記録は残らない',
    testOffH: '通常の進行',
    pixelMode: 'ピクセルプレビュー',
    pixelOnH: 'レトロなドット描画（アーケード風・開発中）',
    pixelOffH: '通常の描画',
    introVoice: 'イントロ音声',
    introOnH: 'タイトルの録音ボイス（「TOKO DROP!」）',
    introOffH: 'タイトルは無音',
    perfMode: '軽量モード',
    perfOnH: '低解像度・ガラス効果と影なし（低速端末向け）', perfOffH: 'フル画質',
    runHistory: 'プレイ履歴', noRuns: 'まだ記録がありません — プレイしよう！',
    rhScore: 'スコア', rhWave: 'ウェーブ', rhTime: 'タイム', rhMode: 'モード', close: '閉じる',
    youDied: 'ゲームオーバー',
    bestScore: '★ ベストスコア', bestTime: '★ ベストタイム', bestWave: '★ ベストウェーブ',
    seed: 'シード',
    fbq_killerRead:  n => `${n} に倒された。何をしようとしているか読めた？`,
    fbq_killerShot:  n => `${n} に撃たれた。弾は見えていた？それとも突然だった？`,
    fbq_killerLob:   n => `${n} に遠距離でやられた。地面の予告は十分だった？`,
    fbq_hazard:      () => '敵ではなくアリーナに倒された。危険の予告は分かりやすかった？',
    fbq_swarmRead:   n => `混戦の中で死んだ。あれだけ密集していても ${n} を見分けられた？`,
    fbq_movement:    n => `${n} の「動き」はどうだった？固有の生き物らしく見えた？`,
    fbq_general:     () => 'あのランで最後に驚いたことは？',
    fbqPlaceholder: '一文で十分です…',
    fbEnjoy: '良かった点は？（任意）',
    fbWrong: '悪かった点は？（任意）',
    fbElse: 'その他（任意）',
    fbSend: '送信して続行', fbContinue: '続行', fbSkip: 'スキップ',
    fbShare: '共有', fbCopied: 'コピーしました',
    likeWeapons: '武器ポッド', likeBosses: 'ボス戦',
    likeFeel: '操作感／ダッシュ', likeDodging: '弾幕回避',
    likeVariety: '敵のバリエーション', likeVibe: 'ビジュアル／雰囲気',
    likeRooms: '部屋から部屋への移動', likeLoot: '現金と賞品',
    likeGraze: 'かすり回避',
    fbTooFast: '敵／弾が速すぎる', fbUnfair: '理不尽に感じた',
    fbUnclear: '脅威が見づらい',
    fbHit: (l) => `${l}に撃たれすぎた`,
    fbMany: (l) => `${l}が一度に多すぎた`,
    fbDash: 'ダッシュがクールダウン中だった',
    fbBullets: '画面上の弾が多すぎた',
    fbBlender: '一度に群がられた',
    fbWarden: 'ワーデンに弾を防がれた',
    fbDoors: '部屋の出口が分かりづらい',
    hudStreak: '連続', hudShld: 'シールド', hudHi: 'ハイ', hudScoreMult: 'スコア',
    chooseUpgrade: 'アップグレードを選択',
    bdPool_blood: '血の捧げもの',
    bdPool_iron:  '鉄の捧げもの',
    bdPool_quick: '疾さの捧げもの',
    bdPool_deep:  '深淵の捧げもの',
    bdCleared: '踏破済み',
    bdBack: 'もどる',
    chooseRare: 'レア強化を選択',
    g_t1: 'ボーナスガントレット', g_t1_d: '4部屋＋ボス。スコア倍率が上昇。クリアでレア強化。死は死。',
    g_t2: 'ガントレット第2層', g_t2_d: '過酷な2部屋＋ボス＋メガボス。倍率アップ、ルールは同じ。',
    c_r_hp: 'アイアンハート',   c_r_hp_d: 'HP +2',
    c_r_rate: 'オーバードライブ', c_r_rate_d: '発射速度が永久に40%上昇',
    c_r_speed: '水銀の靴',      c_r_speed_d: '移動速度が永久に40%上昇',
    c_r_pierce: 'ランス弾',     c_r_pierce_d: '貫通＋弾が30%拡大',
    c_hp: 'HP +1',             c_hp_d: 'ヒットポイントを1つ追加',
    c_speed: 'スピードアップ',   c_speed_d: '移動速度が永久に20%上昇',
    c_firerate: '連射アップ',    c_firerate_d: '発射速度が永久に20%上昇',
    c_bigbullets: '弾の拡大',    c_bigbullets_d: 'プレイヤーの弾が30%大きくなる',
    c_dashcd: 'ダッシュ回復',    c_dashcd_d: 'ダッシュのクールダウン −0.15秒',
    c_nuke: 'ニューク',          c_nuke_d: '敵弾をすべて消す',
    c_pierce: '貫通',            c_pierce_d: '弾が敵を貫通する',
    c_magnet: 'マグネット',      c_magnet_d: 'アイテムが引き寄せられる',
    c_shield: 'シールド',        c_shield_d: '1発を防ぐ。ウェーブごとに回復',
    c_dashboom: 'ダッシュ爆発',  c_dashboom_d: 'ダッシュのたびに放射状に爆発',
    c_graze: '紙一重',           c_graze_d: '弾スレスレ回避のスコアが3倍',
    c_vampire: '泡の宴',         c_vampire_d: '25キルごとにHPが1回復',
    c_longdash: 'ロングスライド', c_longdash_d: 'ダッシュ距離が30%伸びる',
    c_ripple: 'リップル弾', c_ripple_d: '大物撃破の衝撃波が揺らした敵にダメージ。連鎖せよ',
    c_tiredlegs: 'くたびれ足', c_tiredlegs_d: '回避するたび敵はHPを1失う。訓練で殺せ',
    c_minnow: '小魚の賞金', c_minnow_d: '分裂した小魚はスコア3倍',
    cursedTag: '呪われている',
    c_x_berserk: '狂戦士の誓い',  c_x_berserk_d: '連射40%アップ — ただし最大HPが1減る',
    c_x_glasscannon: 'ガラスの大砲', c_x_glasscannon_d: '巨大な貫通弾 — ただし最大HPが1減る',
    c_x_leadfeet: '鉛のブーツ',   c_x_leadfeet_d: '最大HP+2 — ただし移動が15%遅くなる',
    c_x_gambler: '血の報酬',      c_x_gambler_d: 'キルの報酬が2倍 — ただしダッシュの回復が遅くなる',
  },
  fi: {
    subtitle: 'KAKSITIKKU-PARVISELVIYTYMINEN',
    best: 'PARAS', pts: 'PIST.', wave: 'AALTO',
    tapStart: 'NAPAUTA TAI PAINA VÄLILYÖNTIÄ',
    ctrlMove: 'Liiku',          ctrlMoveH: 'vasen tatti / WASD',
    ctrlAim: 'Tähtää & ammu',   ctrlAimH: 'oikea tatti / pidä LMB',
    ctrlDash: 'Syöksy',         ctrlDashH: 'A / olkanäppäin / väli',
    ctrlPause: 'Tauko',         ctrlPauseH: 'Start / ESC',
    ctrlEyes: 'Silmät',         ctrlEyesH: 'E',
    orientation: 'SUUNTA', landscape: 'VAAKA', portrait: 'PYSTY',
    orientLandH: 'Leveä areena — Steam Deck / vaakamobiili',
    orientPortH: 'Korkea areena — pystymobiili',
    rush: 'RYNTÄYSTILA',
    rushOnH: 'Syöksy on vastaus — se tappaa kosketuksesta ja suojaa sinut, mutta ampuminen katkaisee suojan. Varo kuumenemista',
    rushOffH: 'Klassiset säännöt — pyrähdys ja tavallinen ase',
    rushHeat: 'KUUMUUS', rushChain: 'KETJU', rushLevel: 'TASO', rushOverheat: 'YLIKUUMENEE',
    rushLadder: 'RUSH-TIKKAAT', rushStars: 'tähteä',
    rogue: 'ROGUELIKE-TILA', on: 'PÄÄLLÄ', off: 'POIS',
    rogueOnH: 'A: päivityskortit joka 3. aallossa',
    rogueBH: 'B: kortit + harvinaiset BONUS-haasteet (isot kertoimet)',
    rogueOffH: 'Ei päivityksiä — pelkkää arcade-selviytymistä',
    daily: 'PÄIVÄN HAASTE',
    dailyOnH: 'Kaikki pelaavat päivän siementä — vertaa pisteitä',
    dailyOffH: 'Satunnainen siemen joka pelillä',
    dailyBest: 'PÄIVÄN PARAS',
    tokotron: 'TOKOTRON',
    tokotronH: 'Arcade-kaappi: pimeä huone, pelasta siviilit!',
    gaundrop: 'GAUNDROP',
    gaundropH: 'Arcade-kaappi: luolastotasot — tuhoa generaattorit, etsi uloskäynti!',
    binding: 'BINDING OF TOKO',
    bindingH: 'Arcade-kaappi: huone huoneelta, rakenna blobisi — esineet ratkaisevat!',
    loadout: 'LOADOUT',
    loadoutH: 'Arcade-kaappi: valitse varustus, hoida tehtävät!',
    cabRow: 'KAAPPI',
    cabRowH: 'Arcade-kaapit — valitse yksi kerrallaan; TAP TO START pelaa sen.',
    cabBest: 'ENNÄTYS',
    nexdeus: 'NEX DEUS',
    nexLockedH: 'LUKITTU — ylitä jokaisen kaapin raja niin se käynnistyy',
    nexReadyH: 'AVATTU — valintanappi yltää nyt kuudenteen paikkaan',
    nexdeusH: 'VIIMEINEN kaappi: viisi peliä sulautuu yhteen. Syöksysi leikkaa nyt.',
    todayMod: 'TÄNÄÄN',
    kaikki: 'KAIKKI IRTI 3',
    kaikkiH: 'Arcade-kaappi: tapa kaikki, kerää rahat, osta isompaa!',
    kkShop: 'KAUPPA',
    kkCash: 'RAHAT',
    kkWatched: 'SILMINNÄKIJÖITÄ:',
    kkHalf: 'TIENESTIT PUOLIKKAAT',
    kkClear: 'KATU TYHJÄ — TÄYDET TIENESTIT',
    kkJob: 'KEIKKA',
    kkJobDone: 'KEIKKA HOIDETTU!',
    kkJobClear: 'KADUT PUHTAAT',
    kkJ_purge: 'SIIVOUS', kkJ_payday: 'TILIPÄIVÄ',
    kkJ_mark: 'KOHDE', kkJ_shakedown: 'RAVISTELU',
    kkLeft: 'JÄLJELLÄ', kkCratesLeft: 'LAATIKKOA JÄLJELLÄ', kkMarkRuns: 'HÄN JUOKSEE. AJA KIINNI',
    kkBrief_purge: 'TAPA KAIKKI KORTTELISTA',
    kkBrief_payday: 'TEE TILI — TAPOT JA LAATIKOT MAKSAVAT',
    kkBrief_mark: 'YKSI NIMI. PUNAINEN RENGAS. EI PÄÄSE POIS',
    kkBrief_shakedown: 'RIKO JOKAINEN KULTAINEN LAATIKKO',
    kkNext: 'SEURAAVA KEIKKA »',
    kkOwned: 'OSTETTU',
    kk_uzi: 'KONEPISTOOLI',
    kk_uzi_d: 'Pikapoti + tulinopeus.',
    kk_shotgun: 'HAULIKKO',
    kk_shotgun_d: 'Kaksoishajonta + isommat kudit.',
    kk_laser: 'LASERI',
    kk_laser_d: 'Laser + läpäisevät kudit.',
    kk_sinko: 'SINKO',
    kk_sinko_d: 'Raskas sarja, läpäisee, valtavat kudit.',
    kk_medkit: 'MEDKIT',
    kk_medkit_d: '+2 HP heti.',
    kk_kevlar: 'KEVLAR',
    kk_kevlar_d: '+1 maksimi-HP.',
    kk_boots: 'NITROSAAPPAAT',
    kk_boots_d: 'Liiku 20% nopeammin.',
    kk_liekki: 'LIEKINHEITIN',   kk_liekki_d: 'Taso 2: paksua, nopeaa tulta letkusta.',
    kk_magneetti: 'MAGNEETTI',   kk_magneetti_d: 'Taso 2: rahat ja tavarat lentävät sinulle.',
    kk_kilpi: 'KILPI',           kk_kilpi_d: 'Taso 2: kilpipanos, täydennettävissä.',
    q_kaikki: 'KAIKKI IRTI -KEIKKA',
    q_kaikki_d: 'Bonustehtävä: selvitä 2 katukeikkaa. Pisteet nousevat kuin flipperissä!',
    q_nexdeus: 'NEX DEUS -YHTEYS',
    q_nexdeus_d: 'Bonustehtävä: selviä 2 syöksyaallosta jumalkoneessa. Pisteet nousevat kuin flipperissä!',
    q_tokotron: 'TOKOTRON-RYNNÄKKÖ',
    q_tokotron_d: 'Bonustehtävä: selviä 2 vyöryaallosta vektoripimeydessä. Pisteet nousevat kuin flipperissä!',
    q_gaundrop: 'GAUNDROP-SUKELLUS',
    q_gaundrop_d: 'Bonustehtävä: löydä yhden luolastokerroksen uloskäynti. Pisteet nousevat kuin flipperissä!',
    q_loadout: 'LOADOUT-OPERAATIO',
    q_loadout_d: 'Bonustehtävä: suorita 2 tehtävää nykyisellä varustuksella. Pisteet nousevat kuin flipperissä!',
    q_binding: 'KELLARIKIERROS',
    q_binding_d: 'Bonustehtävä: selvitä 3 kellarihuonetta. Pisteet nousevat kuin flipperissä!',
    loPick: 'VALITSE VARUSTUS',
    loMsn: 'TEHTÄVÄ',
    loBrief_purge:    'PUHDISTA KENTTÄ',
    loBrief_demolish: 'TUHOA GENERAATTORIT',
    loBrief_holdout:  'PIDÄ LINJA',
    loBrief_assault:  'VALTAA KOMENTOPAIKKA',
    loBrief_rescue:   'SAA HEIDÄT ULOS ELÄVINÄ',
    lo_gunner: 'Ampuja',
    lo_gunner_d: 'Kaksoishajonta + tulinopeus.',
    lo_lancer: 'Keihäs',
    lo_lancer_d: 'Laser + läpäisevät ammukset.',
    lo_runner: 'Juoksija',
    lo_runner_d: 'Pika-ammunta + nopeus.',
    lo_tank: 'Jyrä',
    lo_tank_d: 'Raskas sarja + lisä-HP.',
    lbTitle: 'PÄIVÄN TOP 10',
    lbPost: 'LÄHETÄ TULOS', lbPosted: 'LÄHETETTY ✓',
    lbNone: 'Ei vielä tuloksia tänään — ole ensimmäinen!',
    language: 'KIELI',
    volume: 'ÄÄNENVOIMAKKUUS', annVolume: 'KUULUTTAJAN ÄÄNI', reduceMotion: 'VÄHENNÄ LIIKETTÄ',
    reduceMotionOnH: 'Ei kameran tärinää', reduceMotionOffH: 'Täysi ruudun tärinä',
    haptics: 'TÄRINÄ', hapticsOnH: 'Tärinä osumista, kuolemasta, ylikuumenemisesta (vain Android Chrome)',
    hapticsOffH: 'Ei tärinää',
    rushAbilityRow: 'RUSH-KYKY', rushAbilityRowH: 'Valitse yksi — laukeaa dash-napista RUSH-tilassa.',
    rushAbilityReady: 'VALMIS',
    heatExchange: 'HEAT EXCHANGE', heatExchangeH: 'Pura lämpösi räjähdyksenä ympärillesi — mitä kuumempi, sitä suurempi.',
    hyperBomb: 'HYPER BOMB', hyperBombH: 'Suuri puhdistus, ei maksa lämpöä. Hätänappi.',
    overcharge: 'OVERCHARGE', overchargeH: 'Ikkuna, jossa boostaus on ilmaista ja ketju nousee tuplana.',
    quantumShield: 'QUANTUM SHIELD', quantumShieldH: 'Ikkuna, jossa vihollisten tuli heijastuu takaisin omanasi.',
    settings: 'ASETUKSET', settingsHint: 'Asetukset ovat taukovalikossa (⏸)',
    options: 'VALINNAT',
    smashTV: 'SMASH TV -TILA',
    smashOnH: 'Viholliset ryntäävät 4 ovesta, isommat aallot, enemmän palkintoja — seuraavasta aallosta',
    smashOffH: 'Tavalliset aallot saartavat areenan',
    meleeMode: 'LÄHITAISTELU',
    meleeOnH: 'Oma vihollisvalikoima, kukaan ei ammu — jokainen kosketus sattuu, ja ruumiit kostavat lajinsa tavalla: tähdätyt sarjat, viuhkat, renkaat',
    meleeOffH: 'Tavallinen arsenaali — ampujat ampuvat',
    gpuMode: 'WEBGPU (BETA)',
    gpuOnH: 'Kokeellinen renderöijä — aito WebGPU kun selain sen sallii, muuten WebGL2 (HUD kertoo kumpi); lataa sivun heti',
    gpuOffH: 'Perinteinen WebGL-renderöijä — vaihto lataa sivun uudelleen',
    announcer: 'SELOSTAJA',
    annOnH: 'Äänekäs peliohjelmaselostus (puhuttu, englanniksi)',
    annOffH: 'Ei selostusta',
    graze: 'HIPAISU',
    testMode: 'TESTITILA',
    testOnH: 'Kaikki viholliset aallosta 1 — ei tallenteita',
    testOffH: 'Normaali eteneminen',
    pixelMode: 'PIKSELIESIKATSELU',
    pixelOnH: 'Rakeinen retrokuva (arcade-kunnianosoitus, kesken)',
    pixelOffH: 'Moderni kuva',
    introVoice: 'INTRO-ÄÄNI',
    introOnH: 'Nauhoitettu aloitushuuto ("TOKO DROP!")',
    introOffH: 'Hiljainen aloitusruutu',
    perfMode: 'SUORITUSKYKYTILA',
    perfOnH: 'Matalampi resoluutio, ei lasiefektejä eikä varjoja — hitaille puhelimille', perfOffH: 'Täysi kuvanlaatu',
    runHistory: 'PELIHISTORIA', noRuns: 'Ei vielä pelejä — pelaa yksi!',
    rhScore: 'PISTEET', rhWave: 'AALTO', rhTime: 'AIKA', rhMode: 'TILA', close: 'SULJE',
    youDied: 'KUOLIT',
    bestScore: '★ PARAS PISTEMÄÄRÄ', bestTime: '★ PARAS AIKA', bestWave: '★ PARAS AALTO',
    seed: 'SIEMEN',
    fbq_killerRead:  n => `${n} kaatoi sinut. Pystyitkö lukemaan mitä se aikoi tehdä?`,
    fbq_killerShot:  n => `${n} ampui sinut. Näitkö laukauksen tulevan vai tuliko se tyhjästä?`,
    fbq_killerLob:   n => `${n} sai sinut kaukaa. Oliko maassa tarpeeksi varoitusta?`,
    fbq_hazard:      () => 'Areena tappoi sinut, ei vihollinen. Varoittiko vaara tarpeeksi selvästi?',
    fbq_swarmRead:   n => `Kuolit väkijoukossa. Erotitko silti ${n}-vihollisen muista?`,
    fbq_movement:    n => `Miten ${n} LIIKKUI? Käyttäytyikö se kuin oma lajinsa vai kuin kaikki muut?`,
    fbq_general:     () => 'Mikä yllätti sinut viimeksi tuolla kierroksella?',
    fbqPlaceholder: 'yksi lause riittää…',
    fbEnjoy: 'MISTÄ PIDIT?  (valinnainen)',
    fbWrong: 'MIKÄ MENI PIELEEN?  (valinnainen)',
    fbElse: 'Jotain muuta? (valinnainen)',
    fbSend: 'LÄHETÄ & JATKA', fbContinue: 'JATKA', fbSkip: 'OHITA',
    fbShare: 'JAA', fbCopied: 'KOPIOITU!',
    likeWeapons: 'Asepodit', likeBosses: 'Pomotaistelut',
    likeFeel: 'Liike / syöksy', likeDodging: 'Luotien väistely',
    likeVariety: 'Vihollisten kirjo', likeVibe: 'Visuaalit / tunnelma',
    likeRooms: 'Huoneesta huoneeseen -ovet', likeLoot: 'Käteinen ja palkinnot',
    likeGraze: 'Täpärät väistöt',
    fbTooFast: 'Viholliset / luodit liian nopeita', fbUnfair: 'Tuntui epäreilulta',
    fbUnclear: 'Uhkaa ei voinut lukea',
    fbHit: (l) => `${l} osui liian usein`,
    fbMany: (l) => `Liikaa ${l}-vihollisia kerralla`,
    fbDash: 'Syöksy oli jäähdyllä',
    fbBullets: 'Liikaa luoteja ruudulla',
    fbBlender: 'Jäin joukon saartamaksi',
    fbWarden: 'Wardenit torjuivat laukaukseni',
    fbDoors: 'Huoneiden uloskäynnit sekoittivat',
    hudStreak: 'PUTKI', hudShld: 'KILPI', hudHi: 'HI', hudScoreMult: 'PISTEET',
    chooseUpgrade: 'VALITSE PÄIVITYS',
    bdPool_blood: 'VERI TARJOAA',
    bdPool_iron:  'RAUTA TARJOAA',
    bdPool_quick: 'NOPEUS TARJOAA',
    bdPool_deep:  'SYVYYS TARJOAA',
    bdCleared: 'TYHJENNETTY',
    bdBack: 'TAKAISIN',
    chooseRare: 'VALITSE HARVINAINEN PÄIVITYS',
    g_t1: 'BONUS-HAASTE', g_t1_d: '4 huonetta + pomo. Nouseva pistekerroin. Läpäisystä HARVINAINEN päivitys. Kuolema on kuolema.',
    g_t2: 'HAASTE, TASO 2', g_t2_d: '2 raakaa huonetta, pomo ja MEGA-pomo. Isompi kerroin, samat säännöt.',
    c_r_hp: 'Rautasydän',      c_r_hp_d: 'HP +2.',
    c_r_rate: 'Ylikierrokset', c_r_rate_d: 'Ammu pysyvästi 40% nopeammin.',
    c_r_speed: 'Elohopeapohjat', c_r_speed_d: 'Liiku pysyvästi 40% nopeammin.',
    c_r_pierce: 'Peitsiluodit', c_r_pierce_d: 'Läpäisy + 30% isommat luodit.',
    c_hp: 'HP +1',                  c_hp_d: 'Yksi ylimääräinen osumapiste.',
    c_speed: 'Nopeus +',            c_speed_d: 'Liiku pysyvästi 20% nopeammin.',
    c_firerate: 'Tulinopeus +',     c_firerate_d: 'Ammu pysyvästi 20% nopeammin.',
    c_bigbullets: 'Isommat luodit', c_bigbullets_d: 'Pelaajan luodit 30% suuremmat.',
    c_dashcd: 'Syöksyn lataus',     c_dashcd_d: 'Syöksyn jäähtyminen −0,15 s.',
    c_nuke: 'Ydinisku',             c_nuke_d: 'Tyhjennä kaikki vihollisluodit.',
    c_pierce: 'Läpäisy',            c_pierce_d: 'Luodit läpäisevät viholliset.',
    c_magnet: 'Magneetti',          c_magnet_d: 'Poiminnat ajautuvat luoksesi.',
    c_shield: 'Kilpi',              c_shield_d: 'Vaimentaa yhden osuman; nollautuu aallottain.',
    c_dashboom: 'Syöksyräjähdys',   c_dashboom_d: 'Säteittäinen räjähdys joka syöksyllä.',
    c_graze: 'Täpärä väistö',       c_graze_d: 'Luotien hipominen maksaa KOLMINKERTAISESTI.',
    c_vampire: 'Vaahtojuhla',       c_vampire_d: 'Joka 25. tappo palauttaa 1 HP.',
    c_longdash: 'Pitkä liuku',      c_longdash_d: 'Syöksy kantaa 30% pidemmälle.',
    c_ripple: 'Väreilyammukset',    c_ripple_d: 'Isojen tappojen paineaalto vahingoittaa kaikkea mitä se ravistaa. Ketjuta.',
    c_tiredlegs: 'Väsyneet jalat',  c_tiredlegs_d: 'Jokainen väistö maksaa väistäjälle 1 HP. Kouluta ne hengiltä.',
    c_minnow: 'Pikkukalapalkkio',   c_minnow_d: 'Halkeamisesta syntyneet pikkukalat maksavat KOLMINKERTAISESTI.',
    cursedTag: 'KIROTTU',
    c_x_berserk: 'Berserkin vala',  c_x_berserk_d: 'Ammu 40% nopeammin — mutta menetä 1 max HP.',
    c_x_glasscannon: 'Lasitykki',   c_x_glasscannon_d: 'Valtavat läpäisevät laukaukset — mutta menetä 1 max HP.',
    c_x_leadfeet: 'Lyijysaappaat',  c_x_leadfeet_d: '+2 max HP — mutta liiku 15% hitaammin.',
    c_x_gambler: 'Veriraha',        c_x_gambler_d: 'Tapot maksavat TUPLASTI — mutta syöksy latautuu hitaammin.',
  },
};

const LANGS       = ['en', 'ja', 'fi'];
const LANG_LABELS = { en: 'ENG', ja: '日本語', fi: 'SUOMI' };

let _lang = localStorage.getItem('tokoDropLang') || 'en';
if (!LANGS.includes(_lang)) _lang = 'en';

export function getLang()   { return _lang; }
export function langLabel() { return LANG_LABELS[_lang]; }

// All selectable languages as {code, label} — for rendering a picker.
export function langs() {
  return LANGS.map(code => ({ code, label: LANG_LABELS[code] }));
}

// Set the active language directly and persist it.
export function setLang(code) {
  if (LANGS.includes(code)) {
    _lang = code;
    localStorage.setItem('tokoDropLang', _lang);
  }
  return _lang;
}

// Advance to the next language (EN → JA → FI → EN) and persist the choice.
export function cycleLang() {
  _lang = LANGS[(LANGS.indexOf(_lang) + 1) % LANGS.length];
  localStorage.setItem('tokoDropLang', _lang);
  return _lang;
}

export function t(key, ...args) {
  const table = STRINGS[_lang] || STRINGS.en;
  let v = table[key];
  if (v === undefined) v = STRINGS.en[key];
  if (v === undefined) return key;
  return typeof v === 'function' ? v(...args) : v;
}
