// Lightweight i18n for Toko Drop. Localizes the DOM-overlay UI (title, controls,
// death screen, feedback panel, wave banner). The on-canvas HUD and the
// roguelike upgrade cards intentionally stay English (canvas monospace fonts
// render CJK unreliably and the HUD layout is space-tight).
//
// t(key, ...args) returns the string for the active language, falling back to
// English for any missing key. Values may be plain strings or functions (for
// templated strings that interpolate a runtime label).

const STRINGS = {
  en: {
    subtitle: 'TWIN-STICK BULLET-HELL',
    best: 'BEST', pts: 'PTS', wave: 'WAVE',
    tapStart: 'TAP OR PRESS SPACE TO START',
    ctrlMove: 'Move',        ctrlMoveH: 'left stick / WASD',
    ctrlAim: 'Aim & fire',   ctrlAimH: 'right stick / hold LMB',
    ctrlDash: 'Dash',        ctrlDashH: 'A / bumper / Space',
    ctrlPause: 'Pause',      ctrlPauseH: 'Start / ESC',
    ctrlEyes: 'Eyes',        ctrlEyesH: 'E',
    orientation: 'ORIENTATION', landscape: 'LANDSCAPE', portrait: 'PORTRAIT',
    orientLandH: 'Wide arena — Steam Deck / sideways mobile',
    orientPortH: 'Tall arena — upright mobile',
    rogue: 'ROGUELIKE MODE', on: 'ON', off: 'OFF',
    rogueOnH: 'A: upgrade cards every 3rd wave',
    rogueBH: 'B: cards + rare BONUS GAUNTLET runs (big multipliers)',
    rogueOffH: 'No upgrades — pure arcade survival',
    daily: 'DAILY RUN',
    dailyOnH: "Everyone plays today's seed — compare scores",
    dailyOffH: 'Random seed every run',
    dailyBest: 'DAILY BEST',
    lbTitle: 'DAILY TOP 10',
    lbPost: 'POST SCORE', lbPosted: 'POSTED ✓',
    lbNone: 'No scores yet today — be first!',
    language: 'LANGUAGE',
    volume: 'VOLUME', annVolume: 'ANNOUNCER VOL.', reduceMotion: 'REDUCE MOTION',
    reduceMotionOnH: 'No camera shake', reduceMotionOffH: 'Full screen-shake feedback',
    settings: 'SETTINGS', settingsHint: 'Settings are in the pause menu (⏸)',
    options: 'OPTIONS',
    smashTV: 'SMASH TV MODE',
    smashOnH: 'Enemies rush from 4 doors, bigger waves, more prizes — from the next wave',
    smashOffH: 'Standard waves surround the arena',
    announcer: 'ANNOUNCER',
    annOnH: 'Loud game-show commentary (spoken, English)',
    annOffH: 'No commentary',
    graze: 'GRAZE',
    testMode: 'TEST MODE',
    testOnH: 'All enemies from wave 1 — no records kept',
    testOffH: 'Normal progression',
    pixelMode: 'PIXEL PREVIEW',
    pixelOnH: 'Chunky retro rendering (arcade tribute look, WIP)',
    pixelOffH: 'Modern rendering',
    introVoice: 'INTRO VOICE',
    introOnH: 'Recorded title shout ("TOKO DROP!")',
    introOffH: 'Silent title screen',
    perfMode: 'PERFORMANCE MODE',
    perfOnH: 'Lower resolution, no glass or shadows — for slower phones', perfOffH: 'Full visual quality',
    runHistory: 'RUN HISTORY', noRuns: 'No runs yet — play one!',
    rhScore: 'SCORE', rhWave: 'WAVE', rhTime: 'TIME', rhMode: 'MODE', close: 'CLOSE',
    youDied: 'YOU DIED',
    bestScore: '★ BEST SCORE', bestTime: '★ BEST TIME', bestWave: '★ BEST WAVE',
    seed: 'SEED',
    fbEnjoy: 'WHAT DID YOU ENJOY?  (optional)',
    fbWrong: 'WHAT WENT WRONG?  (optional)',
    fbElse: 'Anything else? (optional)',
    fbSend: 'SEND & CONTINUE', fbContinue: 'CONTINUE', fbSkip: 'SKIP',
    fbShare: 'SHARE', fbCopied: 'COPIED!',
    likeWeapons: 'The weapon pods', likeBosses: 'Boss fights',
    likeFeel: 'Movement / dash feel', likeDodging: 'Bullet-hell dodging',
    likeVariety: 'Enemy variety', likeVibe: 'Visuals / vibe',
    likeRooms: 'Room-to-room doors', likeLoot: 'Cash & prizes',
    likeGraze: 'Close-call grazes',
    fbTooFast: 'Enemies / bullets too fast', fbUnfair: 'Felt unfair / cheap',
    fbUnclear: "Couldn't read the threat",
    fbHit: (l) => `${l} hit me too often`,
    fbMany: (l) => `Too many ${l}s at once`,
    fbDash: 'Dash was on cooldown',
    fbBullets: 'Too many bullets onscreen',
    fbBlender: 'Got swarmed all at once',
    fbWarden: 'Wardens blocked my shots',
    fbDoors: 'Room exits confused me',
    hudStreak: 'STREAK', hudShld: 'SHLD', hudHi: 'HI', hudScoreMult: 'SCORE',
    chooseUpgrade: 'CHOOSE UPGRADE',
    chooseRare: 'CHOOSE RARE UPGRADE',
    g_t1: 'BONUS GAUNTLET', g_t1_d: '4 rooms + a boss. Rising score multiplier. Clear it → a RARE upgrade. Death is death.',
    g_t2: 'GAUNTLET TIER 2', g_t2_d: '2 brutal rooms, a boss, then a MEGA boss. Bigger multiplier, same rules.',
    c_r_hp: 'Iron Heart',      c_r_hp_d: '+2 HP.',
    c_r_rate: 'Overdrive',     c_r_rate_d: 'Fire 40% faster permanently.',
    c_r_speed: 'Mercury Soles',c_r_speed_d: 'Move 40% faster permanently.',
    c_r_pierce: 'Lance Rounds',c_r_pierce_d: 'Piercing + 30% bigger bullets.',
    c_hp: '+1 HP',                  c_hp_d: 'Gain one extra hit point.',
    c_speed: 'Speed Up',            c_speed_d: 'Move 20% faster permanently.',
    c_firerate: 'Fire Rate Up',     c_firerate_d: 'Fire 20% faster permanently.',
    c_bigbullets: 'Bigger Bullets', c_bigbullets_d: 'Player bullets are 30% larger.',
    c_dashcd: 'Dash Refresh',       c_dashcd_d: 'Dash cooldown −0.15 s.',
    c_nuke: 'Nuke',                 c_nuke_d: 'Clear all enemy bullets now.',
    c_pierce: 'Pierce',             c_pierce_d: 'Bullets pass through enemies.',
    c_magnet: 'Magnet',             c_magnet_d: 'Pickups drift toward you.',
    c_shield: 'Shield',             c_shield_d: 'Absorbs one hit; resets each wave.',
    c_dashboom: 'Dash Boom',        c_dashboom_d: 'Radial explosion on every dash.',
  },
  ja: {
    subtitle: 'ツインスティック弾幕',
    best: 'ベスト', pts: '点', wave: 'ウェーブ',
    tapStart: 'タップまたはスペースでスタート',
    ctrlMove: '移動',          ctrlMoveH: '左スティック / WASD',
    ctrlAim: '照準＆射撃',      ctrlAimH: '右スティック / 左クリック長押し',
    ctrlDash: 'ダッシュ',       ctrlDashH: 'A / バンパー / スペース',
    ctrlPause: 'ポーズ',        ctrlPauseH: 'スタート / ESC',
    ctrlEyes: '目',             ctrlEyesH: 'E',
    orientation: '画面の向き', landscape: '横', portrait: '縦',
    orientLandH: '横長アリーナ — Steam Deck / 横向きモバイル',
    orientPortH: '縦長アリーナ — 縦向きモバイル',
    rogue: 'ローグライク', on: 'オン', off: 'オフ',
    rogueOnH: 'A：3ウェーブごとにアップグレード',
    rogueBH: 'B：カード + レアなボーナスガントレット（高倍率）',
    rogueOffH: 'アップグレードなし — 純粋なアーケード',
    daily: 'デイリーラン',
    dailyOnH: '今日は全員同じシード — スコアで勝負',
    dailyOffH: '毎回ランダムシード',
    dailyBest: 'デイリーベスト',
    lbTitle: 'デイリーTOP10',
    lbPost: 'スコア送信', lbPosted: '送信済み ✓',
    lbNone: 'まだ記録なし — 一番乗りしよう！',
    language: '言語',
    volume: '音量', annVolume: 'アナウンサー音量', reduceMotion: '手ぶれ軽減',
    reduceMotionOnH: 'カメラ揺れなし', reduceMotionOffH: '画面揺れ演出あり',
    settings: '設定', settingsHint: '設定はポーズメニューにあります（⏸）',
    options: 'オプション',
    smashTV: 'SMASH TVモード',
    smashOnH: '敵が4つの扉から突入、ウェーブ増強、賞品も増加 — 次のウェーブから',
    smashOffH: '通常ウェーブ（全方向から出現）',
    announcer: 'アナウンサー',
    annOnH: 'にぎやかな実況コメント（音声・英語）',
    annOffH: '実況なし',
    graze: 'かすり',
    testMode: 'テストモード',
    testOnH: '全敵がウェーブ1から登場 — 記録は残らない',
    testOffH: '通常の進行',
    pixelMode: 'ピクセルプレビュー',
    pixelOnH: 'レトロなドット描画（アーケード風・開発中）',
    pixelOffH: '通常の描画',
    introVoice: 'イントロ音声',
    introOnH: 'タイトルの録音ボイス（「TOKO DROP!」）',
    introOffH: 'タイトルは無音',
    perfMode: '軽量モード',
    perfOnH: '低解像度・ガラス効果と影なし（低速端末向け）', perfOffH: 'フル画質',
    runHistory: 'プレイ履歴', noRuns: 'まだ記録がありません — プレイしよう！',
    rhScore: 'スコア', rhWave: 'ウェーブ', rhTime: 'タイム', rhMode: 'モード', close: '閉じる',
    youDied: 'ゲームオーバー',
    bestScore: '★ ベストスコア', bestTime: '★ ベストタイム', bestWave: '★ ベストウェーブ',
    seed: 'シード',
    fbEnjoy: '良かった点は？（任意）',
    fbWrong: '悪かった点は？（任意）',
    fbElse: 'その他（任意）',
    fbSend: '送信して続行', fbContinue: '続行', fbSkip: 'スキップ',
    fbShare: '共有', fbCopied: 'コピーしました',
    likeWeapons: '武器ポッド', likeBosses: 'ボス戦',
    likeFeel: '操作感／ダッシュ', likeDodging: '弾幕回避',
    likeVariety: '敵のバリエーション', likeVibe: 'ビジュアル／雰囲気',
    likeRooms: '部屋から部屋への移動', likeLoot: '現金と賞品',
    likeGraze: 'かすり回避',
    fbTooFast: '敵／弾が速すぎる', fbUnfair: '理不尽に感じた',
    fbUnclear: '脅威が見づらい',
    fbHit: (l) => `${l}に撃たれすぎた`,
    fbMany: (l) => `${l}が一度に多すぎた`,
    fbDash: 'ダッシュがクールダウン中だった',
    fbBullets: '画面上の弾が多すぎた',
    fbBlender: '一度に群がられた',
    fbWarden: 'ワーデンに弾を防がれた',
    fbDoors: '部屋の出口が分かりづらい',
    hudStreak: '連続', hudShld: 'シールド', hudHi: 'ハイ', hudScoreMult: 'スコア',
    chooseUpgrade: 'アップグレードを選択',
    chooseRare: 'レア強化を選択',
    g_t1: 'ボーナスガントレット', g_t1_d: '4部屋＋ボス。スコア倍率が上昇。クリアでレア強化。死は死。',
    g_t2: 'ガントレット第2層', g_t2_d: '過酷な2部屋＋ボス＋メガボス。倍率アップ、ルールは同じ。',
    c_r_hp: 'アイアンハート',   c_r_hp_d: 'HP +2',
    c_r_rate: 'オーバードライブ', c_r_rate_d: '発射速度が永久に40%上昇',
    c_r_speed: '水銀の靴',      c_r_speed_d: '移動速度が永久に40%上昇',
    c_r_pierce: 'ランス弾',     c_r_pierce_d: '貫通＋弾が30%拡大',
    c_hp: 'HP +1',             c_hp_d: 'ヒットポイントを1つ追加',
    c_speed: 'スピードアップ',   c_speed_d: '移動速度が永久に20%上昇',
    c_firerate: '連射アップ',    c_firerate_d: '発射速度が永久に20%上昇',
    c_bigbullets: '弾の拡大',    c_bigbullets_d: 'プレイヤーの弾が30%大きくなる',
    c_dashcd: 'ダッシュ回復',    c_dashcd_d: 'ダッシュのクールダウン −0.15秒',
    c_nuke: 'ニューク',          c_nuke_d: '敵弾をすべて消す',
    c_pierce: '貫通',            c_pierce_d: '弾が敵を貫通する',
    c_magnet: 'マグネット',      c_magnet_d: 'アイテムが引き寄せられる',
    c_shield: 'シールド',        c_shield_d: '1発を防ぐ。ウェーブごとに回復',
    c_dashboom: 'ダッシュ爆発',  c_dashboom_d: 'ダッシュのたびに放射状に爆発',
  },
  fi: {
    subtitle: 'KAKSITIKKU-LUOTIHELVETTI',
    best: 'PARAS', pts: 'PIST.', wave: 'AALTO',
    tapStart: 'NAPAUTA TAI PAINA VÄLILYÖNTIÄ',
    ctrlMove: 'Liiku',          ctrlMoveH: 'vasen tatti / WASD',
    ctrlAim: 'Tähtää & ammu',   ctrlAimH: 'oikea tatti / pidä LMB',
    ctrlDash: 'Syöksy',         ctrlDashH: 'A / olkanäppäin / väli',
    ctrlPause: 'Tauko',         ctrlPauseH: 'Start / ESC',
    ctrlEyes: 'Silmät',         ctrlEyesH: 'E',
    orientation: 'SUUNTA', landscape: 'VAAKA', portrait: 'PYSTY',
    orientLandH: 'Leveä areena — Steam Deck / vaakamobiili',
    orientPortH: 'Korkea areena — pystymobiili',
    rogue: 'ROGUELIKE-TILA', on: 'PÄÄLLÄ', off: 'POIS',
    rogueOnH: 'A: päivityskortit joka 3. aallossa',
    rogueBH: 'B: kortit + harvinaiset BONUS-haasteet (isot kertoimet)',
    rogueOffH: 'Ei päivityksiä — pelkkää arcade-selviytymistä',
    daily: 'PÄIVÄN HAASTE',
    dailyOnH: 'Kaikki pelaavat päivän siementä — vertaa pisteitä',
    dailyOffH: 'Satunnainen siemen joka pelillä',
    dailyBest: 'PÄIVÄN PARAS',
    lbTitle: 'PÄIVÄN TOP 10',
    lbPost: 'LÄHETÄ TULOS', lbPosted: 'LÄHETETTY ✓',
    lbNone: 'Ei vielä tuloksia tänään — ole ensimmäinen!',
    language: 'KIELI',
    volume: 'ÄÄNENVOIMAKKUUS', annVolume: 'KUULUTTAJAN ÄÄNI', reduceMotion: 'VÄHENNÄ LIIKETTÄ',
    reduceMotionOnH: 'Ei kameran tärinää', reduceMotionOffH: 'Täysi ruudun tärinä',
    settings: 'ASETUKSET', settingsHint: 'Asetukset ovat taukovalikossa (⏸)',
    options: 'VALINNAT',
    smashTV: 'SMASH TV -TILA',
    smashOnH: 'Viholliset ryntäävät 4 ovesta, isommat aallot, enemmän palkintoja — seuraavasta aallosta',
    smashOffH: 'Tavalliset aallot saartavat areenan',
    announcer: 'SELOSTAJA',
    annOnH: 'Äänekäs peliohjelmaselostus (puhuttu, englanniksi)',
    annOffH: 'Ei selostusta',
    graze: 'HIPAISU',
    testMode: 'TESTITILA',
    testOnH: 'Kaikki viholliset aallosta 1 — ei tallenteita',
    testOffH: 'Normaali eteneminen',
    pixelMode: 'PIKSELIESIKATSELU',
    pixelOnH: 'Rakeinen retrokuva (arcade-kunnianosoitus, kesken)',
    pixelOffH: 'Moderni kuva',
    introVoice: 'INTRO-ÄÄNI',
    introOnH: 'Nauhoitettu aloitushuuto ("TOKO DROP!")',
    introOffH: 'Hiljainen aloitusruutu',
    perfMode: 'SUORITUSKYKYTILA',
    perfOnH: 'Matalampi resoluutio, ei lasiefektejä eikä varjoja — hitaille puhelimille', perfOffH: 'Täysi kuvanlaatu',
    runHistory: 'PELIHISTORIA', noRuns: 'Ei vielä pelejä — pelaa yksi!',
    rhScore: 'PISTEET', rhWave: 'AALTO', rhTime: 'AIKA', rhMode: 'TILA', close: 'SULJE',
    youDied: 'KUOLIT',
    bestScore: '★ PARAS PISTEMÄÄRÄ', bestTime: '★ PARAS AIKA', bestWave: '★ PARAS AALTO',
    seed: 'SIEMEN',
    fbEnjoy: 'MISTÄ PIDIT?  (valinnainen)',
    fbWrong: 'MIKÄ MENI PIELEEN?  (valinnainen)',
    fbElse: 'Jotain muuta? (valinnainen)',
    fbSend: 'LÄHETÄ & JATKA', fbContinue: 'JATKA', fbSkip: 'OHITA',
    fbShare: 'JAA', fbCopied: 'KOPIOITU!',
    likeWeapons: 'Asepodit', likeBosses: 'Pomotaistelut',
    likeFeel: 'Liike / syöksy', likeDodging: 'Luotien väistely',
    likeVariety: 'Vihollisten kirjo', likeVibe: 'Visuaalit / tunnelma',
    likeRooms: 'Huoneesta huoneeseen -ovet', likeLoot: 'Käteinen ja palkinnot',
    likeGraze: 'Täpärät väistöt',
    fbTooFast: 'Viholliset / luodit liian nopeita', fbUnfair: 'Tuntui epäreilulta',
    fbUnclear: 'Uhkaa ei voinut lukea',
    fbHit: (l) => `${l} osui liian usein`,
    fbMany: (l) => `Liikaa ${l}-vihollisia kerralla`,
    fbDash: 'Syöksy oli jäähdyllä',
    fbBullets: 'Liikaa luoteja ruudulla',
    fbBlender: 'Jäin joukon saartamaksi',
    fbWarden: 'Wardenit torjuivat laukaukseni',
    fbDoors: 'Huoneiden uloskäynnit sekoittivat',
    hudStreak: 'PUTKI', hudShld: 'KILPI', hudHi: 'HI', hudScoreMult: 'PISTEET',
    chooseUpgrade: 'VALITSE PÄIVITYS',
    chooseRare: 'VALITSE HARVINAINEN PÄIVITYS',
    g_t1: 'BONUS-HAASTE', g_t1_d: '4 huonetta + pomo. Nouseva pistekerroin. Läpäisystä HARVINAINEN päivitys. Kuolema on kuolema.',
    g_t2: 'HAASTE, TASO 2', g_t2_d: '2 raakaa huonetta, pomo ja MEGA-pomo. Isompi kerroin, samat säännöt.',
    c_r_hp: 'Rautasydän',      c_r_hp_d: 'HP +2.',
    c_r_rate: 'Ylikierrokset', c_r_rate_d: 'Ammu pysyvästi 40% nopeammin.',
    c_r_speed: 'Elohopeapohjat', c_r_speed_d: 'Liiku pysyvästi 40% nopeammin.',
    c_r_pierce: 'Peitsiluodit', c_r_pierce_d: 'Läpäisy + 30% isommat luodit.',
    c_hp: 'HP +1',                  c_hp_d: 'Yksi ylimääräinen osumapiste.',
    c_speed: 'Nopeus +',            c_speed_d: 'Liiku pysyvästi 20% nopeammin.',
    c_firerate: 'Tulinopeus +',     c_firerate_d: 'Ammu pysyvästi 20% nopeammin.',
    c_bigbullets: 'Isommat luodit', c_bigbullets_d: 'Pelaajan luodit 30% suuremmat.',
    c_dashcd: 'Syöksyn lataus',     c_dashcd_d: 'Syöksyn jäähtyminen −0,15 s.',
    c_nuke: 'Ydinisku',             c_nuke_d: 'Tyhjennä kaikki vihollisluodit.',
    c_pierce: 'Läpäisy',            c_pierce_d: 'Luodit läpäisevät viholliset.',
    c_magnet: 'Magneetti',          c_magnet_d: 'Poiminnat ajautuvat luoksesi.',
    c_shield: 'Kilpi',              c_shield_d: 'Vaimentaa yhden osuman; nollautuu aallottain.',
    c_dashboom: 'Syöksyräjähdys',   c_dashboom_d: 'Säteittäinen räjähdys joka syöksyllä.',
  },
};

const LANGS       = ['en', 'ja', 'fi'];
const LANG_LABELS = { en: 'ENG', ja: '日本語', fi: 'SUOMI' };

let _lang = localStorage.getItem('tokoDropLang') || 'en';
if (!LANGS.includes(_lang)) _lang = 'en';

export function getLang()   { return _lang; }
export function langLabel() { return LANG_LABELS[_lang]; }

// All selectable languages as {code, label} — for rendering a picker.
export function langs() {
  return LANGS.map(code => ({ code, label: LANG_LABELS[code] }));
}

// Set the active language directly and persist it.
export function setLang(code) {
  if (LANGS.includes(code)) {
    _lang = code;
    localStorage.setItem('tokoDropLang', _lang);
  }
  return _lang;
}

// Advance to the next language (EN → JA → FI → EN) and persist the choice.
export function cycleLang() {
  _lang = LANGS[(LANGS.indexOf(_lang) + 1) % LANGS.length];
  localStorage.setItem('tokoDropLang', _lang);
  return _lang;
}

export function t(key, ...args) {
  const table = STRINGS[_lang] || STRINGS.en;
  let v = table[key];
  if (v === undefined) v = STRINGS.en[key];
  if (v === undefined) return key;
  return typeof v === 'function' ? v(...args) : v;
}
