import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=p=>fs.readFileSync(new URL(p,import.meta.url),'utf8');
const html=read('../index.html'),runtime=read('../js/main-v211.js'),versions=read('../VERSIONS.md'),hub=JSON.parse(read('../../hub/versions.json'));
const top=versions.match(/^## v([^\s]+) —/m)?.[1];
assert.ok(top,'VERSIONS.md has a top version');
assert.match(html,new RegExp(`class="versionHero"[\\s\\S]*?v${top.replace('.','\\.')}`),'opening screen shows top version prominently');
assert.match(runtime,new RegExp(`BUILD_VERSION=['"]${top.replace('.','\\.')}['"]`),'runtime entry version matches VERSIONS.md');
assert.equal(hub.tokomove?.v,top,'hub version matches VERSIONS.md');
const[major,minor='0']=top.split('.');assert.equal(hub.tokomove?.n,Number(major)*1000+Number(minor),'hub numeric version matches visible version');
assert.match(html,/main-v211\.js/,'public page loads v2.11 runtime entry');
assert.match(runtime,/route-choice\.js/,'v2.11 runtime includes route-choice guidance');
console.log(`Toko Move version sync: v${top}`);