export const LOOKS = [
  {
    id: "suds",
    title: "Suds Jack",
    where: "Arcade floor",
    use: "Behind the hub header and cabinet marquees. Leave the playfields alone.",
    grade: "linear-gradient(160deg, #06070a, #0c3330 55%, #12302a)",
    layers: [
      { type: "MeshGradient", props: { colorA: "#06070a", colorB: "#35e8d8", count: 4, swirl: 0.4, drift: 0.45 } },
      { type: "Grid", props: { color: "#35e8d8", cells: 16, thickness: 0.22, opacity: 0.38 } },
      { type: "CRTScreen", props: { pixelSize: 110, scanlineIntensity: 0.32, vignetteIntensity: 0.55 } },
      { type: "Vignette", props: { color: "#06070a", intensity: 0.75, radius: 0.5 } },
    ],
  },
  {
    id: "toko",
    title: "Toko Drop",
    where: "Title and death",
    use: "Gel field on the browser title and the death card. The Godot port keeps its own materials.",
    grade: "radial-gradient(circle at 50% 60%, #146b4a, #04140f 70%)",
    layers: [
      { type: "RadialGradient", props: { colorA: "#1c7a56", colorB: "#04140f", radius: 0.85 } },
      { type: "Blob", props: { colorA: "#c8ffe8", colorB: "#146b4a", size: 0.72, softness: 0.45, speed: 0.55 } },
      { type: "Goo", props: { gooColor: "#8dffe4", translucency: 0.62, scale: 0.92, speed: 0.35, wetness: 0.7 } },
    ],
  },
  {
    id: "kindling",
    title: "Kindling",
    where: "Menu fire",
    use: "The keeper menu and the pause veil. Not the bonfire simulation itself.",
    grade: "linear-gradient(#ff6a1a, #1a0904 70%)",
    layers: [
      { type: "LinearGradient", props: { colorA: "#1a0904", colorB: "#ff6a1a", angle: 100 } },
      { type: "Godrays", props: { rayColor: "#ffb25a", backgroundColor: "#140804", center: { x: 0.5, y: 0.92 }, intensity: 0.6, speed: 0.3 } },
      { type: "Smoke", props: { colorA: "#3a1a10", colorB: "#ff9a55", intensity: 0.4 } },
      { type: "FilmGrain", props: { strength: 0.28, animated: true } },
    ],
  },
  {
    id: "dagger",
    title: "Hyper Dagger",
    where: "Title card",
    use: "Void, dried blood, and bone on the browser title. Not a gameplay post stack.",
    grade: "linear-gradient(180deg, #12080a, #070608)",
    layers: [
      { type: "FlowingGradient", props: { colorA: "#070608", colorB: "#6b1d24", colorC: "#cfc6b8", colorD: "#12080a" } },
      { type: "Hologram", props: { color: "#d7d0c4", scanlines: 0.5, brightness: 0.32 } },
      { type: "ChromaticAberration", props: { strength: 0.22 } },
      { type: "Vignette", props: { color: "#070608", intensity: 1, radius: 0.38 } },
    ],
  },
  {
    id: "eeri",
    title: "Eeri",
    where: "World card",
    use: "Paper grade on the world-select card. The level itself stays drawn, not filtered.",
    grade: "linear-gradient(160deg, #f3ead8, #b7a27a)",
    layers: [
      { type: "LinearGradient", props: { colorA: "#f3ead8", colorB: "#b7a27a", angle: 160 } },
      { type: "Paper", props: { roughness: 0.65, grainScale: 1.15 } },
      { type: "Watercolor", props: { strength: 0.5, bleed: 0.4, paperColor: "#f3ead8" } },
      { type: "Halftone", props: { frequency: 26, paperColor: "#f3ead8", angle: 18 } },
    ],
  },
  {
    id: "piritori",
    title: "Piritori Eden",
    where: "Chapter card",
    use: "Kallio, 2003, on the chapter card. The Godot scene does not get this grade.",
    grade: "linear-gradient(#e4d3b0, #1a120c)",
    layers: [
      { type: "Duotone", props: { colorA: "#1a120c", colorB: "#e4d3b0", blend: 0.48 } },
      { type: "VHS", props: { wobble: 0.32, scanlineNoise: 0.4, smear: 0.18 } },
      { type: "FilmGrain", props: { strength: 0.48, animated: true } },
      { type: "Vignette", props: { color: "#0c0907", radius: 0.4, intensity: 0.95 } },
    ],
  },
  {
    id: "skltr",
    title: "Skltr",
    where: "Cover",
    use: "The cover and the attract loop. Strip it before the first shot.",
    grade: "linear-gradient(140deg, #120014, #ff3d9a)",
    layers: [
      { type: "Plasma", props: { colorA: "#120014", colorB: "#ff3d9a", speed: 0.55, intensity: 0.8 } },
      { type: "Glitch", props: { intensity: 0.26, speed: 0.65, rgbShift: 0.3 } },
      { type: "ChromaticAberration", props: { strength: 0.38 } },
      { type: "Dither", props: { pixelSize: 2.5, colorA: "#120014", colorB: "#ff7ab8" } },
    ],
  },
  {
    id: "voxel",
    title: "Voxel",
    where: "Attract mode",
    use: "Hex floor on the attract screen. The first-person view stays unfiltered.",
    grade: "linear-gradient(#0e1612, #143028)",
    layers: [
      { type: "HexGrid", props: { colorA: "#0e1612", colorB: "#39e6a0", cells: 8, thickness: 1.1, softness: 0.12 } },
      { type: "Dither", props: { pixelSize: 3, colorA: "#0e1612", colorB: "#8dffc4" } },
      { type: "Obsidian", props: { bodyColor: "#101816", colorA: "#35e8d8", colorB: "#b8ffe0", iridescence: 0.5, scale: 0.7 } },
    ],
  },
];
