import * as T from './vendor/three.module.min.js?v=185';
export function createEffects(scene,mobile){
 const count=mobile?96:256,positions=new Float32Array(count*3),sizes=new Float32Array(count),tiles=new Float32Array(count),alphas=new Float32Array(count);const particles=Array.from({length:count},()=>({life:0,total:1,v:new T.Vector3()}));let cursor=0,dustTimer=0;
 const geometry=new T.BufferGeometry();geometry.setAttribute('position',new T.BufferAttribute(positions,3));geometry.setAttribute('size',new T.BufferAttribute(sizes,1));geometry.setAttribute('tile',new T.BufferAttribute(tiles,1));geometry.setAttribute('alpha',new T.BufferAttribute(alphas,1));
 const texture=new T.TextureLoader().load(new URL('./assets/textures/effects.png?v=2',import.meta.url).href);const material=new T.ShaderMaterial({uniforms:{atlas:{value:texture}},vertexShader:`attribute float size;attribute float tile;attribute float alpha;varying float vTile;varying float vAlpha;void main(){vec4 p=modelViewMatrix*vec4(position,1.);gl_Position=projectionMatrix*p;gl_PointSize=clamp(size*600./max(1.,-p.z),1.,64.);vTile=tile;vAlpha=alpha;}`,fragmentShader:`uniform sampler2D atlas;varying float vTile;varying float vAlpha;void main(){vec2 uv=vec2((gl_PointCoord.x+vTile)/4.,gl_PointCoord.y);vec4 c=texture2D(atlas,uv);gl_FragColor=vec4(c.rgb,c.a*vAlpha);}`,transparent:true,depthWrite:false,toneMapped:false});const points=new T.Points(geometry,material);points.frustumCulled=false;scene.add(points);
 function emit(position,tile,velocity,life,size){const i=cursor++%count;positions.set([position.x,position.y,position.z],i*3);particles[i].v.copy(velocity);particles[i].life=particles[i].total=life;sizes[i]=size;tiles[i]=tile;alphas[i]=1}
 function burst(position,n,spark=false){for(let j=0;j<Math.min(n,mobile?12:24);j++){emit(position,spark?1:2,new T.Vector3((Math.random()-.5)*(spark?4:2),Math.random()*(spark?3:1.3),(Math.random()-.5)*3),.35+Math.random()*.4,spark?.085:.35)}}
 function update(dt,position,speed,air,angle){dustTimer+=dt;if(!air&&speed>3&&dustTimer>.065){dustTimer=0;emit(position,speed>10?3:0,new T.Vector3(-Math.sin(angle)*speed*.3,.25,-Math.cos(angle)*speed*.3),speed>10?.22:.5,speed>10?.2:.18)}for(let i=0;i<count;i++){const p=particles[i];if(p.life>0){p.life-=dt;p.v.y-=dt*(tiles[i]===1?7:1);positions[i*3]+=p.v.x*dt;positions[i*3+1]+=p.v.y*dt;positions[i*3+2]+=p.v.z*dt;alphas[i]=Math.max(0,p.life/p.total)}else alphas[i]=0}for(const a of Object.values(geometry.attributes))a.needsUpdate=true}
 return {burst,update,dispose(){points.removeFromParent();geometry.dispose();material.dispose();texture.dispose()}};
}
