import {createGame} from './skate.js?v=5';
const $=id=>document.getElementById(id);let running=false,ended=false,game;
function activate(el,fn){let last=-Infinity;const fire=e=>{if(e.type==='touchend')e.preventDefault();if(performance.now()-last<300)return;last=performance.now();fn()};el.addEventListener('pointerup',fire);el.addEventListener('touchend',fire,{passive:false});el.addEventListener('click',e=>{if(e.detail===0)fn()})}
try{game=createGame($('world'),h=>{for(const k of ['score','best','speed','device'])$(k).textContent=k==='speed'?Math.round(h.speed*3.6):k==='device'?h[k]:Math.floor(h[k]).toLocaleString();$('time').textContent=`${Math.floor(h.time/60)}:${Math.floor(h.time%60).toString().padStart(2,'0')}`;$('timebar').style.width=`${h.time/120*100}%`;$('combo-label').textContent=h.combo?'CURRENT COMBO':'FIND YOUR NEXT LINE';$('combo').textContent=h.combo?`${Math.floor(h.combo)} × ${h.mult}`:'';$('trick-name').textContent=h.trick;if(h.ended&&!ended){ended=true;running=false;$('intro').hidden=false;$('trick').hidden=true;$('touch').hidden=true;$('title').innerHTML='SESSION<br>COMPLETE.';$('message').textContent=`${h.score.toLocaleString()} points. One more run?`;$('start').textContent='RUN IT BACK ↗'}});game.ready.finally(()=>{$('start').disabled=false;$('start').textContent='DROP IN ↗'})}catch(e){$('support').textContent='WebGL could not start. Enable hardware acceleration and reload.';console.error(e)}
activate($('start'),()=>{if(!game)return;game.start();running=true;ended=false;$('intro').hidden=true;$('touch').hidden=false;$('trick').hidden=false});
function help(){game?.pause(true);$('controls').showModal()}activate($('help'),help);activate($('footer-help'),help);activate($('resume'),()=>$('controls').close());$('controls').addEventListener('close',()=>game?.pause(false));
for(const el of document.querySelectorAll('[data-key]')){el.addEventListener('pointerdown',e=>{e.preventDefault();el.setPointerCapture(e.pointerId);game?.key(el.dataset.key,true)});for(const event of ['pointerup','pointercancel','lostpointercapture'])el.addEventListener(event,()=>game?.key(el.dataset.key,false))}
for(const [id,look] of [['move-stick',false],['look-stick',true]]){const el=$(id);const move=e=>{const r=el.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;if(look)game?.look(x*2-1,y*2-1);else game?.stick(x*120,y*120)};el.addEventListener('pointerdown',e=>{e.preventDefault();el.setPointerCapture(e.pointerId);move(e)});el.addEventListener('pointermove',e=>{if(el.hasPointerCapture(e.pointerId))move(e)});for(const ev of ['pointerup','pointercancel','lostpointercapture'])el.addEventListener(ev,()=>{if(look)game?.look(0,0);else game?.stick(60,60)})}
// Start from a controller without requiring a mouse to dismiss the title screen.
let wasStart=false;function menuPad(){const pad=Array.from(navigator.getGamepads?.()||[]).find(p=>p?.connected),pressed=!!pad?.buttons[0]?.pressed;if(pressed&&!wasStart&&!running&&!$('controls').open)$('start').click();wasStart=pressed;requestAnimationFrame(menuPad)}requestAnimationFrame(menuPad);
