// KUOPPA's words, joined onto the Pajatso table (../classic/lang.js). English
// is the source; the Finnish and Japanese are drafts in the same register.
import { extend } from '../classic/lang.js?v=4';

extend({
  en: {
    kSub: 'The roguelike · a Pajatso with a debt on it',
    kIntro1: 'The house hands you <b>{n} coins</b> a round to shoot. Whatever the machine pays goes in your <b>purse</b>.',
    kIntro2: 'Every third round a <b>debt</b> is due out of the purse. Pay it and the next <b>pachinko part</b> is bolted onto the machine. Miss it and the floor opens.',
    kIntro3: 'Between rounds the vendor sells <b>charms</b> that bend the machine. Eight locks on the door.',
    kPlay: 'START THE RUN', kBase: 'PAJATSO — the base machine ›', kOldPit: 'the old pit (v1) ›',
    purse: 'Purse', left: 'Coins', roundWord: 'Round', debtIs: 'Debt {d}/8', roundIs: 'Round {r}/{n}',
    shopTitle: 'THE VENDOR', shopSub: 'Round {r} of {n} next · {debt} mk due after round {n}',
    buy: 'BUY · {p} mk', sold: 'SOLD', mine: 'Your charms {n}/{max}', none: 'none yet',
    reroll: 'ANOTHER LOOK · {p} mk', next: 'NEXT ROUND — {n} COINS',
    dueTitle: 'THE DEBT IS DUE', dueSub: 'Lock {d} of 8 wants <b>{debt} mk</b>. Your purse holds <b>{coins} mk</b>.', pay: 'PAY {debt} mk', cantPay: 'YOU CANNOT PAY',
    paidTitle: 'LOCK {d} OPENS', bolted: 'Bolted onto the machine:',
    fellTitle: 'THE FLOOR OPENS', fellSub: 'You were <b>{short} mk</b> short at lock {d}.',
    wonTitle: 'THE DOOR OPENS', wonSub: 'Eight locks, eight debts paid. The pit lets you go.',
    again: 'ANOTHER RUN', rsLocks: 'Locks opened', rsEarned: 'Earned', rsPotti: '★ POTTI', rsSpins: 'Spins', rsSevens: 'Sevens', rsCharms: 'Charms',
    reach: 'REACH!', clover: '+{n} coins to shoot', mask: 'THE MASK takes {n} mk', feverOn: 'FEVER!', feverSub: 'the gate on the right is open for {n} coins — shoot right',
    feverOff: 'FEVER over', chance: 'CHANCE', chanceSub: 'sevens come three times as often for {n} spins',
    x3: '+{n} coins to shoot', held: 'spin', interest: 'interest +{n} mk', roundOver: 'ROUND OVER', lcdIdle: 'PULL THE LEVER', lcdShop: 'THE VENDOR', lcdDue: 'PAY THE DEBT',
    part_chucker: 'Start chucker & reels', part_tulips: 'Tulips', part_fever: 'FEVER gate', part_windmills: 'Windmills', part_chain: 'Chain jackpots', part_multiplier: 'Ball multipliers',
    partText_chucker: 'A START pocket in the nails. A coin in it spins three reels: a line of cherries, bells, coins or sevens pays; clovers hand you coins; later, a line of masks takes from your purse.',
    partText_tulips: 'The two 1:00 windows are tulips now. A coin in one opens its petals wide; the next coin in shuts it.',
    partText_fever: 'A jackpot — a line of sevens, or the POTTI — opens the gate under the right half of the windows. While FEVER lasts, every coin that misses a window there pays 2 mk. Shoot right.',
    partText_windmills: 'Two windmills turn in the nails beside the chucker, throwing coins where the rail never would.',
    partText_chain: 'After a jackpot the reels run hot: sevens three times as often for a while. And the POTTI grows 2 mk every round until somebody takes it.',
    partText_multiplier: 'The two R windows become ×3: three more coins to shoot this round.',
    kTipRound: 'The house hands you <b>{n} coins</b> a round. What the machine pays goes in your purse, and every third round a debt comes out of it.',
    kTipVendor: 'The <b>vendor</b> sells charms that bend the machine. Keep enough back for the debt.',
  },
  fi: {
    kSub: 'Roguelike · pajatso, jolla on velkaa',
    kIntro1: 'Talo antaa sinulle <b>{n} kolikkoa</b> kierrokselle. Mitä kone maksaa, menee <b>kukkaroon</b>.',
    kIntro2: 'Joka kolmas kierros kukkarosta lähtee <b>velka</b>. Maksa se, niin koneeseen pultataan seuraava <b>pachinko-osa</b>. Jos et pysty, lattia aukeaa.',
    kIntro3: 'Kierrosten välissä kauppias myy <b>amuletteja</b>, jotka taivuttavat konetta. Ovessa on kahdeksan lukkoa.',
    kPlay: 'ALOITA', kBase: 'PAJATSO — peruskone ›', kOldPit: 'vanha kuoppa (v1) ›',
    purse: 'Kukkaro', left: 'Kolikot', roundWord: 'Kierros', debtIs: 'Velka {d}/8', roundIs: 'Kierros {r}/{n}',
    shopTitle: 'KAUPPIAS', shopSub: 'Seuraavaksi kierros {r}/{n} · {debt} mk erääntyy kierroksen {n} jälkeen',
    buy: 'OSTA · {p} mk', sold: 'MYYTY', mine: 'Amulettisi {n}/{max}', none: 'ei vielä yhtään',
    reroll: 'KATSO LISÄÄ · {p} mk', next: 'SEURAAVA KIERROS — {n} KOLIKKOA',
    dueTitle: 'VELKA ERÄÄNTYY', dueSub: 'Lukko {d}/8 vaatii <b>{debt} mk</b>. Kukkarossasi on <b>{coins} mk</b>.', pay: 'MAKSA {debt} mk', cantPay: 'ET PYSTY MAKSAMAAN',
    paidTitle: 'LUKKO {d} AUKEAA', bolted: 'Koneeseen pultattiin:',
    fellTitle: 'LATTIA AUKEAA', fellSub: 'Lukolta {d} puuttui <b>{short} mk</b>.',
    wonTitle: 'OVI AUKEAA', wonSub: 'Kahdeksan lukkoa, kahdeksan velkaa maksettu. Kuoppa päästää sinut.',
    again: 'UUSI YRITYS', rsLocks: 'Lukkoja auki', rsEarned: 'Tienattu', rsPotti: '★ POTTI', rsSpins: 'Pyöräytyksiä', rsSevens: 'Seiskoja', rsCharms: 'Amuletteja',
    reach: 'REACH!', clover: '+{n} kolikkoa pelattavaksi', mask: 'NAAMIO vie {n} mk', feverOn: 'FEVER!', feverSub: 'oikean puolen portti on auki {n} kolikon ajan — ammu oikealle',
    feverOff: 'FEVER ohi', chance: 'CHANCE', chanceSub: 'seiskoja tulee kolme kertaa useammin {n} pyöräytyksen ajan',
    x3: '+{n} kolikkoa pelattavaksi', held: 'pyöräytys', interest: 'korko +{n} mk', roundOver: 'KIERROS OHI', lcdIdle: 'VEDÄ VIPUA', lcdShop: 'KAUPPIAS', lcdDue: 'MAKSA VELKA',
    part_chucker: 'Aloitustasku ja rullat', part_tulips: 'Tulppaanit', part_fever: 'FEVER-portti', part_windmills: 'Tuulimyllyt', part_chain: 'Ketjupotit', part_multiplier: 'Kolikkokertoimet',
    partText_chucker: 'START-tasku naulojen keskellä. Siihen osunut kolikko pyöräyttää kolme rullaa: kirsikka-, kello-, kolikko- tai seiskarivi maksaa; apilat antavat kolikoita; myöhemmin naamiorivi vie kukkarostasi.',
    partText_tulips: 'Kaksi 1:00-ikkunaa ovat nyt tulppaaneja. Kolikko avaa terälehdet leveälle; seuraava kolikko sulkee ne.',
    partText_fever: 'Jättipotti — seiskarivi tai POTTI — avaa portin ikkunarivin oikean puolen alla. FEVERin ajan jokainen siellä ikkunan ohi mennyt kolikko maksaa 2 mk. Ammu oikealle.',
    partText_windmills: 'Kaksi tuulimyllyä pyörii naulojen seassa aloitustaskun vieressä ja heittää kolikoita sinne, minne kisko ei koskaan.',
    partText_chain: 'Jättipotin jälkeen rullat kuumenevat: seiskoja kolme kertaa useammin hetken aikaa. Ja POTTI kasvaa 2 mk joka kierros, kunnes joku vie sen.',
    partText_multiplier: 'Kaksi R-ikkunaa muuttuvat ×3:ksi: kolme kolikkoa lisää pelattavaksi tällä kierroksella.',
    kTipRound: 'Talo antaa <b>{n} kolikkoa</b> kierrokselle. Koneen maksut menevät kukkaroon, ja joka kolmas kierros siitä lähtee velka.',
    kTipVendor: '<b>Kauppias</b> myy amuletteja, jotka taivuttavat konetta. Jätä velkaa varten tarpeeksi.',
  },
  ja: {
    kSub: 'ローグライク · 借金つきのパヤッソ',
    kIntro1: 'ハウスは1ラウンドに<b>{n}枚</b>のコインをくれる。台が払った分は<b>財布</b>へ。',
    kIntro2: '3ラウンドごとに財布から<b>借金</b>を返す。返せば次の<b>パチンコ部品</b>が台に取り付けられる。返せなければ床が抜ける。',
    kIntro3: 'ラウンドの合間に、行商人が台を曲げる<b>お守り</b>を売る。扉の鍵は8つ。',
    kPlay: '開始', kBase: 'PAJATSO — 基本の台 ›', kOldPit: '古い穴（v1） ›',
    purse: '財布', left: 'コイン', roundWord: 'ラウンド', debtIs: '借金 {d}/8', roundIs: 'ラウンド {r}/{n}',
    shopTitle: '行商人', shopSub: '次はラウンド{r}/{n} · ラウンド{n}の後に{debt}マルッカ',
    buy: '買う · {p}マルッカ', sold: '売約済み', mine: 'お守り {n}/{max}', none: 'まだない',
    reroll: '別の品 · {p}マルッカ', next: '次のラウンド — コイン{n}枚',
    dueTitle: '返済期限', dueSub: '鍵{d}/8には<b>{debt}マルッカ</b>。財布には<b>{coins}マルッカ</b>。', pay: '{debt}マルッカ払う', cantPay: '払えない',
    paidTitle: '鍵{d}が開く', bolted: '台に取り付けられた：',
    fellTitle: '床が抜ける', fellSub: '鍵{d}で<b>{short}マルッカ</b>足りなかった。',
    wonTitle: '扉が開く', wonSub: '8つの鍵、8つの借金を返した。穴はあなたを放す。',
    again: 'もう一回', rsLocks: '開けた鍵', rsEarned: '稼ぎ', rsPotti: '★ ポッティ', rsSpins: '回転', rsSevens: '7', rsCharms: 'お守り',
    reach: 'リーチ！', clover: '打つコイン+{n}枚', mask: '仮面が{n}マルッカ奪う', feverOn: 'フィーバー！', feverSub: '右のゲートがコイン{n}枚分開く——右打ち',
    feverOff: 'フィーバー終了', chance: 'チャンス', chanceSub: '{n}回転のあいだ7が3倍出やすい',
    x3: '打つコイン+{n}枚', held: '保留', interest: '利息 +{n}マルッカ', roundOver: 'ラウンド終了', lcdIdle: 'レバーを引け', lcdShop: '行商人', lcdDue: '借金を返せ',
    part_chucker: 'スタートチャッカーとリール', part_tulips: 'チューリップ', part_fever: 'フィーバーゲート', part_windmills: '風車', part_chain: '連チャン', part_multiplier: 'コイン倍増',
    partText_chucker: '釘の中にSTARTの穴。入ったコインが3つのリールを回す：チェリー・ベル・コイン・7の列は払い、クローバーはコインをくれ、後には仮面の列が財布から奪う。',
    partText_tulips: '2つの1:00の窓がチューリップに。コインが入ると花びらが大きく開き、次のコインで閉じる。',
    partText_fever: '大当たり——7の列かポッティ——で窓の列の右半分の下のゲートが開く。フィーバー中、そこで窓を外れたコインは2マルッカ払われる。右打ち。',
    partText_windmills: 'チャッカーの横の釘の中で2つの風車が回り、レールでは届かない所へコインを投げる。',
    partText_chain: '大当たりの後、リールが熱くなる：しばらく7が3倍出やすい。そしてポッティは誰かが取るまで毎ラウンド2マルッカ育つ。',
    partText_multiplier: '2つのRの窓が×3に：このラウンドで打つコインが3枚増える。',
    kTipRound: 'ハウスは1ラウンドに<b>{n}枚</b>くれる。台の払いは財布へ、3ラウンドごとに借金がそこから出ていく。',
    kTipVendor: '<b>行商人</b>は台を曲げるお守りを売る。借金の分は残しておくこと。',
  },
});
