// KUOPPA's words, joined onto the Pajatso table (../classic/lang.js). English
// is the source; the Finnish and Japanese are drafts in the same register.
// Jokers, charms and deadline twists carry their own three-language names in
// data.js; this is everything else the page says.
import { extend } from '../classic/lang.js?v=9';

extend({
  en: {
    kSub: 'The roguelike · a Pajatso with an ante on it',
    kIntro1: 'The house hands you <b>{n} coins</b> a round. Every coin that lands in a window scores <b>CHIPS</b> or <b>MULT</b>; when the round is over it scores <b>CHIPS × MULT</b>.',
    kIntro2: 'Reach the <b>ante</b> within three rounds — the third is the <b>deadline round</b>, and it has a twist. The ante is ×10 every lock. Clear it and the next <b>pachinko part</b> is bolted on.',
    kIntro3: 'Between rounds the vendor sells <b>jokers</b> (the score), <b>charms</b> (the machine) and <b>level plates</b>. <b>Tap the machine</b> to nudge the coin. Eight locks on the door.',
    kPlay: 'START THE RUN', kBase: 'PAJATSO — the base machine ›', kOldPit: 'the old pit (v1) ›',
    money: 'Markka', left: 'Coins', roundWord: 'Round', anteWord: 'Ante {d}/8', tallyWord: 'Chips × mult', deadline: 'DEADLINE',
    shopTitle: 'THE VENDOR', shopSub: 'Round {r} of {n} next · ante {got} / {ante}',
    bossNext: 'Deadline round: <b>{name}</b> — {text}',
    buy: 'BUY · {p} mk', sell: 'SELL · {p}', sold: 'SOLD', none: 'none yet', full: 'FULL',
    tJoker: 'JOKER', tCharm: 'CHARM', tPlate: 'LEVEL PLATE',
    plateName: '{w} plate', plateText: '{w} goes to level {l}: {what} a hit.',
    jokers: 'Jokers {n}/{max}', charms: 'Charms {n}/{max}', levels: 'Levels',
    reroll: 'ANOTHER LOOK · {p} mk', next: 'NEXT ROUND — {n} COINS', nextDeadline: 'THE DEADLINE ROUND — {n} COINS',
    scoredSub: 'the round scores {chips} × {mult}',
    clearedTitle: 'LOCK {d} OPENS', clearedSub: 'The ante is paid. +{bonus} mk ({spare} rounds to spare). The next one is <b>{next}</b>.',
    bolted: 'Bolted onto the machine:',
    fellTitle: 'THE FLOOR OPENS', fellSub: 'The deadline passed at <b>{got}</b> of <b>{ante}</b>.',
    wonTitle: 'THE DOOR OPENS', wonSub: 'Eight locks, eight antes. The pit lets you go.',
    again: 'ANOTHER RUN', rsLocks: 'Locks opened', rsBest: 'Best round', rsPotti: '★ POTTI', rsSpins: 'Spins', rsSevens: 'Sevens', rsBought: 'Bought',
    reach: 'REACH!', clover: '+{n} coins to shoot', mask: 'TOKO halves your chips',
    feverOn: '大当たり!', feverSub: 'the attacker is open for {n} coins — shoot right',
    feverOff: 'the attacker shuts', chance: '確変 RUSH', chanceSub: 'sevens ×3 and the electric tulip open for {n} spins',
    rushEnd: 'RUSH over', held: 'spin', roundOver: 'ROUND OVER', lcdShop: 'THE VENDOR', lcdDue: 'DEADLINE',
    nudge: 'NUDGE', tilt: 'TILT!', tiltSub: 'bumped too hard — the coin is the machine’s',
    part_chucker: 'Heso & the LCD', part_tulips: 'Tulips', part_fever: 'The attacker', part_windmills: 'Windmills', part_chain: '確変 & the electric tulip', part_multiplier: 'Ball multipliers',
    partJa_chucker: 'ヘソ・液晶', partJa_tulips: 'チューリップ', partJa_fever: 'アタッカー', partJa_windmills: '風車', partJa_chain: '確変・電チュー', partJa_multiplier: '出玉',
    partText_chucker: 'A yakumono in the middle of the nails: an LCD in a gold frame, a warp in its left side and a stage under the screen that drops a coin onto the HESO, the start pocket, between its two life nails. A coin in the heso spins the reels: cherries and bells score chips, a coin pays markka, clovers hand you coins, sevens are ×2 mult and a jackpot — and later, a line of Tokos halves your chips.',
    partText_tulips: 'The two 1:00 windows are TULIPS: red plastic flowers. A coin in one scores tulip chips and mult and swings its petals open, so the next coin finds it easier; that one shuts it again.',
    partText_fever: 'A jackpot — the POTTI or a line of sevens — is 大当たり: the ATTACKER, the red flap under the right half of the windows, tips open. For ten pulls every coin that misses a window there drops through it and scores. Shoot right.',
    partText_windmills: 'Two plastic pinwheels turn in the nails either side of the yakumono, throwing coins where the rail never would.',
    partText_chain: 'After a jackpot the machine goes 確変 RUSH: sevens three times as often for a while, and the ELECTRIC TULIP on the right opens its wings — a second heso, for shooting right. And the POTTI’s chips grow every round until somebody takes them.',
    partText_multiplier: 'The two R windows become ×3: three more coins to shoot this round.',
    kTipRound: 'Every window scores <b>chips</b> (blue) or <b>mult</b> (red). The round scores chips × mult toward the <b>ante</b>.',
    kTipVendor: '<b>Jokers</b> change the score, <b>charms</b> change the machine, <b>plates</b> raise a window’s level. Jokers and charms sell back for half.',
    tipNudge: '<b>Tap the machine</b> while the coin is out on the face: it shoves the coin toward your finger. Two nudges a coin are free — the third <b>TILTS</b>.',
    kTipDeadline: 'This is the <b>deadline round</b>: the ante is due when it ends. Its twist: {name}.',
  },
  fi: {
    kSub: 'Roguelike · pajatso, jolla on ante',
    kIntro1: 'Talo antaa <b>{n} kolikkoa</b> kierrokselle. Jokainen ikkunaan osunut kolikko tuo <b>PELIMERKKEJÄ</b> tai <b>KERROINTA</b>; kierroksen lopussa lasketaan <b>PELIMERKIT × KERROIN</b>.',
    kIntro2: 'Saavuta <b>ante</b> kolmessa kierroksessa — kolmas on <b>eräpäivän kierros</b>, ja siinä on juoni. Ante on ×10 joka lukolla. Kun se täyttyy, koneeseen pultataan seuraava <b>pachinko-osa</b>.',
    kIntro3: 'Kierrosten välissä kauppias myy <b>jokereita</b> (pisteet), <b>amuletteja</b> (kone) ja <b>tasolaattoja</b>. <b>Napauta konetta</b> tönäistäksesi kolikkoa. Ovessa on kahdeksan lukkoa.',
    kPlay: 'ALOITA', kBase: 'PAJATSO — peruskone ›', kOldPit: 'vanha kuoppa (v1) ›',
    money: 'Markkaa', left: 'Kolikot', roundWord: 'Kierros', anteWord: 'Ante {d}/8', tallyWord: 'Merkit × kerroin', deadline: 'ERÄPÄIVÄ',
    shopTitle: 'KAUPPIAS', shopSub: 'Seuraavaksi kierros {r}/{n} · ante {got} / {ante}',
    bossNext: 'Eräpäivän kierros: <b>{name}</b> — {text}',
    buy: 'OSTA · {p} mk', sell: 'MYY · {p}', sold: 'MYYTY', none: 'ei vielä yhtään', full: 'TÄYNNÄ',
    tJoker: 'JOKERI', tCharm: 'AMULETTI', tPlate: 'TASOLAATTA',
    plateName: '{w}-laatta', plateText: '{w} nousee tasolle {l}: {what} osumalta.',
    jokers: 'Jokerit {n}/{max}', charms: 'Amuletit {n}/{max}', levels: 'Tasot',
    reroll: 'KATSO LISÄÄ · {p} mk', next: 'SEURAAVA KIERROS — {n} KOLIKKOA', nextDeadline: 'ERÄPÄIVÄN KIERROS — {n} KOLIKKOA',
    scoredSub: 'kierros: {chips} × {mult}',
    clearedTitle: 'LUKKO {d} AUKEAA', clearedSub: 'Ante on maksettu. +{bonus} mk ({spare} kierrosta jäi yli). Seuraava on <b>{next}</b>.',
    bolted: 'Koneeseen pultattiin:',
    fellTitle: 'LATTIA AUKEAA', fellSub: 'Eräpäivä meni ohi: <b>{got}</b> / <b>{ante}</b>.',
    wonTitle: 'OVI AUKEAA', wonSub: 'Kahdeksan lukkoa, kahdeksan antea. Kuoppa päästää sinut.',
    again: 'UUSI YRITYS', rsLocks: 'Lukkoja auki', rsBest: 'Paras kierros', rsPotti: '★ POTTI', rsSpins: 'Pyöräytyksiä', rsSevens: 'Seiskoja', rsBought: 'Ostettu',
    reach: 'REACH!', clover: '+{n} kolikkoa pelattavaksi', mask: 'TOKO puolittaa pelimerkkisi',
    feverOn: '大当たり!', feverSub: 'attacker on auki {n} kolikon ajan — ammu oikealle',
    feverOff: 'attacker sulkeutuu', chance: '確変 RUSH', chanceSub: 'seiskoja ×3 ja sähkötulppaani auki {n} pyöräytyksen ajan',
    rushEnd: 'RUSH ohi', held: 'pyöräytys', roundOver: 'KIERROS OHI', lcdShop: 'KAUPPIAS', lcdDue: 'ERÄPÄIVÄ',
    nudge: 'TÖNÄISY', tilt: 'TILT!', tiltSub: 'liian kova tönäisy — kolikko jää koneelle',
    part_chucker: 'Heso ja näyttö', part_tulips: 'Tulppaanit', part_fever: 'Attacker', part_windmills: 'Tuulimyllyt', part_chain: '確変 ja sähkötulppaani', part_multiplier: 'Kolikkokertoimet',
    partJa_chucker: 'ヘソ・液晶', partJa_tulips: 'チューリップ', partJa_fever: 'アタッカー', partJa_windmills: '風車', partJa_chain: '確変・電チュー', partJa_multiplier: '出玉',
    partText_chucker: 'Yakumono naulojen keskellä: näyttö kultakehyksessä, warp-aukko sen vasemmassa laidassa ja näytön alla stage, joka pudottaa kolikon HESOON, aloitustaskuun, kahden elämänaulan välistä. Kolikko hesossa pyöräyttää rullat: kirsikat ja kellot tuovat pelimerkkejä, kolikko maksaa markkoja, apilat antavat kolikoita, seiskat ovat ×2 kerroin ja jättipotti — ja myöhemmin Toko-rivi puolittaa pelimerkkisi.',
    partText_tulips: 'Kaksi 1:00-ikkunaa ovat TULPPAANEJA: punaisia muovikukkia. Kolikko tuo tulppaanin pelimerkit ja kertoimen ja avaa terälehdet, jolloin seuraava osuu helpommin; se sulkee ne taas.',
    partText_fever: 'Jättipotti — POTTI tai seiskarivi — on 大当たり: ATTACKER, punainen läppä ikkunarivin oikean puolen alla, kallistuu auki. Kymmenen vedon ajan jokainen siellä ikkunan ohi mennyt kolikko putoaa sen läpi ja tuo pisteitä. Ammu oikealle.',
    partText_windmills: 'Kaksi muovista tuulimyllyä pyörii naulojen seassa yakumonon molemmin puolin ja heittää kolikoita sinne, minne kisko ei koskaan.',
    partText_chain: 'Jättipotin jälkeen kone menee 確変 RUSHiin: seiskoja kolme kertaa useammin hetken, ja oikealla oleva SÄHKÖTULPPAANI avaa siipensä — toinen heso, oikealle ammuttavaksi. Ja POTIN pelimerkit kasvavat joka kierros, kunnes joku vie ne.',
    partText_multiplier: 'Kaksi R-ikkunaa muuttuvat ×3:ksi: kolme kolikkoa lisää pelattavaksi tällä kierroksella.',
    kTipRound: 'Jokainen ikkuna tuo <b>pelimerkkejä</b> (sininen) tai <b>kerrointa</b> (punainen). Kierros laskee merkit × kerroin kohti <b>antea</b>.',
    kTipVendor: '<b>Jokerit</b> muuttavat pisteitä, <b>amuletit</b> konetta, <b>laatat</b> nostavat ikkunan tasoa. Jokerit ja amuletit voi myydä puoleen hintaan.',
    tipNudge: '<b>Napauta konetta</b>, kun kolikko on laudalla: se tönäisee kolikkoa sormesi suuntaan. Kaksi tönäisyä kolikkoa kohden on ilmaisia — kolmas <b>TILTTAA</b>.',
    kTipDeadline: 'Tämä on <b>eräpäivän kierros</b>: ante erääntyy sen lopussa. Juoni: {name}.',
  },
  ja: {
    kSub: 'ローグライク · アンテつきのパヤッソ',
    kIntro1: 'ハウスは1ラウンドに<b>{n}枚</b>くれる。窓に入ったコインは<b>チップ</b>か<b>倍率</b>になり、ラウンドの終わりに<b>チップ×倍率</b>で得点。',
    kIntro2: '3ラウンドで<b>アンテ</b>に届け——3つ目は<b>期限のラウンド</b>で、ひねりがある。アンテは鍵ごとに×10。越えれば次の<b>パチンコ部品</b>が取り付けられる。',
    kIntro3: 'ラウンドの合間に行商人が<b>ジョーカー</b>（得点）、<b>お守り</b>（台）、<b>レベルプレート</b>を売る。<b>台をタップ</b>してコインをナッジ。扉の鍵は8つ。',
    kPlay: '開始', kBase: 'PAJATSO — 基本の台 ›', kOldPit: '古い穴（v1） ›',
    money: 'マルッカ', left: 'コイン', roundWord: 'ラウンド', anteWord: 'アンテ {d}/8', tallyWord: 'チップ×倍率', deadline: '期限',
    shopTitle: '行商人', shopSub: '次はラウンド{r}/{n} · アンテ {got} / {ante}',
    bossNext: '期限のラウンド：<b>{name}</b> — {text}',
    buy: '買う · {p}マルッカ', sell: '売る · {p}', sold: '売約済み', none: 'まだない', full: '満杯',
    tJoker: 'ジョーカー', tCharm: 'お守り', tPlate: 'レベルプレート',
    plateName: '{w}プレート', plateText: '{w}がレベル{l}に：1ヒットで{what}。',
    jokers: 'ジョーカー {n}/{max}', charms: 'お守り {n}/{max}', levels: 'レベル',
    reroll: '別の品 · {p}マルッカ', next: '次のラウンド — コイン{n}枚', nextDeadline: '期限のラウンド — コイン{n}枚',
    scoredSub: 'ラウンドの得点 {chips} × {mult}',
    clearedTitle: '鍵{d}が開く', clearedSub: 'アンテ達成。+{bonus}マルッカ（{spare}ラウンド余り）。次は<b>{next}</b>。',
    bolted: '台に取り付けられた：',
    fellTitle: '床が抜ける', fellSub: '期限切れ：<b>{got}</b> / <b>{ante}</b>。',
    wonTitle: '扉が開く', wonSub: '8つの鍵、8つのアンテ。穴はあなたを放す。',
    again: 'もう一回', rsLocks: '開けた鍵', rsBest: '最高ラウンド', rsPotti: '★ ポッティ', rsSpins: '回転', rsSevens: '7', rsBought: '購入',
    reach: 'リーチ！', clover: '打つコイン+{n}枚', mask: 'トコがチップを半分に',
    feverOn: '大当たり！', feverSub: 'アタッカーがコイン{n}枚分開く——右打ち',
    feverOff: 'アタッカーが閉じる', chance: '確変ラッシュ', chanceSub: '{n}回転のあいだ7が3倍、電チューが開く',
    rushEnd: 'ラッシュ終了', held: '保留', roundOver: 'ラウンド終了', lcdShop: '行商人', lcdDue: '期限',
    nudge: 'ナッジ', tilt: 'ティルト！', tiltSub: '叩きすぎ——コインは台のもの',
    part_chucker: 'ヘソと液晶', part_tulips: 'チューリップ', part_fever: 'アタッカー', part_windmills: '風車', part_chain: '確変と電チュー', part_multiplier: '出玉',
    partJa_chucker: 'ヘソ・液晶', partJa_tulips: 'チューリップ', partJa_fever: 'アタッカー', partJa_windmills: '風車', partJa_chain: '確変・電チュー', partJa_multiplier: '出玉',
    partText_chucker: '釘の真ん中に役物：金の枠の液晶、左側にワープ、画面の下にステージ。ステージはコインを2本の命釘の間からスタート入賞口の「ヘソ」へ落とす。ヘソに入るとリールが回る：チェリーとベルはチップ、コインはマルッカ、クローバーはコイン、7は倍率×2で大当たり——後にはトコの列がチップを半分にする。',
    partText_tulips: '2つの1:00の窓がチューリップに：赤いプラスチックの花。入るとチューリップのチップと倍率、花びらが開いて次が入りやすくなり、次の1枚でまた閉じる。',
    partText_fever: '大当たり——ポッティか7の列——でアタッカー（窓の列の右半分の下の赤いフラップ）が開く。10回のあいだ、そこで窓を外れたコインはそこへ落ちて得点。右打ち。',
    partText_windmills: '役物の両側の釘の中でプラスチックの風車が2つ回り、レールでは届かない所へコインを投げる。',
    partText_chain: '大当たりの後は確変ラッシュ：しばらく7が3倍出やすく、右の電チューが羽を開く——右打ち用の2つ目のヘソ。そしてポッティのチップは誰かが取るまで毎ラウンド育つ。',
    partText_multiplier: '2つのRの窓が×3に：このラウンドで打つコインが3枚増える。',
    kTipRound: '窓は<b>チップ</b>（青）か<b>倍率</b>（赤）になる。ラウンドはチップ×倍率で<b>アンテ</b>に向けて得点。',
    kTipVendor: '<b>ジョーカー</b>は得点を、<b>お守り</b>は台を、<b>プレート</b>は窓のレベルを変える。ジョーカーとお守りは半額で売れる。',
    tipNudge: 'コインが盤面にある時に<b>台をタップ</b>すると、指の方へコインを押す。1枚につき2回まで無料——3回目は<b>ティルト</b>。',
    kTipDeadline: 'これは<b>期限のラウンド</b>：終わりにアンテの支払い。ひねり：{name}。',
  },
});

