// TOKO MIDORI GAMES — local small-brain layer.
// Retrieval + corrections + associations + composition. No network/model call.
import projects from './project-knowledge.js';

const KEY='tokoBrain.v1';
const SOURCE_WEIGHT={owner:100,authority:95,lock:92,design:85,roadmap:78,code:72,catalogue:60,memory:50,inferred:35};
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY))||{corrections:[],links:{},queries:[]}}catch{return{corrections:[],links:{},queries:[]}}};
const write=s=>{try{localStorage.setItem(KEY,JSON.stringify(s))}catch{}return s};
const clean=s=>String(s||'').toLowerCase().replace(/[→]/g,' to ').replace(/[^a-z0-9]+/g,' ').trim();
const tokens=s=>new Set(clean(s).split(/\s+/).filter(x=>x.length>2));
const overlap=(a,b)=>{const A=tokens(a),B=tokens(b);let n=0;for(const x of A)if(B.has(x))n++;return n/Math.max(1,Math.sqrt(A.size*B.size));};
const now=()=>new Date().toISOString();

function sourceKind(path=''){const p=String(path).toLowerCase();if(/owner_direction/.test(p))return'owner';if(/design_authority/.test(p))return'authority';if(/design_locks|phasing/.test(p))return'lock';if(/design|gdd|game_design/.test(p))return'design';if(/roadmap|queue/.test(p))return'roadmap';if(/\.js$|\.gd$/.test(p))return'code';return'catalogue';}
function projectFacts(p){const src=p.sources||[];const best=src.map(sourceKind).sort((a,b)=>SOURCE_WEIGHT[b]-SOURCE_WEIGHT[a])[0]||'catalogue';const out=[];(p.design||[]).forEach((text,i)=>out.push({project:p.id,title:p.title,kind:'design',text,source:src[Math.min(i,src.length-1)]||'hub/games.js',sourceKind:best,confidence:SOURCE_WEIGHT[best]}));(p.roadmap||[]).forEach(text=>out.push({project:p.id,title:p.title,kind:'roadmap',text,source:src.find(x=>/roadmap|queue/i.test(x))||src[0]||'hub/games.js',sourceKind:'roadmap',confidence:SOURCE_WEIGHT.roadmap}));(p.constraints||[]).forEach(text=>out.push({project:p.id,title:p.title,kind:'constraint',text,source:src.find(x=>/lock|authority|owner|phasing/i.test(x))||src[0]||'hub/games.js',sourceKind:'lock',confidence:SOURCE_WEIGHT.lock}));return out;}
function allFacts(){const rich=projects.PROJECTS.flatMap(projectFacts);const state=read();const corrections=(state.corrections||[]).map(c=>({project:c.project||null,title:c.title||'LEARNED',kind:'correction',text:c.text,source:'local correction',sourceKind:'owner',confidence:SOURCE_WEIGHT.owner+5,at:c.at}));return [...corrections,...rich];}
export function retrieve(query,{limit=5,project=null}={}){const q=clean(query);const p=project||projects.findProject(q)?.id||null;return allFacts().filter(f=>!p||f.project===p||(f.kind==='correction'&&!f.project)).map(f=>{let score=overlap(q,`${f.title} ${f.kind} ${f.text}`)*100+f.confidence*.18;if(p&&f.project===p)score+=25;if(/roadmap|next|future/.test(q)&&f.kind==='roadmap')score+=24;if(/why|design|goal|vision|core/.test(q)&&f.kind==='design')score+=20;if(/rule|lock|must|constraint|never/.test(q)&&f.kind==='constraint')score+=22;if(f.kind==='correction')score+=18;return {...f,score};}).filter(x=>x.score>14).sort((a,b)=>b.score-a.score).slice(0,limit);}
export function teachCorrection(raw,context=''){let text=String(raw||'').trim();text=text.replace(/^(no[, ]+|actually[, ]+|correction[: ]+|remember that[: ]+|you are wrong[, ]*)/i,'').trim();if(text.length<5)return null;let p=projects.findProject(`${context} ${text}`);if(!p&&context){const inferred=retrieve(context,{limit:1})[0];if(inferred)p=projects.findProject(inferred.title);}const s=read();s.corrections=Array.isArray(s.corrections)?s.corrections:[];const item={at:now(),project:p?.id||null,title:p?.title||null,text:text.slice(0,360)};s.corrections.push(item);s.corrections=s.corrections.slice(-40);write(s);try{globalThis.TokoMind?.remember?.('correction',text,{project:p?.id||null,priority:'owner'})}catch{}return item;}
export function link(a,b,weight=1){const s=read();const A=clean(a),B=clean(b);if(!A||!B)return;s.links[A]=s.links[A]||{};s.links[A][B]=(s.links[A][B]||0)+weight;s.links[B]=s.links[B]||{};s.links[B][A]=(s.links[B][A]||0)+weight;write(s)}
function learnQuery(q,hits){const s=read();s.queries=Array.isArray(s.queries)?s.queries:[];s.queries.push({at:now(),q:String(q).slice(0,180),projects:[...new Set(hits.map(x=>x.project).filter(Boolean))]});s.queries=s.queries.slice(-80);write(s);for(const h of hits.slice(0,3))link(q,h.title,.15);}
export function compose(query){const hits=retrieve(query,{limit:6});if(!hits.length)return null;learnQuery(query,hits);const project=projects.findProject(query)||projects.findProject(hits[0].title);const chosen=[];for(const h of hits){if(!chosen.some(x=>overlap(x.text,h.text)>.72))chosen.push(h);if(chosen.length===3)break;}const lines=[];if(project)lines.push(`${project.title.toUpperCase()} — WHAT I THINK I KNOW`);else lines.push('WHAT I THINK I KNOW');chosen.forEach(h=>lines.push(h.text));const correction=chosen.find(x=>x.kind==='correction');if(correction)lines.push('I AM GIVING YOUR CORRECTION MORE WEIGHT THAN MY OLDER NOTES.');const weakest=Math.min(...chosen.map(x=>x.confidence));lines.push(weakest>=90?'CONFIDENCE: HIGH — THIS IS CLOSE TO OWNER/DESIGN AUTHORITY.':weakest>=70?'CONFIDENCE: MEDIUM — THIS COMES FROM CURRENT DESIGN/ROADMAP MATERIAL.':'CONFIDENCE: LOW — I AM CONNECTING WEAKER EVIDENCE.');return lines;}
export function explainBelief(query){const hits=retrieve(query,{limit:4});if(!hits.length)return['I DO NOT HAVE ENOUGH EVIDENCE FOR THAT YET.'];return ['WHY I THINK THAT:',...hits.map(h=>`${h.text} [${h.sourceKind.toUpperCase()} · ${h.source}]`)];}
export function memorySummary(){const s=read();return [`I HAVE ${(s.corrections||[]).length} EXPLICIT CORRECTION${(s.corrections||[]).length===1?'':'S'} AND ${(s.queries||[]).length} RECENT RETRIEVAL TRACE${(s.queries||[]).length===1?'':'S'}.`,'CORRECTIONS OUTRANK ROADMAPS. ROADMAPS DO NOT OUTRANK DESIGN AUTHORITY.'];}
const api={retrieve,compose,teachCorrection,explainBelief,link,memorySummary,sourceWeights:SOURCE_WEIGHT};globalThis.TokoBrain=api;export default api;
