// TOKO MIDORI GAMES — the counter in Finnish.
//
// A pure string pack. The structure — what opens what, what is spent, what
// only exists at two in the morning — lives once in dialogue.js; this file
// only says the words. Anything missing here falls through to English, so a
// half-finished pack reads wrong rather than reading empty.
//
// TRANSLATED, NOT CONVERTED. Toko's English is clipped and shouted: no
// articles to drop, so the flatness comes from short declaratives. Finnish
// takes the caps happily and drops the pronouns instead — "EN AIO KIISTELLÄ"
// carries the same shrug as "I WILL NOT ARGUE" without the "minä". Where a
// literal rendering went limp the line was rewritten to land the same punch,
// which is the only kind of translation this voice survives.
//
// DRAFT: written by the machine, for a Finnish speaker to correct. The one
// place to be suspicious is the mantra — those lines are meant to be shoutable
// across a room, and that is a thing you can only test out loud.

export const FI = {
  GREETING: [
    'LÖYSIT TISKIN.',
    'KYSY JOTAIN.',
  ],
  LATE: [
    'SINÄ, TÄHÄN AIKAAN.',
    'LEVY PYÖRII VIELÄ. KYSY.',
  ],
  RETURNING: [
    ['PALASIT.', 'KYSY JOTAIN.'],
    ['TAAS.', 'ANNA TULLA.'],
    ['TIEDÄT MISSÄ OLEN.', 'KYSY.'],
  ],
  NOTED: ['SAIN VIESTISI.', 'LUEN NE KAIKKI. KYSY JOTAIN.'],
  REMEMBERED: ['VIIMEKSI KYSYIT: {x}', 'KYSY JOTAIN MUUTA.'],
  ASIDES: [
    ['EI OLE KIIRE.'],
    ['EN OLE MENOSSA MIHINKÄÄN.'],
    ['SOOLO ALKAA KOHTA UUDESTAAN.'],
    ['VOIT MYÖS VAIN MENNÄ PELAAMAAN.'],
    ['HILJAISUUS EI HAITTAA MINUA.'],
  ],
  MISSES: [
    ['TUOTA EN TUNNE.', 'KOKEILE LISTAA.'],
    ['SANO TOISIN.'],
    ['EI. KYSY JOTAIN LISTALTA,', 'TAI SANO ETTÄ OLEN VÄÄRÄSSÄ.'],
    ['TUOHON MINULLA EI OLE VASTAUSTA.'],
  ],
  CRY_A: ['SIINÄ SE.', 'LOPETA NYT KIRJOITTAMINEN JA MENE.'],
  SEEN_NOTHING: [
    'EI MITÄÄN. OLET JOKO UUSI TAI TYHJENSIT SEN,',
    'JA MOLEMMAT SOPIVAT MINULLE.',
    'MENE JÄTTÄMÄÄN JOKIN NUMERO JOHONKIN.',
  ],
  SEEN_SOMETHING: ['TÄHÄN MENNESSÄ:'],
  CHANGED_NONE: ['EI VIELÄ MITÄÄN LUKEMISEN ARVOISTA.'],
  CHANGED_YOURS: 'JÄTIT TÄSTÄ VIESTIN.',
  ABOUT_UNKNOWN: ['TUOSTA MINULLA EI OLE VIELÄ REPLIIKKIÄ.'],

  CHANGED: [
    {
      when: '2026-07', game: 'hub',
      what: ['TISKI OTTI ENSIMMÄISET VIESTINSÄ.',
        'VOIT MYÖS VAIN KIRJOITTAA MINULLE.'],
    },
    {
      when: '2026-07', game: 'hub',
      what: ['KOTI-NAPPI TOIMI HIIRELLÄ JA',
        'EI TEHNYT MITÄÄN PEUKALON ALLA.',
        'NYT SE TOIMII PEUKALOLLA.'],
    },
    {
      when: '2026-07', game: 'hub',
      what: ['PELIT JOTKA EIVÄT OLE PYSTYSSÄ SANOVAT',
        'SEN NAPISSA EIVÄTKÄ HEITÄ 404:ÄÄ.'],
    },
  ],

  GAME_NOTES: {
    sudsjack: ['KAIMA. PUTKI JA PALJON SAIPPUAA.',
      'PELATTAVA ON VANHA VEKTORIVERSIO.',
      'UUSI ALKAA HYPER DAGGERISTA.'],
    tokodrop: ['HYYTELÖÄ. SE HEILUU KOSKA HALUSIN NIIN.',
      'VIHOLLISET PARVEILEVAT KUIN KALAT JA',
      'SITTEN NE PUHKEAVAT. SIINÄ KAIKKI.'],
    hyperdagger: ['TÄMÄ TAPPAA SINUT NOPEIMMIN.',
      'JOKAINEN KALLO ON RAKENNETTU KUUTIOISTA JA',
      'JOKAINEN KUOLEMA HEITTÄÄ NE LATTIALLE.',
      'SELVIYTYMISAIKA ON AINOA PISTEMÄÄRÄ.'],
    dropcabal: ['CABAL, MINUN HYYTELÖILLÄNI.',
      'AMMU SYVYYTEEN. LÄHELLÄ OLEVAT SYÖVÄT',
      'LAUKAUKSET JOTKA TARKOITIT KAUAS.'],
    paperboy: ['LEHTIREITTI AAMUNKOITTEESSA. LITTEÄ VÄRI,',
      'EI VALOJA EIKÄ VARJOJA — JULISTE JOLLA AJETAAN.',
      'EI OLE LIIKKUNUT VÄHÄÄN AIKAAN.'],
    flashprince: ['EI YHTÄKÄÄN SPRITEÄ. JOKAINEN RUUTU ON',
      'MONIKULMIOITA, PAKOTETTUNA KUUTEENTOISTA VÄRIIN.',
      'JOKAINEN ALOITETTU LIIKE VIEDÄÄN LOPPUUN —',
      'SIINÄ ON PELI, JA SIIHEN MYÖS KUOLET.'],
    gameoflife: ['HILJAINEN. SE PÄÄTTYY SIIHEN ETTÄ',
      'SE LÄHETTÄÄ SINUT ULOS, JA TOIMII ILMAN VERKKOA.',
      'AINOA HUONE JOTA EN SIGNEERAA.'],
    neonronin: ['PORTTI, PORTAAT, JA JOKU NOUSEE NIITÄ.',
      'PIIRSIN KANNEN ENNEN PELIÄ.'],
    skltr: ['LUITA. PYSY LIIKKEESSÄ.'],
    powder: ['ALAMÄKEEN, LUJAA, JA KÄÄNNE TULEE',
      'MYÖHEMMIN KUIN LUULET.'],
    tinyhawk: ['PIENI LINTU. PITKÄ PUDOTUS.'],
    tiny2d: ['YKSI NAPPI. SIINÄ KOKO SOITIN.'],
    eyetest: ['EI OIKEASTAAN PELI. KATSO SILTI.'],
    radiofree: ['PIRAATTIVIRTA, JA MINÄ LUEN SEN.',
      'JOKAINEN TIEDOTE ON KEKSITTY. SE ON KOKO IDEA —',
      'DECODE PURKAA YHDEN JA NÄYTTÄÄ MITÄ',
      'SANAMUOTO TEKI SINULLE.',
      'LUE SEURAAVA OIKEA UUTINEN SAMALLA TAVALLA.'],
  },

  // Finnish function words. Without these the parser scored on ON/EI/JA/SE
  // and two ordinary words were enough to hand back a confident wrong
  // answer — the exact failure the whole thing is built to avoid.
  STOP: ['ON', 'EI', 'JA', 'SE', 'SITÄ', 'SEN', 'TAI', 'MUTTA', 'OLEN', 'OLET',
    'MINÄ', 'SINÄ', 'ME', 'NE', 'MIKÄ', 'MITÄ', 'MIKSI', 'MITEN', 'KUN',
    'ETTÄ', 'JOS', 'NIIN', 'VAIN', 'JO', 'VIELÄ', 'TÄMÄ', 'TUO', 'OLE',
    'VOI', 'PITÄÄ', 'SAA', 'ONKO', 'OLIKO'],

  // What the parser matches on, in Finnish. Not a translation of the English
  // keys — the words a Finnish speaker would actually type, including the
  // clipped spoken forms ("mikä", "miks") that a written table would miss.
  KEYS: {
    who: ['KUKA', 'TOKO', 'MIDORI', 'TAITEILIJA', 'TEKIJÄ', 'HEI', 'MOI', 'TERVE'],
    mask: ['NAAMIO', 'MASKI', 'KASVOT', 'PIILOSSA', 'ANONYYMI'],
    name: ['MIDORI', 'VIHREÄ', 'NIMI', 'JAPANI', 'TARKOITTAA'],
    clusters: ['MUUT', 'KAIKKI', 'TIIMI', 'PORUKKA', 'PÄÄT'],
    ai: ['TEKOÄLY', 'KONE', 'MALLI', 'ROBOTTI', 'GENEROITU'],
    scroll: ['SELAA', 'SELAAMINEN', 'YLEISÖ', 'SYÖTE', 'SISÄLTÖ'],
    hypocrite: ['TEKOPYHÄ', 'HUIJAUS', 'HUIJAAT', 'LAISKA', 'FEIKKI'],
    seam: ['SAUMA', 'GLITCH', 'HÄIRIÖ', 'RIKKI', 'KIILLOTUS'],
    music: ['MUSIIKKI', 'KUUNTELET', 'BIISI', 'LEVY', 'FLOYD'],
    faraway: ['KAUKANA', 'HIDAS', 'VÄSYNYT', 'POISSAOLEVA'],
    late: ['MYÖHÄ', 'MYÖHÄÄN', 'YÖ', 'YÖLLÄ', 'NUKKUA', 'AIKA'],
    mantra: ['HYVÄ', 'PELI', 'MANTRA', 'SÄÄNNÖT', 'SUUNNITTELU', 'VERBI', 'FILOSOFIA'],
    thirty: ['TUTORIAALI', 'OPETTAA', 'KOLMEKYMMENTÄ', 'SEKUNTIA', 'ALKU'],
    feel: ['TUNTUMA', 'FIILIS', 'OHJAUS', 'VIIVE', 'TARKKA'],
    juice: ['MEHU', 'JUICE', 'KIILLOTUS', 'EFEKTIT', 'TÄRINÄ'],
    hard: ['VAIKEA', 'VAIKEAA', 'RANKKA', 'EPÄREILU', 'HELPPO'],
    loop: ['SILMUKKA', 'UUDESTAAN', 'KOUKUTTAA', 'YRITÄ', 'KIERROS'],
    creed: ['KOKO', 'KAIKKI', 'MANIFESTI', 'LUE', 'SANO'],
    faves: ['SUOSIKKI', 'SUOSIKIT', 'PELAAT', 'VAIKUTTEET', 'ESIKUVAT', 'KLASSIKOT'],
    retro: ['RETRO', 'NOSTALGIA', 'PIKSELI', 'ATARI', 'VANHA'],
    anarchy: ['ANARKISTI', 'ANARKIA', 'POLITIIKKA', 'PUNK', 'DIY'],
    browser: ['SELAIN', 'VERKKO', 'NETTI', 'STEAM', 'ASENNUS', 'KAUPPA'],
    start: ['ALOITAN', 'ALOITTAA', 'ALKUUN', 'MITEN', 'OPPIA', 'TEHDÄ'],
    bad: ['HUONO', 'SURKEA', 'EPÄONNISTUN', 'PELKÄÄN', 'VIRHE'],
    tools: ['TYÖKALUT', 'KÄYTÄT', 'MOOTTORI', 'UNITY', 'GODOT', 'EDITORI'],
    build: ['BUILD', 'KÄÄNNÖS', 'NPM', 'WEBPACK', 'ASKEL'],
    finish: ['VALMIIKSI', 'VALMIS', 'LOPETAN', 'JUMISSA', 'LAAJUUS'],
    test: ['TESTAAN', 'TESTATA', 'PELITESTI', 'PALAUTE', 'KATSOA'],
    play: ['PELAAN', 'PELATA', 'SUOSITTELE', 'VALITSE', 'MIKÄ', 'PARAS'],
    floor: ['LATTIA', 'PELIT', 'LISTA', 'VALIKOIMA', 'ARKADI', 'TÄÄLLÄ'],
    quiet: ['HILJAINEN', 'ELÄMÄ', 'RAUHA', 'ZEN', 'LUONTO', 'ULOS'],
    dead: ['KUOLLUT', 'ARKISTO', 'VANHA', 'HYLÄTTY'],
    about: ['KERRO', 'KAAPPI', 'KUVAILE', 'NIISTÄ'],
    me: ['KYSY', 'VUOROSI', 'VUORO', 'KYSYMYS'],
    note: ['VIESTI', 'SANOA', 'PALAUTE', 'KERTOA', 'BUGI', 'IDEA', 'KIITOS'],
    mine: ['OMAT', 'KERTONUT', 'VIESTIT', 'KIRJOITIN', 'ARKISTO'],
    changed: ['MUUTTUI', 'KORJATTU', 'MERKITYSTÄ', 'KUUNTELET', 'MUUTOKSET'],
    seen: ['NÄHNYT', 'PISTEET', 'ENNÄTYS', 'PELANNUT', 'TILASTOT'],
    cost: ['MAKSAA', 'HINTA', 'RAHA', 'ILMAINEN', 'MAINOKSET'],
    steal: ['VARASTAA', 'OTTAA', 'KOPIOIDA', 'LISENSSI', 'LÄHDEKOODI', 'KOODI'],
    gift: ['LAHJA', 'TARRA', 'ANNA', 'JOTAIN', 'LATAA', 'SVG'],
    back: ['TAKAHUONE', 'LISÄÄ', 'SYVEMMÄLLE', 'SALAISUUS'],
    bye: ['MOIKKA', 'LÄHDEN', 'POIS', 'HEIPPA', 'KIITOS'],
  },

  UI: {
    CUE: 'TOKO ON TISKILL\u00c4',
    TALK: 'PUHU',
    HINT: '1-9 VALITSE \u00b7 KIRJOITA PUHUAKSESI \u00b7 ESC POIS',
    LEAVE: 'POIS',
    SEND: 'L\u00c4HET\u00c4',
    PARSE_PH: 'tai kirjoita jotain\u2026',
    NOTE_PH: 'rikki, tylsi\u00e4, v\u00e4\u00e4rin \u2014 kaikki hy\u00f6dyllisi\u00e4',
    NOTE_PH_ABOUT: 'aiheesta {x} \u2014 rikki, tylsi\u00e4, v\u00e4\u00e4rin, kaikki k\u00e4y',
    NOTE_LABEL: 'Viestisi Tokolle',
    NOTE_LABEL_ABOUT: 'Viestisi aiheesta {x}',
    TELL: '\u25b8 KERRO H\u00c4NELLE T\u00c4ST\u00c4',
    STICKER: 'OTA TARRA',
    NOTHING_SAID: ['ET SANONUT MIT\u00c4\u00c4N, JOTEN EN KIRJOITTANUT MIT\u00c4\u00c4N.'],
    EMPTY_BOX: ['EI VIEL\u00c4 MIT\u00c4\u00c4N. LAATIKKO ON TYHJ\u00c4.'],
    MORE: '  \u2026JA {n} MUUTA.',
    NO_FLOOR: 'VAIKKA T\u00c4\u00c4LT\u00c4 EN N\u00c4E LATTIAA.',
    SND_ON: '\u266a P\u00c4\u00c4LL\u00c4',
    SND_OFF: '\u266a POIS',
    SND_LABEL_ON: 'Kirjoitus\u00e4\u00e4ni p\u00e4\u00e4ll\u00e4',
    SND_LABEL_OFF: 'Kirjoitus\u00e4\u00e4ni pois',
    TALK_TO: 'Puhu: {x}',
    SAY_TO: 'Sano jotain: {x}',
    SENT: ['SE MENI PERILLE. KIITOS.'],
    SENT_BLIND: ['SE L\u00c4HTI.',
      'EN N\u00c4E T\u00c4\u00c4LT\u00c4 TOISTA P\u00c4\u00c4T\u00c4,',
      'JOTEN SE ON KAIKKI MIT\u00c4 VOIN REHELLISESTI SANOA.'],
    QUEUED: ['VERKKO SANOI EI.', 'SE ON L\u00c4HTEVISS\u00c4. SE MENEE ENSI KERRALLA.'],
    OFF: ['T\u00c4N\u00c4\u00c4N SILL\u00c4 EI OLE MINNE MENN\u00c4,',
      'JOTEN SE ON KIRJOITETTU KONEELLESI.'],
  },

  FAVOURITES: [
    { id: 'rygar', name: 'RYGAR', when: '1986',
      a: ['DISKARMOR. YKSI VERBI, KETJUN PÄÄSSÄ,',
        'JA KOKO PELI ON SEN KAAREN OPETTELUA.',
        'SIINÄ ON KOKO OPPITUNTI.'] },
    { id: 'sinpunishment', name: 'SIN AND PUNISHMENT 2', when: '2009',
      a: ['TREASURE EI ANTANUT RUUDUN OLLA PAIKALLAAN.',
        'SE ON KISKOILLA JA SILTI TÄYSIN SINUN —',
        'RAITA ON KEHYS, EI TALUTUSHIHNA.'] },
    { id: 'chrono', name: 'CHRONO TRIGGER', when: '1995',
      a: ['EI SATUNNAISIA TAISTELUITA. EI HUKATTUA RUUTUA.',
        'SE KUNNIOITTAA AIKAASI LAJITYYPISSÄ JOKA',
        'ELÄÄ SEN VIEMISESTÄ. YHÄ PARAS NIISTÄ.'] },
    { id: 'nexmachina', name: 'NEX MACHINA', when: '2017',
      a: ['KAIKKI RUUDULLA YRITTÄÄ TAPPAA SINUT',
        'JA JOKAINEN OSA SIITÄ ON LUETTAVISSA.',
        'SE EI OLE KAAOSTA. SE ON SOMMITTELUA.'] },
    { id: 'isaac', name: 'THE BINDING OF ISAAC', when: '2011',
      a: ['ESINEET PUHUVAT KESKENÄÄN.',
        'SE KIERROS JOKA RIKKOO PELIN ON SE JOSTA',
        'PUHUT MUILLE VUOSIEN AJAN.'] },
    { id: 'mariobros', name: 'MARIO BROS.', when: '1983',
      a: ['SE HYPPY. KUKAAN EI OLE PARANTANUT SITÄ.',
        'OHJAAT ILMASSA JA SILTI SILLÄ ON PAINO.',
        'KAIKKI KOPIOIVAT SEN.',
        'LÄHES KUKAAN EI OSU SIIHEN.'] },
    { id: 'bombjack', name: 'BOMB JACK', when: '1984',
      a: ['LEIJU, PUDOTA, LEIJU. SIINÄ KOKO VERBI.',
        'HYPPY JOSSA ON HIMMENNIN EIKÄ KYTKIN,',
        'EIKÄ KUKAAN OLE VOITTANUT SITÄ SEN JÄLKEEN.'] },
    { id: 'tempest', name: 'TEMPEST 2000', when: '1994',
      a: ['MINTER LAITTOI RAVEN PUTKEEN.',
        'TODISTE SIITÄ ETTÄ VÄRI JA ÄÄNI OVAT',
        'MEKANIIKKAA, EI PÄÄLLE LADOTTUA KORISTETTA.'] },
  ],
  FAVE_UNKNOWN: ['EN OLE PELANNUT SITÄ TARPEEKSI SANOAKSENI.'],

  T: {
    who: {
      q: 'KUKA SINÄ OLET?',
      a: ['TOKO MIDORI. 美鳥十湖.',
        'TEEN NÄMÄ PELIT.',
        'SIINÄ ON KOKO ELÄMÄKERTA.'],
    },
    mask: {
      q: 'MIKSI NAAMIO?',
      a: ['JOTTA KATSOISIT TYÖTÄ.',
        'KASVOT OVAT BRÄNDI. MINULLA ON JO YKSI —',
        'SE ON OVESSA, JA SE HYMYILEE.'],
    },
    name: {
      q: 'MIKSI "MIDORI"?',
      a: ['SE ON NIMI, EI VÄRITEORIA.',
        'BRÄNDI ON MUSTA JA MAGENTA.',
        'IHMISET KYSYVÄT. NAUTIN SIITÄ.'],
    },
    clusters: {
      q: 'KUKA MUU ON TOKO?',
      a: ['TOKO ON YKSI IHMINEN.',
        'TOKO ON MYÖS JOKAINEN JOKA ON JULKAISSUT',
        'TÄÄLTÄ JOTAIN — JA JOKAINEN PELAAJA',
        'JOKA EI OLE VIELÄ SAAPUNUT.',
        'PÄÄ ON TÄYNNÄ PIENEMPIÄ PÄITÄ.'],
    },
    ai: {
      q: 'KÄYTÄTKÖ TEKOÄLYÄ?',
      a: ['KYLLÄ. ÄÄNEEN. TARKOITUKSELLA.',
        'SE ON TYÖKALU JOSSA ON SAUMA, JA ANNAN',
        'SAUMAN NÄKYÄ.',
        'SITÄ EN TEE, ETTÄ ANTAISIN KONEEN',
        'OLLA YLEISÖ.'],
    },
    scroll: {
      q: 'MITÄ SE TARKOITTAA?',
      a: ['MAAILMAA JOSSA KAIKKI GENEROIDAAN',
        'EIKÄ MITÄÄN TEHDÄ.',
        'JOSSA IHMISET SELAAVAT TULOSTETTA',
        'SEN SIJAAN ETTÄ LEIKKAISIVAT OMANSA.',
        'ÄLÄ OLE SEN YLEISÖ.'],
    },
    hypocrite: {
      q: 'ELI OLET TEKOPYHÄ.',
      a: ['LUULTAVASTI. ISTU ALAS.',
        'EN USKO ETTÄ TYÖKALU ON ONGELMA.',
        'EIKÄ SAMPLERI OLLUT SITÄ AIKANAAN.',
        'ONGELMA ON ANTAA PÄÄTTÄMINEN',
        'JOLLEKIN MUULLE.',
        'MINÄ PÄÄTÄN YHÄ. SIINÄ KOKO RAJA.'],
    },
    seam: {
      q: 'MIKÄ ON SAUMA?',
      a: ['PAIKKA JOSSA TEKEMINEN NÄKYY.',
        'REPEÄMÄ LOGOSSA. HÄIRIÖ JOKA TOISTUU',
        'KOSKA SE ON SIEMENETTY EIKÄ SATTUMAA.',
        'KIILLOTUS PIILOTTAA KÄDEN.',
        'MINÄ HALUAN ETTÄ NÄET KÄDEN.'],
    },
    music: {
      q: 'MITÄ KUUNTELET?',
      a: ['JOTAIN PITKÄÄ.',
        'SE ON ENIMMÄKSEEN HILJAISTA, JA SITTEN EI.',
        'LAITAN SEN SOIMAAN PIIRTÄESSÄNI JA',
        'EN KOSKAAN HUOMAA SEN LOPPUVAN.'],
    },
    faraway: {
      q: 'VAIKUTAT KAUKAISELTA.',
      a: ['OLEN TÄSSÄ.',
        'EN VAIN NÄE SYYTÄ KIIREHTIÄ.',
        'TYÖ VIE NIIN KAUAN KUIN VIE.',
        'NIIN VIE SOOLOKIN.'],
    },
    late: {
      q: 'OLET MYÖHÄÄN HEREILLÄ.',
      a: ['TÄMÄ ON PÄIVÄN PARAS OSA.',
        'KUKAAN EI OLE HEREILLÄ OLEMASSA MIELTÄ.',
        'TYÖ MENEE SIVUUN JA ANNAN SEN MENNÄ.',
        'MENE NUKKUMAAN YHDEN JÄLKEEN VIELÄ.'],
    },
    faves: {
      q: 'MITÄ SINÄ PELAAT?',
      a: ['MUIDEN PELEJÄ. JATKUVASTI.',
        'KAIKKI MISTÄ HUUDAN TULI JOSTAKIN',
        'NÄISTÄ. VALITSE YKSI.'],
    },
    mantra: {
      q: 'MIKÄ TEKEE HYVÄN PELIN?',
      a: ['VERBI.',
        'JUOKSE. AMMU. PUTOA. KAADA. ODOTA.',
        'KAIKKI MUU ON KORISTETTA VERBIN PÄÄLLÄ,',
        'JA JOS VERBI ON TYLSÄ, KORISTE ON',
        'PEITTELYÄ.'],
    },
    thirty: {
      q: 'ENTÄ ENSIMMÄISET KOLMEKYMMENTÄ SEKUNTIA?',
      a: ['NE OPETTAVAT TAPPAMALLA SINUT.',
        'EI TUTORIAALIA. EI TEKSTISEINÄÄ JOSSA',
        'ON JATKA-NAPPI.',
        'KUOLE KERRAN, YMMÄRRÄ, MENE UUDESTAAN.',
        'JOS SE PITÄÄ SELITTÄÄ, SE PITÄÄ TEHDÄ UUSIKSI.'],
    },
    feel: {
      q: 'MIKÄ ON "TUNTUMA"?',
      a: ['VÄLI PEUKALOSI JA RUUDUN VÄLILLÄ.',
        'PAINALLUS VASTAA YHDESSÄ RUUDUSSA TAI',
        'SE ON RIKKI, EIKÄ SILLÄ OLE VÄLIÄ MITEN',
        'HYVÄLTÄ MUU NÄYTTÄÄ.',
        'TÄRISTÄ KAMERAA. LIIKUTA NUMEROA.',
        'TEE OSUMASTA KATSOMISEN ARVOINEN.'],
    },
    juice: {
      q: 'EIKÖ TUO OLE VAIN MEHUA?',
      a: ['MEHU HUONON VERBIN PÄÄLLÄ VALEHTELEE.',
        'SE OSTAA SINULLE KOLMEKYMMENTÄ SEKUNTIA JA',
        'SITTEN PELAAJA HUOMAA ETTEI ALLA OLE MITÄÄN.',
        'TEE VERBI OIKEIN KUN SE ON VIELÄ RUMA.',
        'SITTEN TEE SIITÄ KOVAÄÄNINEN.'],
    },
    hard: {
      q: 'MIKSI KAIKKI ON NÄIN VAIKEAA?',
      a: ['SE EI OLE VAIKEAA. SE ON REHELLISTÄ.',
        'VIHOLLINEN ON HIDAS JA NÄKYVÄ JA SAA',
        'SINUT SILTI, ELI SE ON SINUSTA KIINNI,',
        'JA NIIN ON SEURAAVAKIN.',
        'PELI JOKA EI VOI TAPPAA SINUA EI VOI',
        'MYÖSKÄÄN ONNITELLA SINUA.'],
    },
    loop: {
      q: 'MIKÄ SAA MINUT PAINAMAAN UUDESTAAN?',
      a: ['KIERROKSEN ON OLTAVA NIIN LYHYT ETTÄ',
        'HÄVIÄMINEN ON HALVEMPAA KUIN LOPETTAMINEN.',
        'EI TALLENNUSTA. EI LATAUSRUUTUA. EI VALIKKOA',
        'OVEN JA VERBIN VÄLISSÄ.',
        'YKSI NAPPI JA OLET TAAS SISÄLLÄ.'],
    },
    creed: {
      q: 'SANO SE KOKONAAN.',
      a: ['VERBI ENSIN.',
        'YKSI RUUTU VASTATA.',
        'KUOLE, YMMÄRRÄ, MENE UUDESTAAN.',
        'LYHYET KIERROKSET. EI TALLENNUSTA.',
        'RAJOITTEET, EI NOSTALGIA.',
        'PIIRRÄ SE KOODILLA.',
        'EI TILIÄ. EI LATAAJAA. EI LUPAA.',
        'JULKAISE SE RIKKINÄINEN.',
        'MENE TEKEMÄÄN OMASI.'],
    },
    retro: {
      q: '"RAJOITTEET, EI NOSTALGIA"?',
      a: ['2600 VAIHTOI VÄRIÄ KERRAN JUOVASSA.',
        'SIKSI PALAVA TAIVAS ON LITTEITÄ PALKKEJA',
        'JOISSA ON KOVAT SAUMAT, JA SE NÄYTTÄÄ',
        'SILTÄ FYSIIKAN TAKIA, EI KOSKA KAIPAAN 1982.',
        'OTA RAJOITE. ÄLÄ OTA TUNNELMAA.'],
    },
    anarchy: {
      q: 'MIKSI KUTSUA SITÄ ANARKISTISEKSI?',
      a: ['KOSKA KUKAAN EI OLE YLÄPUOLELLASI TÄSSÄ.',
        'EI KAUPPAA JOKA PÄÄTTÄÄ MIKÄ ON OLEMASSA.',
        'EI VUOKRATTUA MOOTTORIA. EI TILIÄ JOTA',
        'PITÄÄ ANELLA SAADAKSEEN PITÄÄ.',
        'SE EI OLE ASENNE. SE ON OSOITE JA',
        'NÄYTÄ LÄHDEKOODI, JA OLET JO SISÄLLÄ.'],
    },
    browser: {
      q: 'MIKSI SELAIN?',
      a: ['SE ON VIIMEINEN PAIKKA JOSSA TUNTEMATON',
        'VOI PELATA TEKELETTÄSI YHDELLÄ KLIKKAUKSELLA.',
        'EI ASENNUSTA. EI KAUPAN TARKISTUSTA. EI 90 GT.',
        'JA LÄHDEKOODI ON SIINÄ, MIKÄ ON SE TAPA',
        'JOLLA MINÄ OPIN, JA JOLLA SINÄ OPIT.'],
    },
    start: {
      q: 'MITEN ALOITAN?',
      a: ['AVAA LÄHDEKOODI. RIKO SE.',
        'JULKAISE SE RIKKINÄINEN.',
        'KUKAAN EI OLE TULOSSA ANTAMAAN LUPAA.'],
    },
    finish: {
      q: 'MITEN SAAN SEN VALMIIKSI?',
      a: ['ET SAA. SINÄ LOPETAT.',
        'VALITSE SE YKSI ASIA JOSTA SE KERTOO JA',
        'LEIKKAA POIS KAIKKI MUU.',
        'SE PUOLIKAS JONKA POISTAT ON SE JOKA',
        'OLISI VIENYT VUODEN.'],
    },
    test: {
      q: 'MISTÄ TIEDÄN ONKO SE HYVÄ?',
      a: ['ANNA SE JONKUN TOISEN KÄSIIN JA',
        'OLE HILJAA.',
        'JOKAINEN SANA JONKA SANOT PELIN AIKANA ON',
        'ASIA JONKA PELISI JÄTTI SANOMATTA.',
        'KATSO KÄSIÄ, ÄLÄ KASVOJA.'],
    },
    bad: {
      q: 'ENTÄ JOS OLEN HUONO SIINÄ?',
      a: ['HYVÄ. SE ON ENSIMMÄINEN VERSIO TOIMIMASSA.',
        'JULKAISIN TÄMÄN LOGON KERRAN SILMÄT',
        'UMPEEN MENNEINÄ MÖYKKYINÄ.',
        'SE ON YHÄ COMMIT-LOKISSA.',
        'EN POISTANUT SITÄ. KORJASIN SEN.'],
    },
    tools: {
      q: 'MITÄ KÄYTÄT?',
      a: ['TEKSTIEDITORIA JA SELAINTA.',
        'EI MOOTTORIA. EI LATAAJAA. EI TILIÄ.',
        'LOGO JOTA KATSOT ON KUUSI KAARTA',
        'JA TAULUKKO NUMEROITA.',
        'TÄÄLLÄ EI OLE YHTÄÄN KUVATIEDOSTOA.'],
    },
    build: {
      q: 'EIKÖ BUILD-VAIHETTA?',
      a: ['EI. AVAAT TIEDOSTON JA SE TOIMII.',
        'BUILD-VAIHE ON LUKITTU OVI LAPSEN JA',
        'LÄHDEKOODIN VÄLISSÄ.',
        'MUISTAN OLLEENI SE LAPSI.'],
    },
    play: {
      q: 'MITÄ MINUN PITÄISI PELATA?',
      a: ['TÄNÄÄN? TÄMÄ.',
        'EN VALITSE UUTTA JOKA KERTA KUN KYSYT.',
        'SE ON KAUPPA. TÄMÄ ON TISKI.'],
    },
    floor: {
      q: 'MITÄ TÄÄLLÄ ON?',
      a: ['HYYTELÖLUOTIHELVETTIÄ. VOKSELIKUOPPA.',
        'LEHTIREITTI. GALLERIA-AMMUNTAA.',
        'JA HILJAINEN JOKA LÄHETTÄÄ SINUT ULOS.',
        'VALITSE KAAPPI. PAINA PELAA.'],
    },
    quiet: {
      q: 'SE HILJAINEN?',
      a: ['SEN NIMI ON THE GAME OF LIFE.',
        'SE PÄÄTTYY SIIHEN ETTÄ SE PYYTÄÄ SINUA',
        'ULOS, JA SE ON TOSISSAAN — SE TOIMII',
        'ILMAN VERKKOA.',
        'SE ON AINOA HUONE JOTA EN SIGNEERAA.',
        'LOGO SIELLÄ KUMOAISI KOKO JUTUN.'],
    },
    dead: {
      q: 'ONKO TÄÄLLÄ MITÄÄN KUOLLUTTA?',
      a: ['ON. JA SE JÄÄ LATTIALLE.',
        'ARKISTO EI OLE HAUTAUSMAA, SE ON',
        'HYLLY.',
        'NAPPI JOKA SANOO "EI PYSTYSSÄ" ON REHELLINEN.',
        'NAPPI JOKA HEITTÄÄ 404:N EI OLE.'],
    },
    about: {
      q: 'KERRO YHDESTÄ NIISTÄ.',
      a: ['MISTÄ.'],
    },
    note: {
      q: 'MINULLA ON JOTAIN SANOTTAVAA.',
      a: ['SANO SE SITTEN. KUUNTELEN.',
        'RIKKI, TYLSÄ, VÄÄRIN — KAIKKI HYÖDYLLISIÄ.',
        'EN AIO KIISTELLÄ SIITÄ KANSSASI.'],
    },
    mine: {
      q: 'MITÄ OLEN KERTONUT SINULLE?',
      a: ['SE MITÄ JÄTIT ON YHÄ KONEELLASI.',
        'TÄSSÄ SE ON.'],
    },
    changed: {
      q: 'OLIKO SILLÄ MITÄÄN MERKITYSTÄ?',
      a: ['JOLLAKIN OLI. TÄSSÄ MIKÄ LIIKKUI.'],
    },
    seen: {
      q: 'OLETKO NÄHNYT MINUN PELAAVAN?',
      a: ['VAIN SEN MITÄ KAAPIT KIRJOITTIVAT',
        'OMALLE KONEELLESI.',
        'SE EI POISTU SIELTÄ, ENKÄ VOISI LUKEA',
        'SITÄ MUUALTA VAIKKA HALUAISIN.'],
    },
    me: {
      q: 'KYSY SINÄ MINULTA JOTAIN.',
      a: ['HYVÄ ON. REILUA.',
        'MIKSI SEISOT TISKILLÄ PELISSÄ',
        'JOTA ET TEHNYT?'],
      asks: [
        {
          q: 'HALUAN JOTAIN PELATTAVAA.',
          a: ['REHELLISTÄ. MENE SITTEN — VALITSE KAAPPI.',
            'TULE TAKAISIN JA KERRO JOS SE ON HUONO.',
            'MINÄ USKON SINUA.'],
        },
        {
          q: 'HALUAN TEHDÄ TÄLLAISEN.',
          a: ['SITTEN OLET OIKEASSA HUONEESSA JA',
            'VÄÄRÄSSÄ OSASSA SITÄ.',
            'LÄHDEKOODI ON YHDEN VALIKON PÄÄSSÄ.',
            'LOPETA MINULLE PUHUMINEN.'],
        },
        {
          q: 'VÄLTTELEN TÖITÄ.',
          a: ['NIIN MINÄKIN. TÄMÄ TISKI ON',
            'VITKUTTELUA JOSSA ON LOGO.',
            'JÄÄ NIIN PITKÄKSI AIKAA KUIN HALUAT.'],
        },
        {
          q: 'EN TIEDÄ.',
          a: ['SE ON PARAS VASTAUS JONKA KUULEN.',
            'SUURIN OSA TÄSTÄ LATTIASTA ALKOI',
            'TÄSMÄLLEEN SIITÄ.'],
        },
      ],
    },
    cost: {
      q: 'MITÄ SE MAKSAA?',
      a: ['EI MITÄÄN.',
        'EI JULKAISIJAA. EI LATAAJAA. EI TILIÄ.',
        'JOS SE KUULOSTAA ANSALTA,',
        'LUE LÄHDEKOODI. SE ON SIINÄ.'],
    },
    steal: {
      q: 'VOINKO OTTAA KOODISI?',
      a: ['OTA SE. SITÄ VARTEN SE ON.',
        'ÄLÄ OTA KASVOJA — NE OVAT MINUN',
        'JA SINUN PITÄISI HALUTA OMASI JOKA TAPAUKSESSA.',
        'KAIKKI MUU: SINUN.',
        'LAITA NIMESI SIIHEN JA TEE SIITÄ HUONOMPI.'],
    },
    gift: {
      q: 'ANNA SITTEN JOTAIN.',
      a: ['TÄSSÄ. PIIRSIN SEN KUN KYSYIT.',
        'SE ON VEKTORIA, ELI MINKÄ KOKOINEN HALUAT.',
        'TULOSTA SE. LAITA SE LÄPPÄRIIN.',
        'LAITA SE JONNEKIN MIHIN SEN EI',
        'KUULUISI TULLA.'],
    },
    back: {
      q: 'OLET PUHUNUT JO HETKEN.',
      a: ['OLEN. KUKAAN EI YLEENSÄ PÄÄSE NÄIN PITKÄLLE.',
        'ELI: NAAMIO EI OLE MYSTIIKKAA, SE ON',
        'AUKI PIDETTY OVI.',
        'KUKA TAHANSA TEISTÄ VOISI SEISOA TÄSSÄ.',
        'SIINÄ KOKO VITSI JA SE ON MYÖS',
        'KOKO SUUNNITELMA.',
        'MENE TEKEMÄÄN OMASI.'],
    },
    bye: {
      q: 'EI MITÄÄN. MENEN TEKEMÄÄN JOTAIN.',
      a: ['HYVÄ.', 'MENE TEKEMÄÄN OMASI.'],
    },
  },
};
