// TOKO MIDORI GAMES — the face, TRACED from the owner's master artwork.
//
// GENERATED by toko/tools/trace-master.cjs from toko/master/face-white-on-yellow.jpg
// — do not edit by hand; re-run the tracer. The owner supplied the original on
// 2026-09-24 ("this is the exact original face shape"); until then the face was
// GEO in face.js, measured off it by eye, and that measurement differs from the
// original in ways a trace makes plain: the eyes are tall thick arches with a
// narrow slot (not a semicircle on thin parallel legs), every stroke ends in a
// slanted cut rather than a round cap, and both mouth strokes are deep U curves
// rather than arcs of a circle.
//
// Outlines are closed loops of [x, y] in the master's own 700×700 frame, y down,
// one per ink shape. Checked against both master files when traced:
//   IoU 0.9971 against the white-on-yellow original (the one traced)
//   IoU 0.9863 against the yellow-on-white original (not traced; the same
//   drawing placed 0,7 px off, compared with the ink boxes aligned)

export const MASTER = {
  size: 700,
  ground: '#FFCC00',        // the master's own ground, sampled from its corner
  ink: '#FFFFFF',
  eyeL: [191.49,159.5,200.5,158.83,214.5,159.16,226.5,161.17,236.5,164.11,247.5,169.12,255.5,174.23,261.93,179.5,266.88,184.5,271.76,190.5,275.83,196.5,281.69,207.5,286.93,221.5,289.88,232.5,292.83,248.5,294.78,264.5,296,281.5,295.97,286.5,294.89,291.5,293.52,294.5,291.5,297.29,286.5,301.77,280.5,304.69,273.5,306.76,265.5,308,257.5,307.84,250.5,305.69,247.01,303.5,242.23,298.5,240.07,294.5,238.16,288.5,237.16,281.5,235.83,264.5,233.9,251.5,230.93,238.5,226.84,228.5,222.5,222.92,220.5,221.22,216.5,219.07,208.5,217.17,199.5,217.23,195.5,218.31,191.5,220.07,188.5,222.12,184.5,225.92,179.17,233.5,175.12,242.5,172.11,252.5,170.18,261.5,168,280.5,167.8,303.5,166.88,307.5,164.88,311.5,162.3,314.5,157.5,317.93,150.5,320.69,145.5,321.84,138.5,322.97,131.5,323.16,127.5,322.83,120.5,320.84,117.5,319,114.5,316.31,111.38,311.5,110.3,308.5,109.16,299.5,109.49,282.5,111.29,261.5,114.24,244.5,118.3,229.5,123.17,216.5,130.17,202.5,136.12,193.5,143.5,184.69,152.5,176.23,159.5,171.16,170.5,165.29,182.5,161.23],
  eyeR: [483.45,159.5,487.5,159.03,499.5,158.84,512.5,160.16,523.5,163.11,532.5,166.97,538.5,170.17,544.5,174.16,553.09,181.5,557.89,186.5,562.77,192.5,568.83,201.5,574.69,212.5,580.7,227.5,585.83,246.5,588.84,265.5,590.01,280.5,589.93,305.5,587.83,312.5,585.89,315.5,581.37,319.5,576.5,321.78,572.5,322.83,566.5,323.17,559.5,322.84,549.5,320.83,543.5,318.7,538.5,315.62,535.48,312.5,533.11,308.5,532.07,304.5,531.83,282.5,530.77,270.5,527.78,253.5,524.89,243.5,519.88,232.5,513.92,224.5,511.5,222.4,506.5,219.23,499.5,217.16,490.5,217.22,482.5,219.29,479.5,221,475.7,224.5,472.3,229.5,469.06,237.5,466.29,248.5,464.16,261.5,461.97,285.5,460.7,291.5,458,297.5,455.92,300.5,453.5,302.88,448.5,305.93,443.5,307.51,439.5,308,431.5,307.83,422.5,305.84,414.5,302.51,409.5,298.91,406.11,294.5,404.16,289.5,403.7,283.5,405.16,261.5,407.23,245.5,410.22,230.5,413.3,219.5,419.3,204.5,423.17,197.5,429.39,188.5,434.5,182.7,441.5,176.22,448.5,171.22,455.5,167.3,465.5,163.3,472.5,161.31],
  mouthOuter: [149.39,350.5,157.5,351,162.5,352.41,166.5,354.3,169.5,356.38,174.62,361.5,177.83,366.5,179.69,370.5,186.3,390.5,193.17,407.5,202.17,426.5,208.3,437.5,217.11,451.5,225.11,462.5,235.09,474.5,248.5,488.09,258.5,496.71,271.5,505.96,279.5,510.83,291.5,516.84,304.5,521.89,314.5,524.79,323.5,526.77,339.5,528.78,355.5,529,369.5,527.83,385.5,524.7,398.5,520.7,412.5,514.83,423.5,508.84,435.5,500.93,449.5,489.62,460.91,478.5,468.87,469.5,479.71,455.5,487.78,443.5,495.85,429.5,503.84,413.5,513.7,389.5,520.31,369.5,522.3,365.5,524.22,362.5,527.5,358.71,533.5,354.12,540.5,351.31,545.5,350.5,550.5,350.48,555.5,351.16,562.5,353.23,569.5,357.17,574.89,362.5,577.92,368.5,578.77,372.5,578.83,375.5,577.83,380.5,573.7,394.5,568.93,408.5,562.71,424.5,551.52,448.5,541.69,466.5,530.89,483.5,517.71,501.5,504.91,516.5,487.5,533.68,471.5,546.7,453.5,558.83,434.5,568.89,417.5,575.89,397.5,581.84,388.5,583.78,375.5,585.83,356.5,587.17,334.5,586.84,311.5,583.83,298.5,580.89,287.5,577.7,269.5,570.84,260.5,566.7,249.5,560.77,229.5,547.77,213.5,534.88,196.5,518.31,181.12,500.5,172.17,488.5,162.18,473.5,151.17,454.5,145.07,442.5,139.07,429.5,131.07,409.5,125.3,392.5,121.29,378.5,121,372.5,121.38,369.5,123.49,364.5,126.3,360.5,131.5,356.17,137.5,353.07,143.5,351.23],
  mouthInner: [275.67,335.5,282.5,336.22,288.5,338.29,295.7,343.5,298.84,347.5,301.88,353.5,305.12,365.5,310.17,378.5,314.04,385.5,318.31,391.5,324.5,397.92,331.5,402.69,339.5,405.84,344.5,406.83,355.5,406.76,363.5,404.77,369.5,401.93,372.5,399.96,377.71,395.5,383.61,388.5,388.93,379.5,393.88,367.5,397.12,355.5,400.16,348.5,403.08,344.5,405.5,342.09,409.5,339.22,413.5,337.29,418.5,336,424.5,335.49,434.5,337.07,441.5,340.16,446.7,344.5,448.88,347.5,450.77,351.5,451.93,356.5,451.69,364.5,448.78,376.5,445.69,386.5,440.69,399.5,435.83,409.5,429.77,419.5,422.92,428.5,416.3,435.5,410.5,440.7,403.5,445.83,394.5,450.93,385.5,454.77,375.5,457.78,364.5,459.76,355.5,460.51,344.5,460.51,333.5,459.51,324.5,457.83,311.5,453.78,299.5,447.88,290.5,441.77,284.5,436.69,279.3,431.5,274.31,425.5,266.12,413.5,260.3,402.5,255.29,390.5,249.23,370.5,248.11,365.5,247.49,359.5,248.23,353.5,249.16,350.5,251.4,346.5,256.5,341.23,264.5,337.29,268.5,336.23],
};

// the four shapes, in drawing order
export const SHAPES = ['eyeL', 'eyeR', 'mouthOuter', 'mouthInner'];

// the ink's bounding box, in master units
export function masterBounds() {
  let x0 = Infinity, y0 = Infinity, x1 = -Infinity, y1 = -Infinity;
  for (const k of SHAPES) for (let i = 0; i < MASTER[k].length; i += 2) {
    const x = MASTER[k][i], y = MASTER[k][i + 1];
    if (x < x0) x0 = x; if (x > x1) x1 = x; if (y < y0) y0 = y; if (y > y1) y1 = y;
  }
  return { x: x0, y: y0, w: x1 - x0, h: y1 - y0 };
}

// Where each shape bends when the face acts. The master has no pupils and no
// open eye — it is the face at rest, smiling with its eyes shut — so it acts
// only as the mark always has: the eyes SQUASH (a blink) about the foot of the
// arch, and the smile BREATHES about the top of the mouth. Nothing is drawn
// that the master does not have.
export function pivots() {
  const box = (k) => { let x0 = Infinity, y0 = Infinity, x1 = -Infinity, y1 = -Infinity;
    const p = MASTER[k]; for (let i = 0; i < p.length; i += 2) { x0 = Math.min(x0, p[i]); x1 = Math.max(x1, p[i]); y0 = Math.min(y0, p[i + 1]); y1 = Math.max(y1, p[i + 1]); }
    return { x0, y0, x1, y1 }; };
  const L = box('eyeL'), R = box('eyeR'), M = box('mouthOuter');
  return {
    eyeL: [(L.x0 + L.x1) / 2, L.y1], eyeR: [(R.x0 + R.x1) / 2, R.y1],
    mouthOuter: [(M.x0 + M.x1) / 2, M.y0], mouthInner: [(M.x0 + M.x1) / 2, M.y0],
  };
}

// a point of shape `k` posed: eyes squashed about their foot, the mouth scaled
// about its top — in master units
export function posed(k, x, y, squash = 1, grin = 1, pv = pivots()) {
  const [px, py] = pv[k];
  if (k === 'eyeL' || k === 'eyeR') return [x, py + (y - py) * squash];
  return [px + (x - px) * grin, py + (y - py) * grin];
}

// Fill the traced face into a canvas: the ink box of width `w`, top-left at
// (x, y). opts: { color, squash, grin }.
export function fillMaster(ctx, x, y, w, opts = {}) {
  const b = masterBounds(), s = w / b.w, pv = pivots();
  const sq = opts.squash ?? 1, gr = opts.grin ?? 1;
  ctx.save();
  ctx.fillStyle = opts.color || MASTER.ink;
  for (const k of SHAPES) {
    const p = MASTER[k];
    ctx.beginPath();
    for (let i = 0; i < p.length; i += 2) {
      const [mx, my] = posed(k, p[i], p[i + 1], sq, gr, pv);
      const px = x + (mx - b.x) * s, py = y + (my - b.y) * s;
      i ? ctx.lineTo(px, py) : ctx.moveTo(px, py);
    }
    ctx.closePath();
    ctx.fill();
  }
  ctx.restore();
}

// The face on a disc — the badge — centred at (cx, cy), radius r. The ink is
// as wide across the disc as the brand badge's has always been.
export const BADGE_INK = 1.33;
export function drawMasterBadge(ctx, cx, cy, r, opts = {}) {
  if (opts.ground !== null) {
    ctx.save(); ctx.fillStyle = opts.ground || MASTER.ground;
    ctx.beginPath(); ctx.arc(cx, cy, r, 0, Math.PI * 2); ctx.fill(); ctx.restore();
  }
  // placed by the master's FRAME, not its ink: the original sits a little low
  // in its own square, and that is part of the drawing
  const b = masterBounds(), s = (r * BADGE_INK) / b.w, c = MASTER.size / 2;
  fillMaster(ctx, cx + (b.x - c) * s, cy + (b.y - c) * s, r * BADGE_INK,
    { color: opts.ink || MASTER.ink, squash: opts.squash, grin: opts.grin });
}
