import wire from './news-wire.js';
const STATE_KEY='tokoNewsSourceState.v1',read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}},SOURCES=new Map();
export function registerSource(source){if(!source?.id||typeof source.fetch!=='function')throw new Error('news source needs id + fetch()');SOURCES.set(source.id,source);return source}export function listSources(){return[...SOURCES.values()].map(({fetch,...s})=>s)}export function sourceState(){return read(STATE_KEY,{})}function stamp(id,patch){const s=sourceState();s[id]={...(s[id]||{}),...patch};write(STATE_KEY,s)}async function getJSON(url){const r=await fetch(url,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.json()}
registerSource({id:'hn',label:'HACKER NEWS',category:'technology',async fetch(){const d=await getJSON('https://hn.algolia.com/api/v1/search_by_date?tags=story&hitsPerPage=25');return(d.hits||[]).filter(x=>x.title).map(x=>({id:`hn:${x.objectID}`,title:x.title,url:x.url||`https://news.ycombinator.com/item?id=${x.objectID}`,source:'Hacker News',category:'technology',published:x.created_at}))}});
registerSource({id:'helsinki-events',label:'HELSINKI EVENTS',category:'helsinki',async fetch(){const start=new Date().toISOString().slice(0,10),d=await getJSON(`https://api.hel.fi/linkedevents/v1/event/?start=${start}&sort=start_time&page_size=25`);return(d.data||[]).map(x=>({id:`hel:${x.id}`,title:x.name?.en||x.name?.fi||'Helsinki event',url:x.info_url?.en||x.info_url?.fi||null,summary:(x.short_description?.en||x.short_description?.fi||'').replace(/<[^>]+>/g,' '),source:'Helsinki Linked Events',category:'helsinki',published:x.start_time}))}});
function gdelt(id,label,category,query){registerSource({id,label,category,async fetch(){const d=await getJSON('https://api.gdeltproject.org/api/v2/doc/doc?mode=ArtList&maxrecords=20&format=json&sort=HybridRel&query='+encodeURIComponent(query));return(d.articles||[]).filter(x=>x.title&&x.url).map((x,i)=>({id:`gdelt:${id}:${i}:${x.url}`,title:x.title,url:x.url,summary:x.seendate?`Seen ${x.seendate}`:'',source:x.domain||label,category,published:x.seendate||new Date().toISOString()}))}})}
gdelt('games','GAMES DISCOVERY','games','("video game" OR videogame OR gaming)');gdelt('industry','GAME INDUSTRY DISCOVERY','industry','("game studio" OR "video game industry" OR "game publisher" OR "game developer")');gdelt('art','ART / CULTURE DISCOVERY','art','(museum OR gallery OR exhibition OR "digital art" OR "media art")');
registerSource({id:'rfh-sourced',label:'HELSINKI FREE RADIO / SOURCED',category:'industry',async fetch(){const idx=await getJSON('../radiofree/wire/index.json'),date=Array.isArray(idx.episodes)?idx.episodes[0]:null;if(!date)return[];const ep=await getJSON(`../radiofree/wire/${date}.json`),copy=ep.copy?.en||{};return(ep.stories||[]).filter(s=>s.sourced===true&&copy[s.id]).map(s=>({id:`rfh:${date}:${s.id}`,title:copy[s.id].head,url:`../radiofree/?date=${date}#${s.id}`,summary:(copy[s.id].lines||[]).join(' '),source:'Helsinki Free Radio',category:'industry',published:s.filed||date}))}});
export async function refreshSource(id){const source=SOURCES.get(id);if(!source)throw new Error(`unknown news source: ${id}`);stamp(id,{status:'loading'});try{const items=await source.fetch();wire.ingest(items.map(x=>({...x,category:x.category||source.category,source:x.source||source.label})),id);stamp(id,{status:'ok',updated:new Date().toISOString(),count:items.length});return items}catch(err){stamp(id,{status:'error',error:String(err?.message||err)});return[]}}
export async function refreshAll(){return Promise.all([...SOURCES.keys()].map(refreshSource))}let booted=false;export async function bootLiveNews(){if(booted||navigator?.onLine===false)return[];booted=true;return refreshAll()}globalThis.TokoNewsSources={registerSource,listSources,sourceState,refreshSource,refreshAll,bootLiveNews};queueMicrotask(()=>bootLiveNews().catch(()=>{}));