import * as THREE from 'three';
import { Bunny } from './shared.js?v=12';
import { Enemy } from './enemy.js?v=12';

// SKLTR v69-v72 — hero art pass. Adds authored landmark silhouettes and a richer
// stylized player/enemy surface layer without touching gameplay collision or roles.
let scene=null,root=null,state='wire',time=0;
const movers=[];
const PAL={wire:{dark:0x03050a,mid:0x08202a,edge:0xa7f5ff,accent:0xffd34d},brutal:{dark:0x4f493f,mid:0x8c8374,edge:0x221d18,accent:0xe3bf73},bio:{dark:0x0e071a,mid:0x23113b,edge:0x75ffe6,accent:0xff58d6},physical:{dark:0x242a2f,mid:0x697177,edge:0xe9e4d8,accent:0x93d9ff},kill:{dark:0x170102,mid:0x4a0808,edge:0xffc1b5,accent:0xff382c}};
function which(n=''){if(n.includes('TORTOISE'))return'brutal';if(n.includes('WASP'))return'bio';if(n.includes('MACHINE'))return'physical';if(n.includes('KILL')||n.includes('LAST'))return'kill';return'wire'}
function mat(c,rough=.72,metal=.18,em=0){return new THREE.MeshStandardMaterial({color:c,roughness:rough,metalness:metal,emissive:em})}
function mesh(g,geo,c,x,y,z,rough=.72,metal=.18,em=0){const m=new THREE.Mesh(geo,mat(c,rough,metal,em));m.position.set(x,y,z);m.castShadow=m.receiveShadow=true;g.add(m);return m}
function edge(g,obj,c,op=.62){const e=new THREE.LineSegments(new THREE.EdgesGeometry(obj.geometry),new THREE.LineBasicMaterial({color:c,transparent:true,opacity:op}));e.position.copy(obj.position);e.rotation.copy(obj.rotation);e.scale.copy(obj.scale);g.add(e);return e}
function pillar(g,x,z,h,p){const m=mesh(g,new THREE.BoxGeometry(3.4,h,3.4),p.dark,x,h/2,z,.82,.16);edge(g,m,p.edge,.38);return m}
function heroWire(g,p){for(const s of[-1,1]){const base=pillar(g,s*50,42,34,p);base.rotation.z=s*.10;const crown=mesh(g,new THREE.OctahedronGeometry(6,0),p.mid,s*50,38,42,.45,.35,p.mid);edge(g,crown,p.edge,.7);movers.push({o:crown,type:'spin',v:s*.0028})}const gate=mesh(g,new THREE.TorusGeometry(21,.42,7,64),p.mid,0,18,56,.4,.25,p.mid);gate.rotation.x=Math.PI/2;movers.push({o:gate,type:'spinY',v:.002});for(let i=0;i<5;i++){const y=4+i*5;const r=8+i*2;const q=mesh(g,new THREE.TorusGeometry(r,.08,5,48),p.edge,0,y,-50+i*4,.3,.1,p.edge);q.rotation.x=Math.PI/2;movers.push({o:q,type:'pulse',base:1,amp:.08,s:.7+i*.1})}}
function heroBrutal(g,p){const tower=mesh(g,new THREE.BoxGeometry(18,42,14),p.mid,-48,21,34,.95,.04);edge(g,tower,p.edge,.3);const cut=mesh(g,new THREE.BoxGeometry(34,8,12),p.dark,42,12,-36,.95,.04);cut.rotation.z=-.18;edge(g,cut,p.edge,.35);for(const [x,z] of[[-48,34],[42,-36]])for(let i=0;i<4;i++){const q=mesh(g,new THREE.BoxGeometry(2.5,.45,7),p.accent,x+(i-1.5)*4,3+i*6,z-7,.55,.1);q.rotation.y=.2*(i-1.5)}const bridge=mesh(g,new THREE.BoxGeometry(56,2.2,5),p.dark,0,24,58,.9,.05);edge(g,bridge,p.edge,.3)}
function heroBio(g,p){const core=mesh(g,new THREE.IcosahedronGeometry(7,1),p.mid,0,28,54,.38,.32,p.mid);movers.push({o:core,type:'spin',v:.004});for(let i=0;i<8;i++){const a=i/8*Math.PI*2,r=18;const stalk=mesh(g,new THREE.CylinderGeometry(.6,1.4,22,7),p.dark,Math.cos(a)*r,13,54+Math.sin(a)*r,.5,.3);stalk.rotation.z=Math.sin(a)*.2;const bulb=mesh(g,new THREE.SphereGeometry(2.4,10,8),i%2?p.edge:p.accent,Math.cos(a)*r,25,54+Math.sin(a)*r,.32,.2,i%2?p.edge:p.accent);movers.push({o:bulb,type:'bob',baseY:25,amp:1.4,s:.8+i*.06})}for(const y of[12,20,30]){const q=mesh(g,new THREE.TorusGeometry(15+y*.3,.18,6,64),p.edge,0,y,54,.3,.15,p.edge);q.rotation.x=Math.PI/2;movers.push({o:q,type:'spinY',v:.003+y*.00005})}}
function heroPhysical(g,p){const crane=new THREE.Group();g.add(crane);const mast=mesh(crane,new THREE.BoxGeometry(5,34,5),p.dark,-48,17,34,.58,.62);const jib=mesh(crane,new THREE.BoxGeometry(42,2.4,2.6),p.mid,-31,33,34,.5,.55);const cab=mesh(crane,new THREE.BoxGeometry(7,5,6),p.mid,-44,29,34,.42,.48);edge(crane,mast,p.edge,.25);edge(crane,jib,p.edge,.25);edge(crane,cab,p.edge,.25);const hook=new THREE.Group();crane.add(hook);const line=mesh(hook,new THREE.CylinderGeometry(.09,.09,13,6),p.edge,0,-6.5,0,.3,.7);const load=mesh(hook,new THREE.BoxGeometry(5,3,5),p.accent,0,-14,0,.45,.6);hook.position.set(-24,31,34);movers.push({o:hook,type:'slideX',a:-31,b:-12,s:.42});for(const [x,z] of[[48,-30],[44,36]]){const silo=mesh(g,new THREE.CylinderGeometry(7,8,22,12),p.mid,x,11,z,.55,.48);edge(g,silo,p.edge,.2);const cap=mesh(g,new THREE.ConeGeometry(7.4,4,12),p.dark,x,24,z,.58,.4);edge(g,cap,p.edge,.2)}}
function heroKill(g,p){for(let i=0;i<5;i++){const a=i/5*Math.PI*2,r=56;const mon=mesh(g,new THREE.ConeGeometry(5,28,4),p.mid,Math.cos(a)*r,14,Math.sin(a)*r,.42,.38,p.mid);mon.rotation.y=a;movers.push({o:mon,type:'pulse',base:1,amp:.09,s:.9+i*.12})}const eye=mesh(g,new THREE.TorusGeometry(18,.38,8,64),p.accent,0,22,54,.35,.2,p.accent);eye.rotation.x=Math.PI/2;movers.push({o:eye,type:'spinY',v:.006})}
function buildWorld(k){if(!scene)return;if(root)scene.remove(root);movers.length=0;root=new THREE.Group();root.name='SKLTR_V72_HERO_ART';scene.add(root);const p=PAL[k];({wire:heroWire,brutal:heroBrutal,bio:heroBio,physical:heroPhysical,kill:heroKill}[k])(root,p);root.scale.y=.06;state=k}
function tick(){time+=.016;if(root)root.scale.y+=(1-root.scale.y)*.05;for(const m of movers){if(m.type==='spin')m.o.rotation.y+=m.v;else if(m.type==='spinY')m.o.rotation.z+=m.v;else if(m.type==='bob')m.o.position.y=m.baseY+Math.sin(time*m.s)*m.amp;else if(m.type==='slideX')m.o.position.x=THREE.MathUtils.lerp(m.a,m.b,(Math.sin(time*m.s)+1)/2);else if(m.type==='pulse'){const s=m.base+Math.sin(time*m.s)*m.amp;m.o.scale.setScalar(s)}}requestAnimationFrame(tick)}
const oldAdd=THREE.Scene.prototype.add;THREE.Scene.prototype.add=function(...o){const r=oldAdd.apply(this,o);if(this.isScene&&!scene){scene=this;queueMicrotask(()=>buildWorld('wire'))}return r};
addEventListener('skltr-arena',e=>{const k=which(e.detail?.arena||'');if(k!==state)buildWorld(k)});tick();

// Player hero layer: clean helmet shell, stronger torso planes, articulated pads.
const baseBunny=Bunny.prototype.update;
function addOutlined(parent,geo,c,edgeC,pos){const g=new THREE.Group();const m=new THREE.Mesh(geo,mat(c,.5,.26));m.castShadow=true;g.add(m);g.add(new THREE.LineSegments(new THREE.EdgesGeometry(geo),new THREE.LineBasicMaterial({color:edgeC})));g.position.set(...pos);parent.add(g);return g}
function buildPlayer(b){if(b._v72)return;b._v72=true;const face=b._tokoFace?.group;for(const c of b.head.children)c.visible=(c===face||c.userData?.v72keep);const helmet=addOutlined(b.head,new THREE.BoxGeometry(.48,.52,.34),0x080b13,0xe9fbff,[0,.015,0]);helmet.userData.v72keep=true;if(face){face.visible=true;face.position.set(0,.005,-.183);face.scale.setScalar(.72);b.head.add(face)}const collar=addOutlined(b.chest,new THREE.BoxGeometry(.86,.11,.42),0x101722,0x9bfff0,[0,.29,-.01]);const breast=addOutlined(b.chest,new THREE.BoxGeometry(.5,.39,.08),0x1b222c,0xffd34d,[0,.02,-.22]);const waist=addOutlined(b.chest,new THREE.BoxGeometry(.54,.09,.34),0x12161d,0xffd34d,[0,-.36,0]);for(const [limb,x] of[[b.armL,-1],[b.armR,1]])if(limb){const pad=addOutlined(limb,new THREE.BoxGeometry(.16,.18,.16),0x151b24,0x9bfff0,[0,-.14,0]);pad.rotation.z=x*.08}for(const leg of[b.hipL,b.hipR])if(leg)addOutlined(leg,new THREE.BoxGeometry(.18,.20,.18),0x151b24,0xe9fbff,[0,-.15,0]);}
Bunny.prototype.update=function(dt,s={}){const r=baseBunny.call(this,dt,s);buildPlayer(this);return r};

// Enemy hero accents: identifiable armored nodes per role; silhouette stays unchanged.
const baseEnemy=Enemy.prototype.update;
function addEnemyArt(e){if(e._v72art||!e.mesh||e.boss)return;e._v72art=true;const p=PAL[state];const g=new THREE.Group();g.userData.v72hero=true;e.mesh.add(g);if(e.type==='chaser'){for(const x of[-.22,.22]){const q=mesh(g,new THREE.ConeGeometry(.09,.34,5),p.accent,x,.38,-.18,.35,.25,p.accent);q.rotation.x=Math.PI}}else if(e.type==='turret'){const q=mesh(g,new THREE.TorusGeometry(.48,.055,5,24),p.accent,0,.18,0,.35,.3,p.accent);q.rotation.x=Math.PI/2}else if(e.type==='flyer'){for(const x of[-.62,.62]){const q=mesh(g,new THREE.OctahedronGeometry(.17,0),p.accent,x,.02,0,.3,.2,p.accent);movers.push({o:q,type:'pulse',base:1,amp:.12,s:1.5})}}}
Enemy.prototype.update=function(...a){const r=baseEnemy.apply(this,a);addEnemyArt(this);return r};
window._skltrHero72=()=>({state,movers:movers.length});
