import * as THREE from 'three';
import { Bunny, C } from './shared.js?v=12';
import { visualTest } from './modes.js?v=12';
const ADR_THRESH=[3,6,10,15,21],ADR_TINT=[null,0x7a4a10,0x995408,0xb35b00,0xc24a00,0xd03b3b],STEP_MAX=.6;
// v29 tune: a tighter close-pass test, slightly longer conversion window, same meaningful payoff.
const FLOW_NEAR=1.6,FLOW_MAX=3,FLOW_LIFE=3.2,FLOW_DMG=.10,AIR_KILL_ADR=.5;
const BASE={damage:9,fireInterval:.11,moveSpeed:8.8,sprintMul:1.45,maxHp:100,dashCD:.84,dashSpeed:35,dashTime:.22,dashHoldMax:.44,iframe:.3,airDashSpeed:31,jumpV:11,gravUp:24,gravDown:34,apexBand:2.5,apexHang:.55,groundAccel:30,airAccel:7,dashAccel:1.5};
export class Player{
constructor(scene,pool){this.scene=scene;this.pool=pool;this.fig=new Bunny(scene);this.autoAim=true;this.reset();}
reset(o={}){this._stats={maxHp:o.maxHp??BASE.maxHp,dashCD:o.dashCD??BASE.dashCD,fireInterval:o.fireInterval??BASE.fireInterval,iframe:o.iframe??BASE.iframe};this.x=0;this.z=0;this.y=0;this.vy=0;this.vx=0;this.vz=0;this.yaw=0;this.hp=this._stats.maxHp;this.maxHp=this._stats.maxHp;this.fireT=0;this.dashCD=0;this.dashT=0;this.iframe=0;this.dashing=false;this.dashElapsed=0;this.dashDirX=0;this.dashDirZ=0;this._dashGround=true;this.airDashUsed=false;this.airJumpUsed=false;this._fired=false;this._target=false;this.adr=o.startAdr||0;this.adrKills=this.adr?ADR_THRESH[this.adr-1]:0;this.flowStacks=0;this.flowT=0;this._dashTagged=new Set;this.flowPulse=false;this.alive=true;this.groundY=0;this.fig.visible(true)}
grounded(){return this.y<=this.groundY+.02}adrDmgMul(){return 1+.06*this.adr}adrFireMul(){return 1/(1+.08*this.adr)}flowDmgMul(){return 1+FLOW_DMG*this.flowStacks}addKill(){this.adrKills+=1+(!this.grounded()?AIR_KILL_ADR:0);if(!this.grounded())this.flowT=Math.max(this.flowT,FLOW_LIFE);let t=0;for(const k of ADR_THRESH)if(this.adrKills>=k)t++;this.adr=t}
jump(){if(this.alive&&this.grounded()){this.vy=BASE.jumpV;return true}return false}doubleJump(){if(this.alive&&!this.grounded()&&!this.airJumpUsed){this.vy=BASE.jumpV;this.airJumpUsed=true;return true}return false}
_startDash(d,g){this.dashing=true;this.dashElapsed=0;this._dashGround=g;this.dashDirX=d.x;this.dashDirZ=d.z;this.dashT=BASE.dashTime;this.iframe=this._stats.iframe;this._dashTagged.clear();const s=g?BASE.dashSpeed:BASE.airDashSpeed;this.vx=d.x*s;this.vz=d.z*s}groundDash(d){if(!this.alive||!this.grounded()||this.dashCD>0||this.dashing)return false;this._startDash(d,true);return true}airDash(d){if(!this.alive||this.grounded()||this.airDashUsed||this.dashing)return false;this.airDashUsed=true;this.vy=0;this._startDash(d,false);return true}
_aim(a,en){let bx=a.fx,by=a.fy,bz=a.fz,best=.9,locked=false;for(const e of en){if(!e.alive)continue;const dx=e.x-this.x,dy=e.y-1.25,dz=e.z-this.z,d=Math.hypot(dx,dy,dz);if(d<.1||d>42)continue;const dot=dx/d*a.fx+dy/d*a.fy+dz/d*a.fz;if(dot>best){best=dot;bx=dx/d;by=dy/d;bz=dz/d;locked=true}}return{x:bx,y:by,z:bz,locked}}
_fire(d){this.fireT=this._stats.fireInterval*this.adrFireMul();const dmg=BASE.damage*this.adrDmgMul()*this.flowDmgMul();this.pool.spawn(this.x+d.x*.4,1.25+d.y*.4,this.z+d.z*.4,d.x,d.y,d.z,{fromPlayer:true,speed:46,damage:dmg,color:C.shot,r:.4,life:1.6});this._fired=true}
_movementOffense(dt,en){this.flowPulse=false;if(this.flowT>0){this.flowT=Math.max(0,this.flowT-dt);if(this.flowT===0)this.flowStacks=0}if(!this.dashing)return;for(const e of en){if(!e.alive||e.boss||this._dashTagged.has(e))continue;if(Math.hypot(e.x-this.x,e.z-this.z)>e.r+FLOW_NEAR)continue;this._dashTagged.add(e);this.flowStacks=Math.min(FLOW_MAX,this.flowStacks+1);this.flowT=FLOW_LIFE;this.flowPulse=true}}
hurt(d){if(!this.alive||this.iframe>0)return;this.hp-=d;this.fig.hit();this.adr=0;this.adrKills=0;this.flowStacks=0;this.flowT=0;this._dashTagged.clear();if(this.hp<=0){this.hp=0;this.alive=false;this.fig.visible(false)}}heal(a){this.hp=Math.min(this.maxHp,this.hp+a)}
update(dt,input,aim,en,heightAt=()=>0,drift=null){this._fired=false;this.fireT=Math.max(0,this.fireT-dt);this.dashCD=Math.max(0,this.dashCD-dt);this.dashT=Math.max(0,this.dashT-dt);this.iframe=Math.max(0,this.iframe-dt);if(!this.alive)return;const sy=Math.sin(aim.yaw),cy=Math.cos(aim.yaw),f={x:-sy,z:-cy},r={x:cy,z:-sy},mv=input.getMove(),sprint=input.sprint&&Math.hypot(mv.x,mv.z)>.1,spd=BASE.moveSpeed*(sprint?BASE.sprintMul:1);let dx=f.x*mv.z+r.x*mv.x,dz=f.z*mv.z+r.z*mv.x,m=Math.hypot(dx,dz);if(m>.001){dx/=m;dz/=m}const tvx=dx*spd+(drift?drift.x:0),tvz=dz*spd+(drift?drift.z:0),acc=this.dashT>0?BASE.dashAccel:(this.grounded()?BASE.groundAccel:BASE.airAccel);this.vx+=(tvx-this.vx)*Math.min(1,dt*acc);this.vz+=(tvz-this.vz)*Math.min(1,dt*acc);if(this.dashing){this.dashElapsed+=dt;const active=this.dashElapsed<BASE.dashTime||(input.dashHeld&&this.dashElapsed<BASE.dashHoldMax);if(active){const s=this._dashGround?BASE.dashSpeed:BASE.airDashSpeed;this.vx=this.dashDirX*s;this.vz=this.dashDirZ*s;this.dashT=.06}else{this.dashing=false;this.dashCD=this._stats.dashCD;const s=Math.hypot(this.vx,this.vz),cap=BASE.moveSpeed*1.15;if(s>cap){this.vx*=cap/s;this.vz*=cap/s}}}const px=this.x,pz=this.z;this.x+=this.vx*dt;this.z+=this.vz*dt;const grav=(this.vy>0?BASE.gravUp:BASE.gravDown)*(Math.abs(this.vy)<BASE.apexBand?BASE.apexHang:1);this.vy-=grav*dt;this.y+=this.vy*dt;const ground=heightAt(this.x,this.z);if(ground-this.y>STEP_MAX&&this.vy<=.1){this.x=px;this.z=pz;const g=heightAt(this.x,this.z);this.groundY=g;if(this.y<=g){this.y=g;this.vy=0;this.airDashUsed=false;this.airJumpUsed=false}}else{this.groundY=ground;if(this.y<=ground){this.y=ground;this.vy=0;this.airDashUsed=false;this.airJumpUsed=false}}this._movementOffense(dt,en);this.yaw=aim.yaw;this.fig.group.position.set(this.x,this.y,this.z);this.fig.group.rotation.y=this.yaw;const ar=this._aim(aim,en),want=!sprint&&((this.autoAim&&ar.locked)||input.firing);this._target=ar.locked;if(want&&this.fireT<=0)this._fire(ar);this.fig.update(dt,{speed:Math.hypot(this.vx,this.vz),aimPitch:aim.pitch,yOffset:this.y,airborne:!this.grounded(),dashing:this.dashT>0,firing:this._fired,vy:this.vy,accent:visualTest?ADR_TINT[this.adr]:null})}}
