import * as THREE from 'three';

// SKLTR v61-v64 — high-detail world layer: depth bands, landmarks and restrained motion.
let scene=null,root=null,state='wire',t=0;
const movers=[];
const C={wire:{a:0xa7f5ff,b:0x2acfff,d:0x061018},brutal:{a:0x201b16,b:0xe0c89a,d:0x5b554c},bio:{a:0x75ffe6,b:0xff58d6,d:0x100921},physical:{a:0xe9e4d8,b:0x93d9ff,d:0x343a3f},kill:{a:0xffc1b5,b:0xff382c,d:0x210202}};
function which(n=''){if(n.includes('TORTOISE'))return'brutal';if(n.includes('WASP'))return'bio';if(n.includes('MACHINE'))return'physical';if(n.includes('KILL')||n.includes('LAST'))return'kill';return'wire'}
function std(c,rough=.82,metal=.12){return new THREE.MeshStandardMaterial({color:c,roughness:rough,metalness:metal})}
function basic(c,op=.5){return new THREE.MeshBasicMaterial({color:c,transparent:true,opacity:op})}
function box(g,x,y,z,w,h,d,c,rough=.82,metal=.12){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),std(c,rough,metal));m.position.set(x,y+h/2,z);g.add(m);return m}
function beam(g,a,b,c,op=.4){const l=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(...a),new THREE.Vector3(...b)]),new THREE.LineBasicMaterial({color:c,transparent:true,opacity:op}));g.add(l);return l}
function ring(g,x,y,z,r,c,op=.4){const m=new THREE.Mesh(new THREE.TorusGeometry(r,.08,5,48),basic(c,op));m.position.set(x,y,z);m.rotation.x=Math.PI/2;g.add(m);return m}
function light(g,x,y,z,c,int=.7,dist=18){const l=new THREE.PointLight(c,int,dist,2);l.position.set(x,y,z);g.add(l);return l}
function horizonWire(g,p){for(let i=0;i<18;i++){const a=i/18*Math.PI*2,r=66+(i%4)*5,h=8+(i%6)*7,x=Math.cos(a)*r,z=Math.sin(a)*r;beam(g,[x,0,z],[x,h,z],p.a,.26);if(i%3===0)beam(g,[x,h,z],[Math.cos(a+.15)*r,h+4,Math.sin(a+.15)*r],p.b,.2)}for(const r of[58,70,82])ring(g,0,.05,0,r,p.a,.12)}
function brutalDetail(g,p){for(let i=0;i<8;i++){const side=i%2?-1:1,x=side*(47+(i%3)*5),z=-50+i*14;box(g,x,0,z,7+(i%3)*3,14+(i%4)*7,16,p.d,.9,.05)}for(const z of[-34,0,34]){box(g,-20,.1,z,4,.35,5,p.b,.7,.08);box(g,20,.1,z,4,.35,5,p.b,.7,.08)}box(g,0,0,60,52,4,5,p.d,.9,.04)}
function bioDetail(g,p){for(let i=0;i<8;i++){const a=i/8*Math.PI*2,r=54,x=Math.cos(a)*r,z=Math.sin(a)*r,stalk=box(g,x,0,z,1.1,18+(i%3)*5,1.1,p.d,.5,.28);stalk.rotation.z=Math.sin(a)*.18;const r1=ring(g,x,12+(i%3)*3,z,4+(i%2)*1.5,p.a,.45);r1.rotation.y=a;movers.push({o:r1,type:'spin',v:(i%2?1:-1)*.005});if(i%2===0)light(g,x,15,z,p.b,.55,15)}for(let i=0;i<12;i++){const a=i/12*Math.PI*2,r=62;beam(g,[Math.cos(a)*r,1,Math.sin(a)*r],[Math.cos(a)*r,23+(i%4)*5,Math.sin(a)*r],i%3?p.a:p.b,.16)}}
function machineDetail(g,p){for(const z of[-40,40])for(const x of[-30,-10,10,30])box(g,x,0,z,8,5+(Math.abs(x)%7),6,p.d,.62,.32);const rail=box(g,0,16,18,58,.45,.45,p.a,.4,.55);rail.position.y=16;const trolley=box(g,-24,15.6,18,4,2.4,3,p.b,.42,.52);movers.push({o:trolley,type:'slide',axis:'x',a:-24,b:24,s:.32});const hook=new THREE.Group();g.add(hook);beam(hook,[0,0,0],[0,-8,0],p.a,.65);box(hook,0,-9,0,1.8,1.8,1.8,p.b,.45,.5);hook.position.set(24,25,-34);movers.push({o:hook,type:'bob',baseY:25,amp:2.5,s:.8});for(const x of[-34,34]){light(g,x,10,0,p.b,.65,22);const beacon=ring(g,x,10,0,1.3,p.b,.5);movers.push({o:beacon,type:'spin',v:.012*(x<0?-1:1)})}}
function killDetail(g,p){for(let i=0;i<9;i++){const a=i/9*Math.PI*2,r=62,m=box(g,Math.cos(a)*r,0,Math.sin(a)*r,3,14+(i%4)*7,3,p.d,.5,.3);m.rotation.z=.08*Math.sin(a);const q=ring(g,m.position.x,7+(i%4)*4,m.position.z,3.5,p.b,.35);movers.push({o:q,type:'spin',v:.008*(i%2?1:-1)})}}
function build(k){if(!scene)return;if(root)scene.remove(root);movers.length=0;root=new THREE.Group();root.name='SKLTR_V64_WORLD_DETAIL';scene.add(root);const p=C[k];if(k==='wire')horizonWire(root,p);else if(k==='brutal')brutalDetail(root,p);else if(k==='bio')bioDetail(root,p);else if(k==='physical')machineDetail(root,p);else killDetail(root,p);const far=new THREE.Group();far.name='BACKGROUND_BAND';root.add(far);for(let i=0;i<14;i++){const a=i/14*Math.PI*2,r=78+(i%3)*7,h=6+(i%5)*6;box(far,Math.cos(a)*r,0,Math.sin(a)*r,4+(i%2)*3,h,5,p.d,.92,.06)}root.scale.y=.06;state=k}
function tick(){t+=.016;if(root)root.scale.y+=(1-root.scale.y)*.055;for(const m of movers){if(m.type==='spin')m.o.rotation.z+=m.v;else if(m.type==='slide'){const u=(Math.sin(t*m.s)+1)/2;m.o.position[m.axis]=THREE.MathUtils.lerp(m.a,m.b,u)}else if(m.type==='bob')m.o.position.y=m.baseY+Math.sin(t*m.s)*m.amp}requestAnimationFrame(tick)}
const oldAdd=THREE.Scene.prototype.add;THREE.Scene.prototype.add=function(...o){const r=oldAdd.apply(this,o);if(this.isScene&&!scene){scene=this;queueMicrotask(()=>build('wire'))}return r};
addEventListener('skltr-arena',e=>{const k=which(e.detail?.arena||'');if(k!==state)build(k)});tick();
window._skltrWorldDetail64=()=>({state,movers:movers.length});
