// Toko Move daylight smoke gate — catch existing HSL services on real Helsinki geography.
const { chromium } = require('playwright');
const http = require('http'); const fs = require('fs'); const path = require('path');
const ROOT = path.resolve(__dirname, '..', '..');
const MIME = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.json': 'application/json' };
const s = http.createServer((req, res) => { let p = path.join(ROOT, decodeURIComponent(req.url.split('?')[0])); if (fs.existsSync(p) && fs.statSync(p).isDirectory()) p = path.join(p, 'index.html'); if (!fs.existsSync(p)) { res.writeHead(404); return res.end('no'); } res.writeHead(200, { 'Content-Type': MIME[path.extname(p)] || 'application/octet-stream' }); fs.createReadStream(p).pipe(res); });
let pass=0,fail=0; const ok=(n,c,d)=>{c?(pass++,console.log('  ok   '+n)):(fail++,console.log('  FAIL '+n+(d?' → '+d:'')));};
const PHONE={width:390,height:780};
s.listen(0,'127.0.0.1',async()=>{const base='http://127.0.0.1:'+s.address().port,b=await chromium.launch(),p=await b.newPage({viewport:PHONE}),errs=[];p.on('pageerror',e=>errs.push('pageerror: '+e.message));p.on('console',m=>{if(m.type()==='error')errs.push('console: '+m.text());});
 await p.goto(base+'/toko-move/'); await p.waitForTimeout(1000);
 ok('boots with no errors',errs.length===0,errs.slice(0,2).join(' | '));
 ok('delivery handle is exposed',await p.evaluate(()=>!!window.__tm?.challenge));
 ok('real Helsinki graph is active',await p.evaluate(()=>{const ids=new Set([...window.__tm.flow.graph.nodes.keys()]),city=window.__tm.city;return ['pasila','toolontori','hakaniemi','kamppi','rautatientori','sornainen','kalasatama','kauppatori'].every(x=>ids.has(x))&&city?.source?.exactGeometry===true&&city.nodes.every(n=>Number.isFinite(n.lat)&&Number.isFinite(n.lon)&&n.hslStopId);}));
 ok('first job waits for the player to catch a service',await p.evaluate(()=>{const ch=window.__tm.challenge;return !!ch.active&&ch.waitingForCatch===true&&ch.activeTrip===null;}));
 ok('all source transit layers remain visible',await p.evaluate(()=>window.__tm.transit.layers.length>20&&window.__tm.transit.layers.every(l=>l.visible)));
 await p.click('#play'); await p.waitForTimeout(450);
 ok('clock runs after start',await p.evaluate(()=>!window.__tm.flow.clock.paused));
 ok('catch choices are visible',await p.evaluate(()=>document.querySelectorAll('.catchChoice').length>=1));
 const before=await p.evaluate(()=>window.__tm.flow.routes.drawn.length); await p.click('.catchChoice'); await p.waitForTimeout(250);
 ok('catch commits an existing HSL service plan',await p.evaluate(()=>{const ch=window.__tm.challenge;return !!ch.activeTrip&&!ch.waitingForCatch&&Array.isArray(ch.activeTrip.legs)&&ch.activeTrip.legs.length>=1;}));
 ok('catching creates no player-drawn line',await p.evaluate(n=>window.__tm.flow.routes.drawn.length===n,before));
 ok('fixed services come from HSL tram + metro',await p.evaluate(()=>{const rs=window.__tm.flow.routes.list.filter(r=>r.fixed);return rs.some(r=>r.mode==='metro'&&(r.label==='M1'||r.label==='M2'))&&rs.some(r=>r.mode==='tram'&&['2','3','4','5','6','7','8H','8T','9','13'].includes(r.label))&&!rs.some(r=>['T','R','M'].includes(r.label));}));
 ok('gameplay HUD identifies HSL network rather than line budget',await p.evaluate(()=>document.getElementById('lines').textContent.includes('HSL')));
 ok('large visible version matches runtime',await p.evaluate(()=>document.querySelector('.versionHero')?.textContent.includes(`v${window.__tm.version}`)));
 ok('no horizontal phone overflow',await p.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));
 const small=await p.$$eval('button',bs=>bs.filter(x=>{const r=x.getBoundingClientRect();return r.width>0&&(r.width<44||r.height<44);}).map(x=>x.id||x.textContent.trim().slice(0,16)));ok('controls clear 44px',small.length===0,small.join(', '));
 ok('no encounter layer in daylight product',await p.evaluate(()=>!document.getElementById('fight')));
 ok('still no errors after catch',errs.length===0,errs.slice(0,2).join(' | '));
 await p.close();await b.close();s.close();console.log(`\n  ${pass} passed, ${fail} failed\n`);process.exit(fail?1:0);});
